<!doctype html>
<html><head><meta charset="utf-8"><style>@page{margin:30px}body{font-family:DejaVu Sans;font-size:10px;color:#172033}table{width:100%;border-collapse:collapse}th{background:#0f172a;color:#fff;text-align:left;padding:8px}td{padding:8px;border-bottom:1px solid #e2e8f0}.right{text-align:right}.muted{color:#64748b}.total{font-size:13px;font-weight:bold}.signature{margin-top:28px;text-align:right}.signature img{display:block;max-width:130px;max-height:52px;margin-left:auto;object-fit:contain}.signature p{margin:4px 0 0}.invoice-watermark{height:38%;left:15%;opacity:.12;position:fixed;text-align:center;top:31%;width:70%;z-index:0}.invoice-watermark img{height:100%;max-width:100%;object-fit:contain;width:auto}.invoice-watermark~*{position:relative;z-index:1}.payment-details{border-top:1px solid #cbd5e1;font-size:8px;line-height:1.4;margin-top:15px;padding-top:8px;page-break-inside:avoid}.payment-details table{margin-top:4px;table-layout:fixed;width:100%}.payment-details td{border:0;padding:1px 5px 1px 0;vertical-align:top}.payment-details td:first-child{color:#64748b;width:28%}.payment-details-value{overflow-wrap:anywhere;word-break:break-word}</style></head>
<body>
@php($render = ['watermark' => $presentation['watermark'], 'payment_details' => $presentation['payment_details'], 'setting' => (object) ['paper_format' => 'a4']])
@include('invoice-templates.partials.watermark')
<p style="color:#0f766e;font-weight:bold">RETAILPOS.BIZ · POWERED BY CRYSTALPRO</p>
<table><tr><td><h1>{{ $presentation['document_title'] }}</h1><strong>{{ $proforma->proforma_number }}</strong></td><td class="right">Invoice date: {{ $proforma->invoice_date?->format('d M Y') }}<br>Due date: {{ $proforma->due_date?->format('d M Y') }}</td></tr></table>
<p><strong>Prepared for:</strong><br>{{ $proforma->customer_company ?: $proforma->customer_name }}<br>{{ $proforma->customer_email }}<br>{{ $proforma->billing_address }}</p>
<table><thead><tr><th>Item</th><th class="right">Qty</th>@if($isGst)<th class="right">GST</th>@endif<th class="right">Total</th></tr></thead><tbody>@foreach($proforma->items as $item)<tr><td>{{ $item->name }}</td><td class="right">{{ $item->quantity }}</td>@if($isGst)<td class="right">{{ number_format((float) $item->tax_rate, 2) }}%</td>@endif<td class="right">{{ $proforma->currency }} {{ number_format((float) $item->line_total, 2) }}</td></tr>@endforeach</tbody></table>
<table style="margin-top:20px;margin-left:auto;width:260px"><tr><td>Subtotal</td><td class="right">{{ $proforma->currency }} {{ number_format((float) $proforma->subtotal, 2) }}</td></tr>@if($isGst)<tr><td>GST</td><td class="right">{{ $proforma->currency }} {{ number_format((float) $proforma->tax_total, 2) }}</td></tr>@endif<tr class="total"><td>Total</td><td class="right">{{ $proforma->currency }} {{ number_format((float) $proforma->grand_total, 2) }}</td></tr><tr><td>Paid</td><td class="right">{{ number_format((float) $proforma->paid_amount, 2) }}</td></tr><tr class="total"><td>Balance</td><td class="right">{{ number_format((float) $proforma->balance_amount, 2) }}</td></tr></table>
@if($proforma->terms_conditions)<h3>Terms</h3><p>{!! nl2br(e($proforma->terms_conditions)) !!}</p>@endif
@include('invoice-templates.partials.payment-details')
@if($proforma->show_authorized_signature && ($signature['data_uri'] || $signature['name']))<div class="signature"><p>For {{ $proforma->company?->name ?? 'Company' }}</p>@if($signature['data_uri'])<img src="{{ $signature['data_uri'] }}" alt="Authorized signature">@endif<p><strong>{{ $signature['name'] ?: 'Authorized Signatory' }}</strong></p>@if($signature['designation'])<p class="muted">{{ $signature['designation'] }}</p>@endif</div>@endif
</body></html>
