@extends('layouts.pos')
@section('title', 'POS Dashboard')
@section('content')
<main class="min-h-screen bg-slate-50 p-4 sm:p-6 lg:p-8">
    <div class="mx-auto max-w-7xl">
        <header class="flex flex-wrap items-start justify-between gap-4"><div><a href="{{ route('dashboard') }}" class="text-sm font-semibold text-teal-700">Command Center</a><h1 class="mt-2 text-2xl font-bold text-slate-950">POS dashboard</h1><p class="mt-1 text-sm text-slate-500">{{ auth()->user()->branch?->name ?? 'All branches' }} sales activity for today.</p></div><div class="flex flex-wrap gap-2"><a href="{{ route('pos.sales.index') }}" class="pos-secondary-action">Sales history</a><a href="{{ route('pos.mobile') }}" class="pos-secondary-action">Mobile POS</a><a href="{{ route('pos.held.index') }}" class="pos-secondary-action">Held bills <span class="ml-1 rounded-full bg-slate-100 px-1.5 py-0.5 text-xs">{{ $summary['held_bills'] }}</span></a><a href="{{ route('pos.terminal') }}" class="pos-primary-action">Open terminal</a></div></header>

        <section class="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><div class="pos-dashboard-stat"><span>Today sales</span><strong>{{ number_format($summary['today_sales'], 2) }}</strong></div><div class="pos-dashboard-stat"><span>Today bills</span><strong>{{ number_format($summary['today_bills']) }}</strong></div><div class="pos-dashboard-stat"><span>Average bill</span><strong>{{ number_format($summary['average_bill'], 2) }}</strong></div><div class="pos-dashboard-stat"><span>Held bills</span><strong>{{ number_format($summary['held_bills']) }}</strong></div><div class="pos-dashboard-stat"><span>Cashiers active today</span><strong>{{ number_format($summary['active_cashiers']) }}</strong></div></section>

        <section class="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1.45fr)_minmax(19rem,0.8fr)]"><div class="pos-dashboard-panel"><div class="flex items-center justify-between"><div><h2 class="font-bold text-slate-900">Recent bills</h2><p class="mt-1 text-sm text-slate-500">Completed sales in this branch.</p></div><a href="{{ route('pos.terminal') }}" class="text-sm font-semibold text-teal-700">New sale</a></div><div class="mt-5 overflow-x-auto"><table class="w-full min-w-[38rem] text-left text-sm"><thead class="border-b border-slate-200 text-xs uppercase tracking-[0.1em] text-slate-400"><tr><th class="pb-3 font-semibold">Bill</th><th class="pb-3 font-semibold">Customer</th><th class="pb-3 font-semibold">Cashier</th><th class="pb-3 text-right font-semibold">Payment</th><th class="pb-3 text-right font-semibold">Total</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($summary['recent_sales'] as $sale)<tr><td class="py-3"><a class="font-semibold text-teal-700" href="{{ route('pos.receipts.show', $sale) }}">{{ $sale->sale_number }}</a><p class="mt-0.5 text-xs text-slate-400">{{ $sale->completed_at?->format('h:i A') }}</p></td><td class="py-3 text-slate-600">{{ $sale->customer?->display_name ?? 'Walk-in' }}</td><td class="py-3 text-slate-600">{{ $sale->completer?->name ?? '—' }}</td><td class="py-3 text-right text-slate-600">{{ $sale->payments->pluck('payment_method')->map(fn ($method) => strtoupper($method))->join(', ') }}</td><td class="py-3 text-right font-semibold">{{ number_format($sale->total_amount, 2) }}</td></tr>@empty<tr><td colspan="5" class="py-12 text-center text-slate-500">No completed POS bills for this branch today.</td></tr>@endforelse</tbody></table></div></div>
            <div class="space-y-6"><div class="pos-dashboard-panel"><h2 class="font-bold text-slate-900">Payment split</h2><div class="mt-4 space-y-3">@forelse($summary['payments'] as $method => $amount)<div class="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2.5 text-sm"><span class="font-medium text-slate-700">{{ strtoupper($method) }}</span><span class="font-bold text-slate-900">{{ number_format($amount, 2) }}</span></div>@empty<p class="py-6 text-center text-sm text-slate-500">No payments recorded today.</p>@endforelse</div></div><div class="pos-dashboard-panel"><h2 class="font-bold text-slate-900">Top products</h2><div class="mt-4 space-y-3">@forelse($summary['top_products'] as $product)<div class="flex items-center justify-between gap-3"><div class="min-w-0"><p class="truncate text-sm font-semibold text-slate-700">{{ $product->product_name }}</p><p class="mt-0.5 text-xs text-slate-400">{{ $product->sku }} · {{ number_format($product->quantity_sold, 0) }} sold</p></div><span class="shrink-0 text-sm font-bold text-teal-700">{{ number_format($product->sales_total, 2) }}</span></div>@empty<p class="py-6 text-center text-sm text-slate-500">Top products appear after completed sales.</p>@endforelse</div></div></div></section>
    </div>
</main>
@endsection
