@extends('layouts.pos')
@section('title', 'POS')
@section('content')
@php
    $initialCart = $resumedSale?->items->map(fn ($item) => ['id' => $item->product_id, 'name' => $item->product_name, 'sku' => $item->sku, 'price' => (float) $item->unit_price, 'quantity' => (float) $item->quantity, 'category' => $item->category?->name, 'available_stock' => null])->values() ?? collect();
    $initialCustomer = $resumedSale?->customer ? ['id' => $resumedSale->customer->id, 'name' => $resumedSale->customer->display_name, 'mobile' => $resumedSale->customer->phone ?: $resumedSale->customer->whatsapp, 'group' => $resumedSale->customer->groups->first()?->group?->name, 'loyalty_points' => $resumedSale->customer->loyalty_points_balance, 'wallet_balance' => (float) $resumedSale->customer->wallet_balance, 'last_purchase_at' => $resumedSale->customer->last_purchase_at?->toDateString(), 'birthday' => $resumedSale->customer->date_of_birth?->format('d M'), 'retention_note' => $resumedSale->customer->insight?->segment_label] : null;
    $productPayload = fn ($product) => ['id' => $product->id, 'name' => $product->name, 'sku' => $product->sku, 'barcode' => $product->barcode, 'price' => (float) $product->selling_price, 'category' => $product->category?->name, 'available_stock' => (float) $product->stockLevels->sum('quantity_available')];
@endphp
<div data-pos-app data-catalog-url="{{ route('pos.catalog') }}" data-customer-url="{{ route('pos.customers.lookup') }}" data-quick-customer-url="{{ route('pos.customers.quick-create') }}" data-checkout-url="{{ route('pos.checkout') }}" data-hold-url="{{ route('pos.hold') }}" data-initial-cart='@json($initialCart)' data-initial-customer='@json($initialCustomer)'>
    <div class="hidden min-h-screen lg:flex lg:flex-col">
        <header class="flex h-16 items-center justify-between border-b border-slate-200 bg-white px-6 shadow-sm">
            <div class="flex items-center gap-4"><a href="{{ route('dashboard') }}" class="grid size-9 place-items-center rounded-lg bg-teal-700 text-sm font-bold text-white">RP</a><div><p class="text-sm font-semibold">Point of Sale</p><p class="text-xs text-slate-500">{{ auth()->user()->branch?->name ?? 'Primary branch' }}</p></div></div>
            <div class="flex items-center gap-3"><span class="rounded-full bg-teal-50 px-3 py-1 text-xs font-semibold text-teal-700">{{ auth()->user()->name }}</span><a href="{{ route('dashboard') }}" class="rounded-lg p-2 text-slate-500 hover:bg-slate-100" aria-label="Exit POS"><x-icon name="x" class="size-5" /></a></div>
        </header>
        <main class="grid min-h-0 flex-1 grid-cols-[minmax(0,1fr)_25rem]">
            <section class="min-w-0 border-r border-slate-200 bg-slate-50 p-5">
                <div class="flex items-center gap-3"><div class="relative flex-1"><x-icon name="barcode" class="pointer-events-none absolute left-3 top-3.5 size-5 text-slate-400" /><input data-pos-scanner class="w-full pl-11" placeholder="Scan barcode or search products" autocomplete="off"></div><button type="button" data-pos-search class="inline-flex min-h-11 items-center gap-2 rounded-lg bg-slate-900 px-4 text-sm font-semibold text-white hover:bg-slate-800"><x-icon name="barcode" class="size-4" />Scan</button></div>
                <div class="mt-5 flex items-center justify-between"><h1 class="text-lg font-semibold">Products</h1><span data-pos-product-count class="text-sm text-slate-500">{{ $products->count() }} available</span></div>
                <div class="mt-4 grid grid-cols-2 gap-3 xl:grid-cols-3 2xl:grid-cols-4" data-pos-products>
                    @foreach($products as $product)<button type="button" data-pos-product='@json($productPayload($product))' class="pos-product-card text-left"><span class="grid aspect-[4/3] place-items-center rounded-md bg-teal-50 text-xl font-semibold text-teal-700">{{ str($product->name)->substr(0,1) }}</span><span class="mt-3 block truncate text-sm font-semibold">{{ $product->name }}</span><span class="mt-1 flex items-center justify-between text-xs text-slate-500"><span>{{ $product->sku }}</span><span class="font-semibold text-slate-900">{{ number_format($product->selling_price,2) }}</span></span></button>@endforeach
                </div>
            </section>
            <aside class="flex min-h-0 flex-col bg-white" data-pos-cart-panel>
                <div class="border-b border-slate-200 p-5"><div class="flex items-center justify-between"><h2 class="font-semibold">Current bill</h2><button type="button" data-pos-clear class="rounded-md p-2 text-slate-400 hover:bg-slate-100" aria-label="Clear cart"><x-icon name="x" class="size-4" /></button></div><div class="mt-4"><label class="sr-only" for="desktop-customer-mobile">Customer mobile</label><div class="flex gap-2"><input id="desktop-customer-mobile" data-pos-customer-mobile class="min-w-0 flex-1" placeholder="Customer mobile"><button type="button" data-pos-customer-search class="rounded-lg bg-slate-950 px-3 text-sm font-semibold text-white">Find</button></div></div><div data-pos-customer-card class="mt-3"></div><div data-pos-quick-customer class="mt-3 hidden"></div></div>
                <div class="min-h-0 flex-1 overflow-y-auto p-5"><div data-pos-suggestions class="mb-5"></div><div data-pos-cart-items class="space-y-3"></div><p data-pos-empty-cart class="py-12 text-center text-sm text-slate-500">Add products to start a bill.</p></div>
                <div class="border-t border-slate-200 p-5"><div class="flex gap-2"><input data-pos-discount type="number" min="0" step="0.01" placeholder="Manual discount"><input data-pos-coupon placeholder="Coupon"></div><div class="mt-4 space-y-2 text-sm"><div class="flex justify-between text-slate-500"><span>Subtotal</span><span data-pos-subtotal>0.00</span></div><div class="flex justify-between text-slate-500"><span>Discount</span><span data-pos-discount-total>0.00</span></div><div class="flex justify-between text-lg font-semibold"><span>Total</span><span data-pos-total>0.00</span></div></div><div class="mt-4 grid grid-cols-3 gap-2" data-pos-payment-methods><button type="button" data-payment-method="cash" class="pos-payment-method">Cash</button><button type="button" data-payment-method="card" class="pos-payment-method">Card</button><button type="button" data-payment-method="upi" class="pos-payment-method">UPI</button></div><input data-pos-payment-amount type="number" min="0" step="0.01" class="mt-2 w-full" placeholder="Payment amount"><div class="mt-4 grid grid-cols-2 gap-3"><button type="button" data-pos-hold class="pos-secondary-action">Hold bill</button><button type="button" data-pos-checkout class="pos-primary-action">Pay & receipt</button></div></div>
            </aside>
        </main>
    </div>

    <div class="min-h-screen pb-24 lg:hidden" data-pos-mobile>
        <header class="sticky top-0 z-20 flex items-center justify-between border-b border-slate-200 bg-white px-4 py-3"><div><p class="text-base font-semibold">RetailPOS</p><p class="text-xs text-slate-500">{{ auth()->user()->branch?->name ?? 'Primary branch' }}</p></div><a href="{{ route('dashboard') }}" class="grid size-10 place-items-center rounded-lg bg-slate-100 text-slate-600" aria-label="Exit POS"><x-icon name="x" class="size-5" /></a></header>
        <main class="p-4"><section data-pos-mobile-pane="sell"><div class="relative"><x-icon name="barcode" class="pointer-events-none absolute left-3 top-3.5 size-5 text-slate-400" /><input data-pos-scanner class="w-full pl-11" placeholder="Search or scan" autocomplete="off"></div><div class="mt-4 grid grid-cols-2 gap-3" data-pos-products-mobile>@foreach($products as $product)<button type="button" data-pos-product='@json($productPayload($product))' class="pos-product-card text-left"><span class="grid aspect-square place-items-center rounded-md bg-teal-50 text-lg font-semibold text-teal-700">{{ str($product->name)->substr(0,1) }}</span><span class="mt-2 block truncate text-sm font-semibold">{{ $product->name }}</span><span class="mt-1 block text-sm font-semibold text-teal-700">{{ number_format($product->selling_price,2) }}</span></button>@endforeach</div></section>
            <section data-pos-mobile-pane="customer" class="hidden"><h1 class="text-xl font-semibold">Customer</h1><div class="mt-4 flex gap-2"><input data-pos-customer-mobile placeholder="Mobile number" inputmode="tel" class="min-w-0 flex-1"><button type="button" data-pos-customer-search class="rounded-lg bg-slate-950 px-4 text-sm font-semibold text-white">Find</button></div><div data-pos-customer-card class="mt-4"></div><div data-pos-quick-customer class="mt-4 hidden"></div><div data-pos-suggestions class="mt-5"></div></section>
            <section data-pos-mobile-pane="held" class="hidden"><h1 class="text-xl font-semibold">Held bills</h1><div class="mt-4 space-y-3">@forelse($heldSales as $sale)<a href="{{ route('pos.held.resume',$sale) }}" class="block rounded-lg border border-slate-200 bg-white p-4 shadow-sm"><div class="flex justify-between"><span class="font-semibold">{{ $sale->sale_number }}</span><span class="text-sm text-slate-500">{{ number_format($sale->total_amount,2) }}</span></div><p class="mt-1 text-sm text-slate-500">{{ $sale->customer?->display_name ?? 'Walk-in' }}</p></a>@empty<p class="py-12 text-center text-sm text-slate-500">No held bills.</p>@endforelse</div></section></main>
        <button type="button" data-pos-open-cart class="fixed inset-x-4 bottom-20 z-30 flex min-h-14 items-center justify-between rounded-lg bg-slate-950 px-5 text-white shadow-xl"><span data-pos-cart-count>0 items</span><span data-pos-total>0.00</span></button>
        <div data-pos-cart-drawer class="fixed inset-x-0 bottom-0 z-40 hidden max-h-[88vh] overflow-y-auto rounded-t-xl bg-white p-4 shadow-2xl"><div class="mx-auto h-1.5 w-10 rounded-full bg-slate-200"></div><div class="mt-4 flex items-center justify-between"><h2 class="text-lg font-semibold">Current bill</h2><button type="button" data-pos-close-cart class="rounded-lg p-2 text-slate-500" aria-label="Close cart"><x-icon name="x" class="size-5" /></button></div><div data-pos-cart-items class="mt-4 space-y-3"></div><div class="mt-5 rounded-lg bg-slate-50 p-4"><label class="text-sm font-medium">Discount</label><input data-pos-discount type="number" min="0" step="0.01" placeholder="0.00" class="mt-2 w-full"><div class="mt-4 flex justify-between text-lg font-semibold"><span>Total</span><span data-pos-total>0.00</span></div></div><div class="mt-4"><p class="text-sm font-medium">Payment</p><div class="mt-2 grid grid-cols-3 gap-2" data-pos-payment-methods><button type="button" data-payment-method="cash" class="pos-payment-method">Cash</button><button type="button" data-payment-method="card" class="pos-payment-method">Card</button><button type="button" data-payment-method="upi" class="pos-payment-method">UPI</button></div><input data-pos-payment-amount type="number" min="0" step="0.01" class="mt-2 w-full" placeholder="Amount received"></div><div class="mt-5 grid grid-cols-2 gap-3"><button type="button" data-pos-hold class="pos-secondary-action">Hold</button><button type="button" data-pos-checkout class="pos-primary-action">Pay</button></div></div>
        <nav class="fixed inset-x-0 bottom-0 z-30 flex h-16 border-t border-slate-200 bg-white pb-[env(safe-area-inset-bottom)]"><button type="button" data-pos-mobile-tab="sell" class="pos-mobile-nav is-active">Sell</button><button type="button" data-pos-mobile-tab="customer" class="pos-mobile-nav">Customer</button><button type="button" data-pos-mobile-tab="held" class="pos-mobile-nav">Held</button></nav>
    </div>
    <form data-pos-submit method="POST" class="hidden">@csrf</form>
</div>
@endsection
