@extends('layouts.pos')
@section('title', $posMode === 'terminal' ? 'POS Terminal' : ($posMode === 'mobile' ? 'Mobile POS' : 'POS Billing'))
@section('content')
@php
    $isTerminal = $posMode === 'terminal';
    $isMobileOnly = $posMode === 'mobile';
    $initialCart = $resumedSale?->items->map(fn ($item) => ['id' => $item->product_id, 'name' => $item->product_name, 'sku' => $item->sku, 'price' => (float) $item->unit_price, 'quantity' => (float) $item->quantity, 'category' => $item->category?->name, 'available_stock' => null, 'track_inventory' => false])->values() ?? collect();
    $initialCustomer = $resumedSale?->customer ? ['id' => $resumedSale->customer->id, 'name' => $resumedSale->customer->display_name, 'mobile' => $resumedSale->customer->phone ?: $resumedSale->customer->whatsapp, 'group' => $resumedSale->customer->groups->first()?->group?->name, 'loyalty_points' => $resumedSale->customer->loyalty_points_balance, 'wallet_balance' => (float) $resumedSale->customer->wallet_balance, 'last_purchase_at' => $resumedSale->customer->last_purchase_at?->toDateString(), 'birthday' => $resumedSale->customer->date_of_birth?->format('d M'), 'retention_note' => $resumedSale->customer->insight?->segment_label] : null;
    $productPayload = fn ($product) => ['id' => $product->id, 'name' => $product->name, 'sku' => $product->sku, 'barcode' => $product->barcode, 'price' => (float) $product->selling_price, 'category' => $product->category?->name, 'brand' => $product->brand?->name, 'category_id' => $product->category_id, 'image' => $product->image, 'track_inventory' => (bool) $product->track_inventory, 'available_stock' => (float) $product->stockLevels->sum('quantity_available'), 'low_stock' => $product->track_inventory && $product->stockLevels->sum('quantity_available') > 0 && $product->stockLevels->sum('quantity_available') <= 5];
@endphp

<div data-pos-app data-pos-mode="{{ $posMode }}" data-catalog-url="{{ route('pos.catalog') }}" data-customer-url="{{ route('pos.customers.lookup') }}" data-quick-customer-url="{{ route('pos.customers.quick-create') }}" data-checkout-url="{{ route('pos.checkout') }}" data-hold-url="{{ route('pos.hold') }}" data-initial-cart='@json($initialCart)' data-initial-customer='@json($initialCustomer)' class="pos-workspace {{ $isTerminal ? 'pos-terminal-mode' : '' }}">
    <div class="{{ $isMobileOnly ? 'hidden' : 'flex' }} min-h-screen flex-col overflow-hidden">
        <header class="pos-terminal-header">
            <div class="flex min-w-0 items-center gap-3">
                <div class="grid size-10 shrink-0 place-items-center rounded-xl bg-teal-700 text-sm font-bold text-white">RP</div>
                <div class="min-w-0"><p class="truncate text-sm font-bold text-slate-900">{{ auth()->user()->company?->name ?? 'RetailPOS' }}</p><p class="truncate text-xs text-slate-500">{{ auth()->user()->branch?->name ?? 'Primary branch' }} <span class="mx-1 text-slate-300">/</span> {{ auth()->user()->name }}</p></div>
                <span class="hidden rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700 sm:inline-flex">Session active</span>
            </div>
            <div class="flex items-center gap-2 text-xs text-slate-500">
                <span class="hidden lg:inline" data-pos-clock>{{ now()->format('d M, h:i A') }}</span>
                <span class="hidden rounded-lg bg-slate-100 px-2.5 py-1.5 font-semibold text-slate-600 sm:inline">{{ $resumedSale ? 'Resumed '.$resumedSale->sale_number : 'New draft' }}</span>
                <a href="{{ route('pos.dashboard') }}" class="pos-icon-button" title="POS dashboard" aria-label="POS dashboard"><x-icon name="dashboard" class="size-4" /></a>
                <button type="button" data-pos-fullscreen class="pos-icon-button" title="Enter fullscreen terminal mode" aria-label="Enter fullscreen terminal mode"><x-icon name="layout" class="size-4" /></button>
                <a href="{{ route('dashboard') }}" class="pos-icon-button" title="Exit to Command Center" aria-label="Exit to Command Center"><x-icon name="x" class="size-4" /></a>
            </div>
        </header>

        <main class="pos-terminal-grid">
            <section class="pos-catalog-pane">
                <div class="pos-search-row">
                    <div class="relative min-w-0 flex-1"><x-icon name="barcode" class="pointer-events-none absolute left-4 top-1/2 size-5 -translate-y-1/2 text-teal-700" /><input data-pos-scanner class="pos-scanner-input w-full pl-12" placeholder="Scan barcode or search products" autocomplete="off" autofocus></div>
                    <button type="button" data-pos-search class="pos-scan-action" title="Focus barcode search (F2 or /)"><x-icon name="barcode" class="size-4" /><span class="hidden sm:inline">Scan</span></button>
                </div>
                <p data-pos-feedback class="pos-feedback hidden" role="status" aria-live="polite"></p>

                <div class="pos-catalog-toolbar">
                    <div class="flex min-w-0 gap-2 overflow-x-auto pb-1" data-pos-categories><button type="button" data-pos-category="" class="pos-category is-active">All products</button>@foreach($categories as $category)<button type="button" data-pos-category="{{ $category->id }}" class="pos-category">{{ $category->name }}</button>@endforeach</div>
                    <span data-pos-product-count class="shrink-0 text-xs font-medium text-slate-500">{{ $products->count() }} available</span>
                </div>

                <div class="pos-product-grid" data-pos-products>
                    @foreach($products as $product)
                        <button type="button" data-pos-product='@json($productPayload($product))' class="pos-product-card text-left">
                            <span class="pos-product-visual">@if($product->image)<img src="{{ $product->image }}" alt="" class="size-full object-cover">@else{{ str($product->name)->substr(0, 1) }}@endif</span>
                            <span class="mt-3 flex items-start justify-between gap-2"><span class="min-w-0"><span class="block truncate text-sm font-semibold text-slate-900">{{ $product->name }}</span><span class="mt-1 block truncate text-xs text-slate-500">{{ $product->brand?->name ?? $product->category?->name ?? 'Product' }}</span></span><span class="shrink-0 text-sm font-bold text-teal-700">{{ number_format($product->selling_price, 2) }}</span></span>
                            <span class="mt-2 flex items-center justify-between gap-2 text-xs"><span class="truncate text-slate-400">{{ $product->sku }}</span>@if($product->track_inventory)<span class="{{ $product->stockLevels->sum('quantity_available') <= 5 ? 'text-amber-700' : 'text-emerald-700' }} font-semibold">{{ number_format($product->stockLevels->sum('quantity_available'), 0) }} in stock</span>@endif</span>
                        </button>
                    @endforeach
                </div>
            </section>

            <aside class="pos-cart-pane" data-pos-cart-panel>
                <div class="pos-cart-heading"><div><p class="text-xs font-semibold uppercase tracking-[0.12em] text-slate-400">Current bill</p><h1 class="mt-1 text-lg font-bold text-slate-900">{{ $resumedSale ? 'Resumed bill' : 'New sale' }}</h1></div><button type="button" data-pos-clear class="pos-icon-button" title="Clear current bill" aria-label="Clear current bill"><x-icon name="x" class="size-4" /></button></div>
                <div class="pos-customer-lookup"><label class="sr-only" for="desktop-customer-mobile">Customer mobile</label><div class="flex gap-2"><input id="desktop-customer-mobile" data-pos-customer-mobile class="min-w-0 flex-1" placeholder="Customer mobile (F4)" inputmode="tel"><button type="button" data-pos-customer-search class="pos-find-customer">Find</button></div><p data-pos-customer-loading class="mt-2 hidden text-xs font-medium text-teal-700">Looking up customer…</p><div data-pos-customer-card class="mt-3"></div><div data-pos-quick-customer class="mt-3 hidden"></div></div>
                <div class="pos-cart-scroll"><div data-pos-suggestions></div><div data-pos-cart-items class="space-y-2"></div><div data-pos-empty-cart class="pos-empty-cart"><x-icon name="pos" class="size-8 text-slate-300" /><p class="mt-3 font-semibold text-slate-700">Start a new bill</p><p class="mt-1 text-sm text-slate-500">Scan a barcode or tap a product.</p></div></div>
                <div class="pos-bill-footer">
                    <div class="grid grid-cols-2 gap-2"><input data-pos-discount type="number" min="0" step="0.01" placeholder="Manual discount"><input data-pos-coupon placeholder="Coupon code"></div>
                    <div class="mt-3 space-y-1.5 text-sm"><div class="flex justify-between text-slate-500"><span>Subtotal</span><span data-pos-subtotal>0.00</span></div><div class="flex justify-between text-slate-500"><span>Manual discount</span><span data-pos-discount-total>0.00</span></div><div class="flex justify-between text-slate-500"><span>Promotion discount</span><span>Evaluated at checkout</span></div><div class="flex justify-between text-slate-500"><span>Tax</span><span>0.00</span></div></div>
                    <div class="pos-grand-total"><span>Grand total</span><span data-pos-total>0.00</span></div>
                    <div class="mt-3 grid grid-cols-3 gap-2" data-pos-payment-methods><button type="button" data-payment-method="cash" class="pos-payment-method">Cash</button><button type="button" data-payment-method="card" class="pos-payment-method">Card</button><button type="button" data-payment-method="upi" class="pos-payment-method">UPI</button><button type="button" data-pos-payment-foundation class="pos-payment-method" title="Wallet settlement is not enabled">Wallet</button><button type="button" data-pos-payment-foundation class="pos-payment-method" title="Credit sale terms are not enabled">Credit</button><button type="button" data-pos-split-foundation class="pos-payment-method" title="Split payment is prepared for a later payment workflow">Split</button></div>
                    <div class="mt-2 grid grid-cols-[minmax(0,1fr)_minmax(0,1fr)] gap-2"><input data-pos-payment-amount type="number" min="0" step="0.01" placeholder="Amount received"><input data-pos-payment-reference placeholder="Card/UPI reference"></div><div class="mt-2 flex justify-between text-xs text-slate-500"><span>Paid <span data-pos-paid>0.00</span></span><span>Change <span data-pos-change>0.00</span></span></div>
                    <div class="mt-4 grid grid-cols-[0.85fr_1.35fr] gap-3"><button type="button" data-pos-hold class="pos-secondary-action" title="Hold bill (F8)">Hold</button><button type="button" data-pos-checkout class="pos-primary-action" title="Complete sale (F9)">Pay &amp; receipt</button></div>
                </div>
            </aside>
        </main>
    </div>

    <div class="{{ $isMobileOnly ? 'block' : 'lg:hidden' }} min-h-screen bg-slate-50 pb-36" data-pos-mobile>
        <header class="pos-mobile-header"><div><p class="text-base font-bold text-slate-900">RetailPOS</p><p class="text-xs text-slate-500">{{ auth()->user()->branch?->name ?? 'Primary branch' }}</p></div><div class="flex items-center gap-2"><span class="grid size-9 place-items-center rounded-full bg-teal-50 text-xs font-bold text-teal-700" data-pos-cart-count>0</span><a href="{{ route('pos.dashboard') }}" class="pos-icon-button" aria-label="POS dashboard"><x-icon name="dashboard" class="size-4" /></a></div></header>
        <main class="p-4">
            <section data-pos-mobile-pane="products"><div class="relative"><x-icon name="barcode" class="pointer-events-none absolute left-4 top-1/2 size-5 -translate-y-1/2 text-teal-700" /><input data-pos-scanner class="pos-scanner-input w-full pl-12" placeholder="Search or scan" autocomplete="off"></div><p data-pos-feedback class="pos-feedback hidden" role="status"></p><div class="mt-4 flex gap-2 overflow-x-auto pb-1" data-pos-categories><button type="button" data-pos-category="" class="pos-category is-active">All</button>@foreach($categories as $category)<button type="button" data-pos-category="{{ $category->id }}" class="pos-category">{{ $category->name }}</button>@endforeach</div><div class="pos-product-grid mt-4" data-pos-products-mobile>@foreach($products as $product)<button type="button" data-pos-product='@json($productPayload($product))' class="pos-product-card text-left"><span class="pos-product-visual">{{ str($product->name)->substr(0, 1) }}</span><span class="mt-2 block truncate text-sm font-semibold text-slate-900">{{ $product->name }}</span><span class="mt-1 flex justify-between text-xs"><span class="truncate text-slate-500">{{ $product->sku }}</span><span class="font-bold text-teal-700">{{ number_format($product->selling_price, 2) }}</span></span></button>@endforeach</div></section>
            <section data-pos-mobile-pane="customer" class="hidden"><h1 class="text-xl font-bold">Customer</h1><p class="mt-1 text-sm text-slate-500">Find purchase history with a mobile number.</p><div class="mt-4 flex gap-2"><input data-pos-customer-mobile class="min-w-0 flex-1" placeholder="Mobile number" inputmode="tel"><button type="button" data-pos-customer-search class="pos-find-customer">Find</button></div><p data-pos-customer-loading class="mt-2 hidden text-xs font-medium text-teal-700">Looking up customer…</p><div data-pos-customer-card class="mt-4"></div><div data-pos-quick-customer class="mt-4 hidden"></div><div data-pos-suggestions class="mt-5"></div></section>
            <section data-pos-mobile-pane="cart" class="hidden"><div class="flex items-center justify-between"><div><h1 class="text-xl font-bold">Current bill</h1><p class="mt-1 text-sm text-slate-500" data-pos-cart-count>0 items</p></div><button type="button" data-pos-clear class="pos-icon-button" aria-label="Clear cart"><x-icon name="x" class="size-4" /></button></div><div data-pos-cart-items class="mt-5 space-y-2"></div><div data-pos-empty-cart class="pos-empty-cart mt-5"><x-icon name="pos" class="size-8 text-slate-300" /><p class="mt-3 font-semibold text-slate-700">Your cart is empty</p></div><div class="mt-5 rounded-xl border border-slate-200 bg-white p-4"><input data-pos-discount type="number" min="0" step="0.01" class="w-full" placeholder="Manual discount"><div class="mt-4 flex justify-between text-lg font-bold"><span>Total</span><span data-pos-total>0.00</span></div></div></section>
            <section data-pos-mobile-pane="payment" class="hidden"><h1 class="text-xl font-bold">Payment</h1><div class="pos-grand-total mt-4"><span>Amount payable</span><span data-pos-total>0.00</span></div><div class="mt-4 grid grid-cols-2 gap-3" data-pos-payment-methods><button type="button" data-payment-method="cash" class="pos-payment-method">Cash</button><button type="button" data-payment-method="card" class="pos-payment-method">Card</button><button type="button" data-payment-method="upi" class="pos-payment-method">UPI</button><button type="button" data-pos-payment-foundation class="pos-payment-method">Wallet</button></div><div class="mt-4 space-y-2"><input data-pos-payment-amount type="number" min="0" step="0.01" class="w-full" placeholder="Amount received"><input data-pos-payment-reference class="w-full" placeholder="Card/UPI reference"></div><div class="mt-3 flex justify-between text-sm text-slate-500"><span>Paid <span data-pos-paid>0.00</span></span><span>Change <span data-pos-change>0.00</span></span></div><button type="button" data-pos-checkout class="pos-primary-action mt-5 w-full">Complete sale</button></section>
            <section data-pos-mobile-pane="more" class="hidden"><h1 class="text-xl font-bold">More</h1><div class="mt-4 space-y-2"><a href="{{ route('pos.held.index') }}" class="pos-more-row"><span>Held bills</span><span>{{ $heldSales->count() }}</span></a><a href="{{ route('pos.dashboard') }}" class="pos-more-row"><span>POS dashboard</span><x-icon name="dashboard" class="size-4" /></a><a href="{{ route('dashboard') }}" class="pos-more-row"><span>Exit POS</span><x-icon name="x" class="size-4" /></a></div></section>
        </main>
        <div class="fixed inset-x-0 bottom-16 z-20 border-t border-slate-200 bg-white px-4 py-3"><div class="flex items-center justify-between"><span class="text-sm text-slate-500" data-pos-cart-count>0 items</span><strong class="text-lg" data-pos-total>0.00</strong></div><div class="mt-2 grid grid-cols-2 gap-2"><button type="button" data-pos-hold class="pos-secondary-action">Hold</button><button type="button" data-pos-mobile-tab="payment" class="pos-primary-action">Pay</button></div></div>
        <nav class="pos-mobile-bottom-nav"><button type="button" data-pos-mobile-tab="products" class="pos-mobile-nav is-active">Products</button><button type="button" data-pos-mobile-tab="customer" class="pos-mobile-nav">Customer</button><button type="button" data-pos-mobile-tab="cart" class="pos-mobile-nav">Cart</button><button type="button" data-pos-mobile-tab="payment" class="pos-mobile-nav">Payment</button><button type="button" data-pos-mobile-tab="more" class="pos-mobile-nav">More</button></nav>
    </div>
    <form data-pos-submit method="POST" class="hidden">@csrf</form>
</div>
@endsection
