@extends('layouts.admin')

@section('title', 'Subscriptions')
@section('page-title', 'Subscriptions')
@section('breadcrumbs')<span>/</span><span>Platform</span><span>/</span><span>Subscriptions</span>@endsection

@section('content')
    @include('command-center.saas.partials.nav')
    <form class="mb-5 flex flex-wrap gap-3"><select name="status" class="rounded-md border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-950"><option value="">All statuses</option>@foreach(['trialing','active','grace_period','past_due','suspended','cancelled','expired'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ str($status)->headline() }}</option>@endforeach</select><button class="rounded-md border border-slate-300 px-3 py-2 text-sm font-medium dark:border-slate-700">Filter</button></form>
    <div class="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm dark:divide-slate-800"><thead class="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500 dark:bg-slate-800"><tr><th class="px-5 py-3">Tenant</th><th class="px-5 py-3">Plan</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Renewal</th><th class="px-5 py-3"></th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($subscriptions as $subscription)<tr class="hover:bg-slate-50 dark:hover:bg-slate-800"><td class="px-5 py-4"><a class="font-medium text-slate-900 dark:text-white" href="{{ route('saas.tenants.show', $subscription->company) }}">{{ $subscription->company?->name }}</a><p class="mt-1 text-xs text-slate-500">{{ $subscription->subscription_number }}</p></td><td class="px-5 py-4">{{ $subscription->plan?->name ?? 'Historical plan' }}</td><td class="px-5 py-4"><x-status-badge :status="$subscription->status" /></td><td class="px-5 py-4">{{ $subscription->renewal_date?->format('d M Y') ?? '—' }}</td><td class="px-5 py-4 text-right"><a href="{{ route('saas.tenants.show', $subscription->company) }}" class="font-medium text-sky-700 dark:text-sky-300">View</a></td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-slate-500">No subscriptions match this filter.</td></tr>@endforelse</tbody></table></div></div><div class="mt-4">{{ $subscriptions->links() }}</div>
@endsection
