@extends('layouts.admin')
@section('title', 'Theme Manager') @section('page-title', 'Theme Manager')
@section('breadcrumbs')<span>/</span><a href="{{ route('cms.dashboard') }}">CMS</a><span>/</span><span>Theme</span>@endsection
@section('content')
    <div class="space-y-6">
        @include('command-center.cms.partials.nav')
        <form method="POST" action="{{ route('cms.theme.update') }}" class="space-y-6">
            @csrf @method('PUT')
            <section class="cms-panel"><p class="cms-kicker">Visual editor</p><h1 class="mt-2 text-xl font-semibold text-slate-900">Website theme</h1><p class="mt-2 text-sm leading-6 text-slate-600">Choose calm visual tokens now. They are stored for the future website adapter and do not alter the separate public website in this phase.</p></section>
            <div class="grid gap-6 xl:grid-cols-[1.05fr_0.95fr]">
                <x-form-section title="Colour and shape tokens" help="Use hex values from your approved brand palette."><div class="grid gap-5 md:grid-cols-2">@foreach (['primary_color' => 'Primary colour', 'secondary_color' => 'Secondary colour', 'accent_color' => 'Accent colour', 'background_color' => 'Background colour', 'text_color' => 'Text colour', 'button_color' => 'Button colour'] as $field => $label)<label class="cms-control-label"><span class="flex items-center gap-2"><span class="size-4 rounded border border-slate-200" style="background: {{ old($field, $theme->{$field}) ?: '#cbd5e1' }}"></span>{{ $label }}</span><input name="{{ $field }}" value="{{ old($field, $theme->{$field}) }}" placeholder="#0f766e" class="mt-2 block w-full"></label>@endforeach
                    <label class="cms-control-label">Website theme mode<select name="website_theme_mode" class="mt-2 block w-full">@foreach (['clean_light' => 'Clean Light', 'premium_dark' => 'Premium Dark', 'soft_saas' => 'Soft SaaS'] as $key => $label)<option value="{{ $key }}" @selected(old('website_theme_mode', $theme->website_theme_mode) === $key)>{{ $label }}</option>@endforeach</select></label>
                    <label class="cms-control-label">Button radius<select name="button_radius_style" class="mt-2 block w-full">@foreach (['square', 'rounded', 'pill'] as $value)<option value="{{ $value }}" @selected(old('button_radius_style', $theme->button_radius_style) === $value)>{{ str($value)->headline() }}</option>@endforeach</select></label>
                    <label class="cms-control-label">Card radius<select name="card_radius_style" class="mt-2 block w-full">@foreach (['square', 'rounded', 'soft'] as $value)<option value="{{ $value }}" @selected(old('card_radius_style', $theme->card_radius_style) === $value)>{{ str($value)->headline() }}</option>@endforeach</select></label>
                    @foreach (['header_style' => 'Header style', 'footer_style' => 'Footer style', 'cta_button_style' => 'CTA button style'] as $field => $label)<label class="cms-control-label"><span>{{ $label }}</span><input name="{{ $field }}" value="{{ old($field, $theme->{$field}) }}" class="mt-2 block w-full"></label>@endforeach</div></x-form-section>
                <aside class="space-y-5"><section class="cms-panel"><p class="cms-kicker">Live style preview</p><div class="mt-4 overflow-hidden rounded-xl border border-slate-200" style="background: {{ $theme->background_color ?: '#ffffff' }}; color: {{ $theme->text_color ?: '#0f172a' }}"><div class="flex h-10 items-center justify-between px-4 text-xs font-semibold text-white" style="background: {{ $theme->primary_color ?: '#0f766e' }}"><span>RetailPOS</span><span>Products · Solutions · Contact</span></div><div class="p-5"><p class="text-lg font-semibold">Clear retail operations start here.</p><p class="mt-2 text-sm opacity-70">An easy-to-read website card preview using your current theme tokens.</p><button type="button" class="mt-5 px-4 py-2 text-sm font-semibold text-white shadow-sm" style="background: {{ $theme->button_color ?: '#0f766e' }}; border-radius: {{ $theme->button_radius_style === 'pill' ? '9999px' : ($theme->button_radius_style === 'square' ? '0px' : '8px') }}">Book a demo</button></div></div></section><section class="cms-panel"><p class="cms-kicker">Theme modes</p><div class="mt-4 grid gap-3">@foreach (['clean_light' => ['Clean Light', 'bg-white'], 'premium_dark' => ['Premium Dark', 'bg-slate-900 text-white'], 'soft_saas' => ['Soft SaaS', 'bg-sky-50']] as $key => [$label, $classes])<div class="rounded-xl border p-4 {{ $classes }} {{ $theme->website_theme_mode === $key ? 'border-teal-400 ring-2 ring-teal-100' : 'border-slate-200' }}"><p class="font-semibold">{{ $label }}</p><p class="mt-1 text-xs opacity-70">{{ $theme->website_theme_mode === $key ? 'Current saved selection' : 'Available website direction' }}</p></div>@endforeach</div></section></aside>
            </div>
            <x-sticky-form-actions><button class="cms-button-primary">Save theme</button></x-sticky-form-actions>
        </form>
    </div>
@endsection
