@php($campaign = $campaign ?? null)
<div class="grid gap-5 md:grid-cols-2">
    <label class="block text-sm font-medium text-slate-700 dark:text-slate-200">Campaign name<input name="name" required value="{{ old('name', $campaign?->name) }}" class="mt-1 block w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label>
    <label class="block text-sm font-medium text-slate-700 dark:text-slate-200">Slug<input name="slug" value="{{ old('slug', $campaign?->slug) }}" class="mt-1 block w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label>
    <label class="block text-sm font-medium text-slate-700 dark:text-slate-200">Campaign type<select name="campaign_type" class="mt-1 block w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950">@foreach($campaignTypes as $type)<option value="{{ $type->value }}" @selected(old('campaign_type', $campaign?->campaign_type?->value ?? 'manual') === $type->value)>{{ str($type->value)->headline() }}</option>@endforeach</select></label>
    <label class="block text-sm font-medium text-slate-700 dark:text-slate-200">Status<select name="status" class="mt-1 block w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950">@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(old('status', $campaign?->status?->value ?? 'draft') === $status->value)>{{ str($status->value)->headline() }}</option>@endforeach</select></label>
    <label class="block text-sm font-medium text-slate-700 dark:text-slate-200">Priority<input name="priority" type="number" min="0" value="{{ old('priority', $campaign?->priority ?? 100) }}" class="mt-1 block w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label>
    <label class="block text-sm font-medium text-slate-700 dark:text-slate-200">Starts at<input name="start_at" type="datetime-local" value="{{ old('start_at', $campaign?->start_at?->format('Y-m-d\TH:i')) }}" class="mt-1 block w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label>
    <label class="block text-sm font-medium text-slate-700 dark:text-slate-200 md:col-span-2">Ends at<input name="end_at" type="datetime-local" value="{{ old('end_at', $campaign?->end_at?->format('Y-m-d\TH:i')) }}" class="mt-1 block w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label>
    <label class="block text-sm font-medium text-slate-700 dark:text-slate-200 md:col-span-2">Description<textarea name="description" rows="4" class="mt-1 block w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950">{{ old('description', $campaign?->description) }}</textarea></label>
</div>
