@extends('layouts.admin')
@section('title', 'Customer Statement')
@section('page-title', 'Customer Statement')
@section('breadcrumbs')<span>/</span><span>Finance</span><span>/</span><span>Customer Statement</span>@endsection
@section('content')
@include('command-center.finance.partials.nav')
<div class="space-y-6"><header class="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p class="text-sm text-slate-500">{{ $customer->company_name ?: $customer->display_name }}</p><h1 class="mt-1 text-2xl font-semibold text-slate-950 dark:text-white">Customer statement</h1><p class="mt-1 text-sm text-slate-500">{{ $from->format('d M Y') }} to {{ $to->format('d M Y') }}</p></div><div class="flex flex-wrap gap-2">@can('finance.exports')<a href="{{ route('finance.customer-statements.csv',[$customer,'from'=>$from->toDateString(),'to'=>$to->toDateString()]) }}" class="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold dark:border-slate-700">CSV</a>@endcan<a href="{{ route('finance.customer-statements.pdf',[$customer,'from'=>$from->toDateString(),'to'=>$to->toDateString()]) }}" class="rounded-lg bg-slate-950 px-3 py-2 text-sm font-semibold text-white dark:bg-teal-300 dark:text-slate-950">Download PDF</a></div></header>
<section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Outstanding',$summary['outstanding']],['Overdue',$summary['overdue']],['Available credit',$summary['available_credit']],['Net exposure',$summary['net_exposure']]] as [$label,$value])<article class="rounded-lg border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><p class="text-xs font-semibold uppercase text-slate-500">{{ $label }}</p><p class="mt-2 text-xl font-semibold">₹{{ number_format($value/100,2) }}</p></article>@endforeach</section>
<form class="flex flex-col gap-3 rounded-lg border border-slate-200 bg-white p-4 sm:flex-row sm:items-end dark:border-slate-800 dark:bg-slate-900"><label class="text-sm font-medium">From<input type="date" name="from" value="{{ $from->toDateString() }}" class="mt-1 block rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">To<input type="date" name="to" value="{{ $to->toDateString() }}" class="mt-1 block rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><button class="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white dark:bg-teal-300 dark:text-slate-950">Update period</button></form>
@include('command-center.finance.partials.statement-ledger')
@can('finance.payments.allocate')
@if($credits->isNotEmpty() && $openInvoices->isNotEmpty())
<section class="rounded-lg border border-amber-200 bg-amber-50 p-5 dark:border-amber-900/60 dark:bg-amber-950/30"><h2 class="font-semibold text-slate-950 dark:text-white">Apply available customer credit</h2><p class="mt-1 text-sm text-slate-600 dark:text-slate-300">Choose a finalized credit note and an outstanding invoice. This records a credit allocation, not a payment or refund.</p><form method="POST" action="{{ route('finance.customer-credits.apply') }}" class="mt-4 grid gap-3 lg:grid-cols-[1fr_1fr_160px_auto]">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) \Illuminate\Support\Str::uuid() }}"><label class="text-sm font-medium">Available credit<select name="return_id" required class="mt-1 block w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950">@foreach($credits as $credit)<option value="{{ $credit->id }}">{{ $credit->credit_note_number }} · {{ $credit->currency }} {{ number_format((float)$credit->available_amount,2) }}</option>@endforeach</select></label><label class="text-sm font-medium">Outstanding invoice<select name="invoice_id" required class="mt-1 block w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950">@foreach($openInvoices as $invoice)<option value="{{ $invoice->id }}">{{ $invoice->invoice_number }} · {{ $invoice->currency }} {{ number_format((float)$invoice->balance_due,2) }}</option>@endforeach</select></label><label class="text-sm font-medium">Amount<input name="amount" type="number" min="0.01" step="0.01" required class="mt-1 block w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><button class="self-end rounded-lg bg-amber-700 px-4 py-2.5 text-sm font-semibold text-white">Apply credit</button></form></section>
@endif
@endcan
@can('finance.credit-limits.manage')<section class="rounded-lg border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold text-slate-950 dark:text-white">Credit terms</h2><p class="mt-1 text-sm text-slate-500">Leave the limit empty for unlimited credit. These controls never alter historical invoices.</p><form method="POST" action="{{ route('finance.customer-credit-limits.update',$customer) }}" class="mt-4 grid gap-3 sm:grid-cols-[1fr_1fr_auto]">@csrf @method('PUT')<label class="text-sm font-medium">Credit limit<input name="credit_limit" type="number" min="0" step="0.01" value="{{ $customer->credit_limit }}" class="mt-1 block w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Payment terms (days)<input name="credit_terms_days" type="number" min="0" max="3650" value="{{ $customer->credit_terms_days }}" class="mt-1 block w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><button class="self-end rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white dark:bg-teal-300 dark:text-slate-950">Save terms</button></form></section>@endcan
</div>
@endsection
