@extends('layouts.admin')
@section('title', 'Payables')
@section('page-title', 'Payables')
@section('breadcrumbs')<span>/</span><span>Finance</span><span>/</span><span>Payables</span>@endsection
@section('content')
@include('command-center.finance.partials.nav')
<div class="space-y-6"><header class="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p class="text-sm font-semibold text-indigo-700 dark:text-indigo-300">Money you owe suppliers</p><h1 class="mt-1 text-2xl font-semibold text-slate-950 dark:text-white">₹{{ number_format($metrics['payable']/100,2) }} payable</h1><p class="mt-2 text-sm text-slate-500">Approved purchase invoices after recorded supplier-payment allocations.</p></div>@can('finance.exports')<a href="{{ route('finance.payables.csv', request()->query()) }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-center text-sm font-semibold dark:border-slate-700">Export CSV</a>@endcan</header>
<section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Total payable',$metrics['payable']],['Due today',$metrics['due_today']],['Overdue',$metrics['overdue']],['Upcoming',$metrics['upcoming']]] as [$label,$value])<article class="rounded-lg border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p class="text-xs font-semibold uppercase text-slate-500">{{ $label }}</p><p class="mt-2 text-xl font-semibold text-slate-950 dark:text-white">₹{{ number_format($value/100,2) }}</p></article>@endforeach</section>
<section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">@foreach(['current'=>'Not due','1_30'=>'1–30 days','31_60'=>'31–60 days','61_90'=>'61–90 days','90_plus'=>'90+ days'] as $key=>$label)<a href="{{ route('finance.payables.index',['bucket'=>$key]) }}" class="rounded-lg border border-slate-200 bg-white p-4 hover:border-indigo-400 dark:border-slate-800 dark:bg-slate-900"><p class="text-sm text-slate-500">{{ $label }}</p><p class="mt-1 text-lg font-semibold">₹{{ number_format($aging[$key]/100,2) }}</p></a>@endforeach</section>
<form class="flex flex-col gap-3 rounded-lg border border-slate-200 bg-white p-4 sm:flex-row dark:border-slate-800 dark:bg-slate-900"><input name="search" value="{{ request('search') }}" placeholder="Supplier or bill reference" class="min-w-0 flex-1 rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-950"><select name="bucket" class="rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-950"><option value="">All aging</option>@foreach(['current'=>'Not due','1_30'=>'1–30','31_60'=>'31–60','61_90'=>'61–90','90_plus'=>'90+'] as $key=>$label)<option value="{{ $key }}" @selected(request('bucket')===$key)>{{ $label }}</option>@endforeach</select><button class="rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white dark:bg-indigo-300 dark:text-slate-950">Filter</button></form>
<section class="rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($invoices as $invoice)<article class="grid gap-3 p-4 md:grid-cols-[1.2fr_1fr_1fr_auto] md:items-center"><div><a href="{{ route('purchases.invoices.show',$invoice) }}" class="font-semibold text-indigo-700 dark:text-indigo-300">{{ $invoice->invoice_number }}</a><p class="mt-1 text-sm text-slate-500">{{ $invoice->supplier->name }}</p></div><p class="text-sm text-slate-500">Due {{ $invoice->due_date?->format('d M Y') ?? 'not set' }}</p><p class="font-semibold">{{ $invoice->currency }} {{ number_format((float)$invoice->outstanding_total,2) }}</p><a href="{{ route('finance.supplier-statements.show',$invoice->supplier_id) }}" class="rounded-lg border border-slate-300 px-3 py-2 text-center text-sm font-semibold dark:border-slate-700">Statement</a></article>@empty<div class="p-10 text-center text-sm text-slate-500">No supplier bills match these authorized filters.</div>@endforelse</div>@if($invoices->hasPages())<div class="border-t p-4 dark:border-slate-800">{{ $invoices->links() }}</div>@endif</section></div>
@endsection
