@extends('layouts.admin')
@section('title', 'Record Customer Payment')
@section('page-title', 'Record Customer Payment')
@section('breadcrumbs')<span>/</span><span>Finance</span><span>/</span><span>Record Payment</span>@endsection
@section('content')
@include('command-center.finance.partials.nav')
<div class="mx-auto max-w-5xl space-y-6"><header><h1 class="text-2xl font-semibold text-slate-950 dark:text-white">Allocate a customer payment</h1><p class="mt-2 text-sm text-slate-500">Choose exactly how the payment is applied. Any remainder stays safely on account for later reconciliation.</p></header>
@if(!$customer)<form method="GET" class="rounded-lg border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><label class="text-sm font-medium">Customer ID<input name="customer_id" type="number" min="1" required class="mt-1 block w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950" placeholder="Enter a customer ID from Receivables"></label><button class="mt-4 rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white dark:bg-teal-300 dark:text-slate-950">Load outstanding invoices</button></form>
@else
<form method="POST" action="{{ $payment ? route('finance.customer-payments.allocations.store',$payment) : route('finance.customer-payments.store') }}" class="space-y-6">@csrf<input type="hidden" name="customer_id" value="{{ $customer->id }}"><input type="hidden" name="currency" value="{{ $payment?->currency ?: 'INR' }}"><input type="hidden" name="idempotency_key" value="{{ (string) \Illuminate\Support\Str::uuid() }}">
<section class="rounded-lg border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div class="flex items-start justify-between gap-4"><div><p class="text-sm text-slate-500">{{ $payment ? 'Allocating payment' : 'Receiving from' }}</p><h2 class="mt-1 text-lg font-semibold text-slate-950 dark:text-white">{{ $customer->company_name ?: $customer->display_name }}</h2><p class="mt-1 text-sm text-slate-500">{{ $customer->phone }} · {{ $customer->email }}</p></div><a href="{{ route('finance.customer-statements.show',$customer) }}" class="text-sm font-semibold text-teal-700 dark:text-teal-300">Statement</a></div>@if($payment)<div class="mt-5 grid gap-3 sm:grid-cols-3"><div><p class="text-xs text-slate-500">Reference</p><p class="font-semibold">{{ $payment->payment_reference }}</p></div><div><p class="text-xs text-slate-500">Received</p><p class="font-semibold">{{ $payment->currency }} {{ number_format((float)$payment->amount,2) }}</p></div><div><p class="text-xs text-slate-500">Available to allocate</p><p class="font-semibold text-teal-700 dark:text-teal-300">{{ $payment->currency }} {{ number_format((float)$payment->unallocated_amount,2) }}</p></div></div>@else<div class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label class="text-sm font-medium">Payment amount<input name="amount" type="number" step="0.01" min="0.01" required value="{{ old('amount') }}" class="mt-1 block w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Payment date<input name="payment_date" type="date" required value="{{ old('payment_date',today()->toDateString()) }}" class="mt-1 block w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Method<select name="payment_method" required class="mt-1 block w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950">@foreach(['bank_transfer'=>'Bank transfer','upi'=>'UPI','cash'=>'Cash','card'=>'Card','cheque'=>'Cheque','other'=>'Other'] as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label><label class="text-sm font-medium">Reference<input name="transaction_reference" value="{{ old('transaction_reference') }}" class="mt-1 block w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label></div>@endif</section>
<section class="rounded-lg border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><div class="border-b border-slate-200 p-5 dark:border-slate-800"><h2 class="font-semibold text-slate-950 dark:text-white">Outstanding invoices</h2><p class="mt-1 text-sm text-slate-500">Enter an amount beside each invoice. Leave it at zero to keep funds unapplied.</p></div><div class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($invoices as $invoice)<div class="grid gap-3 p-4 sm:grid-cols-[1fr_160px] sm:items-center"><div><p class="font-semibold">{{ $invoice->invoice_number }}</p><p class="mt-1 text-sm text-slate-500">Due {{ $invoice->due_date?->format('d M Y') ?? 'not set' }} · Remaining {{ $invoice->currency }} {{ number_format((float)$invoice->balance_due,2) }}</p></div><input type="hidden" name="allocations[{{ $loop->index }}][invoice_id]" value="{{ $invoice->id }}"><label class="text-sm font-medium">Apply amount<input name="allocations[{{ $loop->index }}][amount]" type="number" min="0" max="{{ $invoice->balance_due }}" step="0.01" value="0.00" class="mt-1 block w-full rounded-lg border-slate-300 text-right dark:border-slate-700 dark:bg-slate-950"></label></div>@empty<div class="p-8 text-center text-sm text-slate-500">This customer has no outstanding invoices. The full payment can remain on account.</div>@endforelse</div></section>
@unless($payment)<label class="block text-sm font-medium">Internal note<textarea name="notes" rows="3" class="mt-1 block w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950">{{ old('notes') }}</textarea></label>@endunless<div class="flex justify-end"><button class="rounded-lg bg-teal-700 px-5 py-3 text-sm font-semibold text-white transition hover:bg-teal-800 active:scale-[.98]">{{ $payment ? 'Save allocation' : 'Review and record payment' }}</button></div></form>
@endif</div>
@endsection
