@extends('layouts.admin')
@section('title', 'Receivables')
@section('page-title', 'Receivables')
@section('breadcrumbs')<span>/</span><span>Finance</span><span>/</span><span>Receivables</span>@endsection
@section('content')
@include('command-center.finance.partials.nav')
<div class="space-y-6">
    <header class="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p class="text-sm font-semibold text-teal-700 dark:text-teal-300">Money customers owe you</p><h1 class="mt-1 text-2xl font-semibold text-slate-950 dark:text-white">₹{{ number_format($metrics['outstanding'] / 100, 2) }} outstanding</h1><p class="mt-2 text-sm text-slate-500 dark:text-slate-400">Balances use issued invoices after payments and finalized credit allocations.</p></div><div class="flex flex-wrap gap-2">@can('finance.exports')<a href="{{ route('finance.receivables.csv', request()->query()) }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-center text-sm font-semibold dark:border-slate-700">Export CSV</a>@endcan @can('finance.payments.allocate')<a href="{{ route('finance.customer-payments.create') }}" class="rounded-lg bg-slate-950 px-4 py-2.5 text-center text-sm font-semibold text-white dark:bg-teal-300 dark:text-slate-950">Record payment</a>@endcan</div></header>
    <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
        @foreach ([['Outstanding',$metrics['outstanding'],'teal'],['Due today',$metrics['due_today'],'sky'],['Overdue',$metrics['overdue'],'rose'],['Customer credits',$metrics['customer_credits'],'amber']] as [$label,$value,$tone])<article class="rounded-lg border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p class="text-xs font-semibold uppercase text-slate-500 dark:text-slate-400">{{ $label }}</p><p class="mt-2 text-xl font-semibold text-slate-950 dark:text-white">₹{{ number_format($value / 100, 2) }}</p></article>@endforeach
        <article class="rounded-lg border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p class="text-xs font-semibold uppercase text-slate-500">Average collection</p><p class="mt-2 text-xl font-semibold text-slate-950 dark:text-white">{{ $metrics['average_collection_age'] === null ? 'Not enough data' : $metrics['average_collection_age'].' days' }}</p></article>
    </section>
    <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">@foreach (['current'=>'Not due','1_30'=>'1–30 days','31_60'=>'31–60 days','61_90'=>'61–90 days','90_plus'=>'90+ days'] as $key=>$label)<a href="{{ route('finance.receivables.index', array_merge(request()->except('page'), ['bucket'=>$key])) }}" class="rounded-lg border border-slate-200 bg-white p-4 transition hover:border-teal-400 dark:border-slate-800 dark:bg-slate-900"><p class="text-sm text-slate-500">{{ $label }}</p><p class="mt-1 text-lg font-semibold text-slate-950 dark:text-white">₹{{ number_format($aging[$key] / 100, 2) }}</p></a>@endforeach</section>
    <form class="grid gap-3 rounded-lg border border-slate-200 bg-white p-4 sm:grid-cols-2 xl:grid-cols-[minmax(220px,1fr)_180px_150px_150px_auto] dark:border-slate-800 dark:bg-slate-900"><input name="search" value="{{ request('search') }}" placeholder="Customer, mobile or invoice" class="min-w-0 rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-950"><select name="bucket" class="min-w-0 rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-950"><option value="">All aging</option>@foreach(['current'=>'Not due','1_30'=>'1–30','31_60'=>'31–60','61_90'=>'61–90','90_plus'=>'90+'] as $key=>$label)<option value="{{ $key }}" @selected(request('bucket')===$key)>{{ $label }}</option>@endforeach</select><input type="date" name="from" value="{{ request('from') }}" class="min-w-0 rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-950"><input type="date" name="to" value="{{ request('to') }}" class="min-w-0 rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-950"><button class="rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white dark:bg-teal-300 dark:text-slate-950">Filter</button></form>
    <section class="rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="border-b border-slate-200 p-5 dark:border-slate-800"><h2 class="font-semibold text-slate-950 dark:text-white">Outstanding invoices</h2></div><div class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($invoices as $invoice)<article class="grid gap-3 p-4 md:grid-cols-[1.3fr_1fr_1fr_auto] md:items-center"><div><a href="{{ route('sales.invoices.show',$invoice) }}" class="font-semibold text-teal-700 dark:text-teal-300">{{ $invoice->invoice_number }}</a><p class="mt-1 text-sm text-slate-500">{{ $invoice->billing_company ?: $invoice->billing_name }}</p></div><div class="text-sm"><p class="text-slate-500">Due {{ $invoice->due_date?->format('d M Y') ?? 'not set' }}</p><p class="mt-1 font-medium">{{ $invoice->due_date?->isPast() ? $invoice->due_date->diffInDays(today()).' days overdue' : 'Not overdue' }}</p></div><div><p class="text-sm text-slate-500">Remaining</p><p class="font-semibold">{{ $invoice->currency }} {{ number_format((float)$invoice->balance_due,2) }}</p></div><div class="flex gap-2">@if($invoice->customer_id)<a href="{{ route('finance.customer-statements.show',$invoice->customer_id) }}" class="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold dark:border-slate-700">Statement</a>@can('finance.payments.allocate')<a href="{{ route('finance.customer-payments.create',['customer_id'=>$invoice->customer_id]) }}" class="rounded-lg bg-teal-700 px-3 py-2 text-sm font-semibold text-white">Pay</a>@endcan
        @endif</div></article>@empty<div class="p-10 text-center"><p class="font-semibold text-slate-950 dark:text-white">Nothing outstanding</p><p class="mt-1 text-sm text-slate-500">No invoices match these authorized filters.</p></div>@endforelse</div>@if($invoices->hasPages())<div class="border-t border-slate-200 p-4 dark:border-slate-800">{{ $invoices->links() }}</div>@endif</section>
</div>
@endsection
