@extends('layouts.admin')
@section('title', 'Reconciliation')
@section('page-title', 'Reconciliation')
@section('breadcrumbs')<span>/</span><span>Finance</span><span>/</span><span>Reconciliation</span>@endsection
@section('content')
@include('command-center.finance.partials.nav')
<div class="space-y-6"><header><h1 class="text-2xl font-semibold text-slate-950 dark:text-white">Payments needing attention</h1><p class="mt-2 text-sm text-slate-500">Review recorded payments that still have an amount waiting to be allocated. This does not connect to a bank feed.</p></header>
@foreach([['Customer payments',$customerPayments,'customer'],['Supplier payments',$supplierPayments,'supplier']] as [$heading,$payments,$type])<section class="rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="border-b border-slate-200 p-5 dark:border-slate-800"><h2 class="font-semibold text-slate-950 dark:text-white">{{ $heading }}</h2></div><div class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($payments as $payment)<article class="grid gap-3 p-4 md:grid-cols-[1.2fr_1fr_1fr_auto] md:items-center"><div><p class="font-semibold">{{ $type === 'customer' ? ($payment->customer?->company_name ?: $payment->customer?->display_name ?: 'Customer not linked') : ($payment->supplier?->name ?: 'Supplier not linked') }}</p><p class="mt-1 text-xs text-slate-500">{{ $type === 'customer' ? $payment->payment_reference : $payment->payment_number }}</p></div><p class="text-sm text-slate-500">{{ $payment->payment_date?->format('d M Y') }}</p><div><p class="text-xs text-slate-500">Unallocated</p><p class="font-semibold">{{ $payment->currency }} {{ number_format((float)$payment->unallocated_amount,2) }}</p></div><div class="flex flex-wrap gap-2">@if($type === 'customer' && $payment->customer_id)<a href="{{ route('finance.customer-payments.create',['payment_id'=>$payment->id]) }}" class="rounded-lg bg-teal-700 px-3 py-2 text-sm font-semibold text-white">Allocate</a>@endif<form method="POST" action="{{ route('finance.reconciliation.store') }}" class="flex min-w-0 gap-2">@csrf<input type="hidden" name="payment_type" value="{{ $type }}"><input type="hidden" name="payment_id" value="{{ $payment->id }}"><input name="note" aria-label="Review note" placeholder="Review note" class="min-w-0 rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-950"><button class="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold dark:border-slate-700">Mark reviewed</button></form></div></article>@empty<div class="p-8 text-center text-sm text-slate-500">No unallocated {{ strtolower($heading) }}.</div>@endforelse</div>@if($payments->hasPages())<div class="border-t border-slate-200 p-4 dark:border-slate-800">{{ $payments->links() }}</div>@endif</section>@endforeach</div>
@endsection
