@extends('layouts.admin')
@section('title', 'Supplier Statement')
@section('page-title', 'Supplier Statement')
@section('breadcrumbs')<span>/</span><span>Finance</span><span>/</span><span>Supplier Statement</span>@endsection
@section('content')
@include('command-center.finance.partials.nav')
<div class="space-y-6"><header class="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p class="text-sm text-slate-500">{{ $supplier->name }}</p><h1 class="mt-1 text-2xl font-semibold text-slate-950 dark:text-white">Supplier statement</h1><p class="mt-1 text-sm text-slate-500">{{ $from->format('d M Y') }} to {{ $to->format('d M Y') }}</p></div><div class="flex gap-2">@can('finance.exports')<a href="{{ route('finance.supplier-statements.csv',[$supplier,'from'=>$from->toDateString(),'to'=>$to->toDateString()]) }}" class="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold dark:border-slate-700">CSV</a>@endcan<a href="{{ route('finance.supplier-statements.pdf',[$supplier,'from'=>$from->toDateString(),'to'=>$to->toDateString()]) }}" class="rounded-lg bg-slate-950 px-3 py-2 text-sm font-semibold text-white dark:bg-indigo-300 dark:text-slate-950">Download PDF</a></div></header>
<section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Total purchases',$summary['total_purchases']],['Total paid',$summary['total_paid']],['Outstanding',$summary['outstanding']],['Supplier advance',$summary['supplier_credit']]] as [$label,$value])<article class="rounded-lg border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><p class="text-xs font-semibold uppercase text-slate-500">{{ $label }}</p><p class="mt-2 text-xl font-semibold">₹{{ number_format($value/100,2) }}</p></article>@endforeach</section>
<form class="flex flex-col gap-3 rounded-lg border border-slate-200 bg-white p-4 sm:flex-row sm:items-end dark:border-slate-800 dark:bg-slate-900"><label class="text-sm font-medium">From<input type="date" name="from" value="{{ $from->toDateString() }}" class="mt-1 block rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">To<input type="date" name="to" value="{{ $to->toDateString() }}" class="mt-1 block rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><button class="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white dark:bg-indigo-300 dark:text-slate-950">Update period</button></form>
@include('command-center.finance.partials.statement-ledger')
<p class="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-100">Purchase-return credits are not inferred here because the current return ledger does not authoritatively link each return to a purchase invoice. Approved supplier payments and purchase invoices remain fully represented.</p></div>
@endsection
