@extends('layouts.admin')

@section('title', 'Amend '.$record->invoice_number)
@section('page-title', 'Amend Invoice')

@section('content')
    <div class="mx-auto max-w-6xl space-y-6" data-amendment-editor data-currency="{{ $record->currency }}" data-current-total="{{ $record->grand_total }}" data-product-url="{{ route('sales.invoices.amendments.products.search') }}">
        @include('command-center.crm.partials.nav')

        <section class="rounded-lg border border-violet-200 bg-violet-50 p-5 dark:border-violet-900 dark:bg-violet-950/25">
            <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p class="text-xs font-semibold uppercase text-violet-700 dark:text-violet-300">Issued invoice · Version {{ $record->amendment_version }}</p><h1 class="mt-1 text-2xl font-semibold text-slate-950 dark:text-white">Add products or services</h1><p class="mt-2 max-w-2xl text-sm text-slate-600 dark:text-slate-300">Original issued lines stay unchanged. Use a return or credit note when an original line needs correction.</p></div><a href="{{ route('sales.invoices.show', $record) }}" class="text-sm font-semibold text-slate-700 dark:text-slate-200">Back to invoice</a></div>
        </section>

        @if($errors->any())<section class="rounded-lg border border-rose-200 bg-rose-50 p-4 text-sm text-rose-900 dark:border-rose-900 dark:bg-rose-950/30 dark:text-rose-100"><p class="font-semibold">Please review the amendment.</p><ul class="mt-2 list-disc space-y-1 pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></section>@endif

        <form method="POST" action="{{ route('sales.invoices.amendments.store', $record) }}" class="space-y-6">@csrf
            <input type="hidden" name="expected_version" value="{{ $record->amendment_version }}">
            <input type="hidden" name="idempotency_key" value="{{ (string) Str::uuid() }}">

            <section class="rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">
                <div class="flex flex-col gap-3 border-b border-slate-200 p-5 dark:border-slate-800 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-semibold text-slate-950 dark:text-white">New lines</h2><p class="mt-1 text-sm text-slate-500">Choose a catalog product or add a free-text service.</p></div><div class="flex flex-wrap gap-2"><button type="button" data-add-service class="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:text-slate-200 dark:hover:bg-slate-800">+ Add Service</button><button type="button" data-add-product class="rounded-lg bg-teal-600 px-3 py-2 text-sm font-semibold text-white hover:bg-teal-500 dark:bg-teal-400 dark:text-slate-950">+ Add Product</button></div></div>
                <div data-lines class="space-y-4 p-5"></div>
            </section>

            <section class="grid gap-6 lg:grid-cols-[minmax(0,1fr)_340px]">
                <div class="space-y-6">
                    <article class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><label class="block text-sm font-semibold text-slate-800 dark:text-slate-200">Reason for amendment<textarea name="reason" rows="3" required minlength="5" maxlength="2000" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-slate-950 focus:border-teal-500 focus:ring-teal-500 dark:border-slate-700 dark:bg-slate-950 dark:text-white" placeholder="Example: Additional installation requested">{{ old('reason') }}</textarea></label><p class="mt-2 text-xs text-slate-500">This reason becomes part of the permanent internal amendment history.</p></article>
                    <article class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><label class="block text-sm font-semibold text-slate-800 dark:text-slate-200">Product fulfilment warehouse<select name="warehouse_id" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-slate-950 dark:border-slate-700 dark:bg-slate-950 dark:text-white"><option value="">Not needed for service-only amendment</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}" @selected(old('warehouse_id') == $warehouse->id)>{{ $warehouse->name }}</option>@endforeach</select></label><p class="mt-2 text-xs text-slate-500">Required only when an added catalog product tracks inventory.</p></article>
                    @can('finance.credit-limits.override')<article class="rounded-lg border border-amber-200 bg-amber-50 p-5 dark:border-amber-900 dark:bg-amber-950/25"><label class="flex items-start gap-3 text-sm font-semibold text-amber-950 dark:text-amber-100"><input type="checkbox" name="credit_limit_override" value="1" class="mt-0.5" data-credit-override>Allow credit-limit override</label><label class="mt-3 hidden text-sm text-amber-900 dark:text-amber-100" data-credit-reason>Override reason<input name="credit_limit_override_reason" maxlength="1000" class="mt-2 w-full rounded-lg border border-amber-300 bg-white px-3 py-2 dark:border-amber-800 dark:bg-slate-950"></label></article>@endcan
                </div>

                <aside class="h-fit rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 lg:sticky lg:top-24"><h2 class="font-semibold text-slate-950 dark:text-white">Amendment preview</h2><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between gap-4"><dt class="text-slate-500">Current total</dt><dd class="font-medium">{{ $record->currency }} {{ number_format((float) $record->grand_total, 2) }}</dd></div><div class="flex justify-between gap-4"><dt class="text-slate-500">Added before tax</dt><dd data-added-subtotal>—</dd></div><div class="flex justify-between gap-4"><dt class="text-slate-500">Added tax</dt><dd data-added-tax>—</dd></div><div class="flex justify-between gap-4 border-t border-slate-200 pt-3 dark:border-slate-700"><dt class="font-semibold">Additional amount</dt><dd class="font-semibold text-violet-700 dark:text-violet-300" data-added-total>—</dd></div><div class="flex justify-between gap-4"><dt class="font-semibold">New invoice total</dt><dd class="font-semibold" data-new-total>—</dd></div></dl><button class="mt-5 w-full rounded-lg bg-slate-950 px-4 py-3 text-sm font-semibold text-white hover:bg-slate-800 dark:bg-teal-300 dark:text-slate-950 dark:hover:bg-teal-200">Confirm Amendment</button><p class="mt-3 text-center text-xs text-slate-500">Confirmation is permanent and fully audited.</p></aside>
            </section>
        </form>

        <template data-line-template>
            <article class="rounded-lg border border-slate-200 p-4 dark:border-slate-800" data-line>
                <div class="flex items-center justify-between gap-3"><div><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700 dark:bg-slate-800 dark:text-slate-200" data-line-kind>Service</span></div><button type="button" data-remove-line class="rounded-lg p-2 text-slate-500 hover:bg-rose-50 hover:text-rose-700 dark:hover:bg-rose-950/30" aria-label="Remove added line"><x-icon name="trash-2" class="size-4" /></button></div>
                <div class="mt-4 hidden" data-product-search><label class="block text-sm font-medium text-slate-700 dark:text-slate-300">Find product<input type="search" autocomplete="off" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 dark:border-slate-700 dark:bg-slate-950" placeholder="Search by product name, SKU or barcode" data-product-query></label><div class="relative"><div class="absolute z-20 mt-1 hidden max-h-56 w-full overflow-y-auto rounded-lg border border-slate-200 bg-white shadow-xl dark:border-slate-700 dark:bg-slate-900" data-product-results></div></div></div>
                <input type="hidden" data-field="product_id">
                <div class="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label class="block text-sm font-medium text-slate-700 dark:text-slate-300 md:col-span-2">Description<input required maxlength="255" data-field="name" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 dark:border-slate-700 dark:bg-slate-950"></label><label class="block text-sm font-medium text-slate-700 dark:text-slate-300">Quantity<input required type="number" min="0.001" step="0.001" value="1" data-field="quantity" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 dark:border-slate-700 dark:bg-slate-950"></label><label class="block text-sm font-medium text-slate-700 dark:text-slate-300">Unit price<input required type="number" min="0" step="0.01" value="0" data-field="unit_price" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 dark:border-slate-700 dark:bg-slate-950"></label><label class="block text-sm font-medium text-slate-700 dark:text-slate-300">Unit<input maxlength="32" value="unit" data-field="unit" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 dark:border-slate-700 dark:bg-slate-950"></label><label class="block text-sm font-medium text-slate-700 dark:text-slate-300">Discount<input type="number" min="0" step="0.01" value="0" data-field="discount_value" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 dark:border-slate-700 dark:bg-slate-950"></label><label class="block text-sm font-medium text-slate-700 dark:text-slate-300">GST / tax %<input type="number" min="0" max="100" step="0.001" value="0" data-field="tax_rate" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 dark:border-slate-700 dark:bg-slate-950"></label><label class="block text-sm font-medium text-slate-700 dark:text-slate-300">HSN / SAC<input maxlength="16" data-field="hsn_sac" class="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 dark:border-slate-700 dark:bg-slate-950"></label></div>
            </article>
        </template>
    </div>

    @push('scripts')
        <script>
            (() => {
                const root = document.querySelector('[data-amendment-editor]'); if (!root) return;
                const lines = root.querySelector('[data-lines]'), template = root.querySelector('[data-line-template]');
                const money = value => `${root.dataset.currency} ${Number(value || 0).toFixed(2)}`;
                const reindex = () => lines.querySelectorAll('[data-line]').forEach((line, index) => line.querySelectorAll('[data-field]').forEach(input => input.name = `items[${index}][${input.dataset.field}]`));
                const totals = () => { let subtotal = 0, tax = 0; lines.querySelectorAll('[data-line]').forEach(line => { const q=Number(line.querySelector('[data-field="quantity"]').value||0), p=Number(line.querySelector('[data-field="unit_price"]').value||0), d=Number(line.querySelector('[data-field="discount_value"]').value||0), r=Number(line.querySelector('[data-field="tax_rate"]').value||0); const taxable=Math.max(0,q*p-d); subtotal+=taxable; tax+=taxable*r/100; }); root.querySelector('[data-added-subtotal]').textContent=money(subtotal); root.querySelector('[data-added-tax]').textContent=money(tax); root.querySelector('[data-added-total]').textContent=money(subtotal+tax); root.querySelector('[data-new-total]').textContent=money(Number(root.dataset.currentTotal)+subtotal+tax); };
                const add = kind => { const line=template.content.firstElementChild.cloneNode(true); line.querySelector('[data-line-kind]').textContent=kind==='product'?'Product':'Service'; if(kind==='product') line.querySelector('[data-product-search]').classList.remove('hidden'); line.querySelector('[data-remove-line]').addEventListener('click',()=>{line.remove(); if(!lines.children.length)add('service'); reindex(); totals();}); line.querySelectorAll('input').forEach(input=>input.addEventListener('input',totals)); const query=line.querySelector('[data-product-query]'); if(query){let timer; query.addEventListener('input',()=>{clearTimeout(timer); timer=setTimeout(async()=>{const box=line.querySelector('[data-product-results]'); if(query.value.trim().length<2){box.classList.add('hidden');return;} const response=await fetch(`${root.dataset.productUrl}?q=${encodeURIComponent(query.value.trim())}`,{headers:{Accept:'application/json'}}); if(!response.ok)return; const data=await response.json(); box.innerHTML=''; data.products.forEach(product=>{const button=document.createElement('button'); button.type='button'; button.className='block w-full px-3 py-2 text-left text-sm hover:bg-slate-50 dark:hover:bg-slate-800'; button.textContent=`${product.name}${product.sku?' · '+product.sku:''}`; button.addEventListener('click',()=>{line.querySelector('[data-field="product_id"]').value=product.id; line.querySelector('[data-field="name"]').value=product.name; line.querySelector('[data-field="unit_price"]').value=product.selling_price; query.value=product.name; box.classList.add('hidden'); totals();}); box.appendChild(button);}); box.classList.toggle('hidden',!data.products.length);},250);});} lines.appendChild(line); reindex(); totals(); };
                root.querySelector('[data-add-service]').addEventListener('click',()=>add('service')); root.querySelector('[data-add-product]').addEventListener('click',()=>add('product')); const override=root.querySelector('[data-credit-override]'); if(override)override.addEventListener('change',()=>root.querySelector('[data-credit-reason]').classList.toggle('hidden',!override.checked)); add('service');
            })();
        </script>
    @endpush
@endsection
