@extends('layouts.admin')

@section('title', 'Document Numbering')
@section('page-title', 'Document Numbering')
@section('breadcrumbs')<span>/</span><a href="{{ route('sales.invoices.index') }}">Sales</a><span>/</span><span>Document Numbering</span>@endsection

@section('content')
    <form method="POST" action="{{ route('sales.invoices.document-settings.update') }}" class="mx-auto max-w-3xl space-y-6">@csrf @method('PUT')
        <section class="rounded-lg border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p class="text-sm font-semibold text-teal-700">Sales settings</p><h1 class="mt-1 text-2xl font-semibold text-slate-950 dark:text-white">Document numbering</h1><p class="mt-2 text-sm leading-6 text-slate-500">Choose the identifier used on new sales documents. The sequence continues across prefix changes, and historical documents are never renamed.</p><div class="mt-6 grid gap-5 sm:grid-cols-3"><label class="text-sm font-medium text-slate-700 dark:text-slate-200">Sales invoice prefix<input name="invoice_prefix" value="{{ old('invoice_prefix', $setting->invoice_prefix) }}" maxlength="24" required class="mt-2 block w-full rounded-lg border-slate-300 uppercase dark:border-slate-700 dark:bg-slate-950"><span class="mt-1 block text-xs font-normal text-slate-500">Letters, numbers, and hyphens only.</span>@error('invoice_prefix')<span class="mt-1 block text-rose-600">{{ $message }}</span>@enderror</label><label class="text-sm font-medium text-slate-700 dark:text-slate-200">Quotation prefix<input name="quotation_prefix" value="{{ old('quotation_prefix', $setting->quotation_prefix) }}" maxlength="24" required class="mt-2 block w-full rounded-lg border-slate-300 uppercase dark:border-slate-700 dark:bg-slate-950"><span class="mt-1 block text-xs font-normal text-slate-500">Letters, numbers, and hyphens only.</span>@error('quotation_prefix')<span class="mt-1 block text-rose-600">{{ $message }}</span>@enderror</label><label class="text-sm font-medium text-slate-700 dark:text-slate-200">Proforma invoice prefix<input name="proforma_prefix" value="{{ old('proforma_prefix', $setting->proforma_prefix) }}" maxlength="24" required class="mt-2 block w-full rounded-lg border-slate-300 uppercase dark:border-slate-700 dark:bg-slate-950"><span class="mt-1 block text-xs font-normal text-slate-500">Letters, numbers, and hyphens only.</span>@error('proforma_prefix')<span class="mt-1 block text-rose-600">{{ $message }}</span>@enderror</label></div></section>
        <section class="grid gap-4 sm:grid-cols-3"><article class="rounded-lg border border-slate-200 bg-slate-50 p-5 dark:border-slate-800 dark:bg-slate-950"><p class="text-xs font-semibold uppercase text-slate-500">Next invoice</p><p class="mt-2 break-all font-mono text-lg font-semibold text-slate-950 dark:text-white" data-preview="invoice">{{ $previews['invoice'] }}</p></article><article class="rounded-lg border border-slate-200 bg-slate-50 p-5 dark:border-slate-800 dark:bg-slate-950"><p class="text-xs font-semibold uppercase text-slate-500">Next quotation</p><p class="mt-2 break-all font-mono text-lg font-semibold text-slate-950 dark:text-white" data-preview="quotation">{{ $previews['quotation'] }}</p></article><article class="rounded-lg border border-slate-200 bg-slate-50 p-5 dark:border-slate-800 dark:bg-slate-950"><p class="text-xs font-semibold uppercase text-slate-500">Next proforma</p><p class="mt-2 break-all font-mono text-lg font-semibold text-slate-950 dark:text-white" data-preview="proforma">{{ $previews['proforma'] }}</p></article></section>
        <div class="flex justify-end"><button class="rounded-lg bg-slate-950 px-5 py-3 text-sm font-semibold text-white dark:bg-teal-300 dark:text-slate-950">Save document numbering</button></div>
    </form>
    <script>document.querySelectorAll('input[name$="_prefix"]').forEach((input)=>input.addEventListener('input',()=>{input.value=input.value.toUpperCase().replace(/[^A-Z0-9-]/g,'');const documentType=input.name==='invoice_prefix'?'invoice':(input.name==='quotation_prefix'?'quotation':'proforma');const type=documentType==='invoice'?'INV':(documentType==='quotation'?'QUO':'PI');const prefix=input.value||'PREFIX';document.querySelector(`[data-preview="${documentType}"]`).textContent=(documentType==='quotation'&&prefix==='RPQ')||(documentType==='proforma'&&prefix==='RPI')?`${prefix}-{{ now()->format('Y') }}-000001`:`${prefix}-${type}-{{ now()->format('Y') }}-00001`;}));</script>
@endsection
