@extends('layouts.admin')
@section('title','Sales Invoices')
@section('page-title','Sales Invoices')
@section('content')
<div class="space-y-6">@include('command-center.crm.partials.nav')
<section class="rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex flex-col gap-4 border-b border-slate-200 p-5 sm:flex-row sm:items-center sm:justify-between dark:border-slate-800"><div><h1 class="text-xl font-semibold text-slate-950 dark:text-white">Invoices and collections</h1><p class="mt-1 text-sm text-slate-500">Track issued invoices, balances, and recorded payments by currency.</p></div><div class="flex flex-wrap gap-2">@can('sales.finance.export')<a href="{{ route('sales.invoices.export', request()->only(['search', 'status'])) }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-center text-sm font-semibold text-slate-700 dark:border-slate-700 dark:text-slate-200">Export CSV</a>@endcan<a href="{{ route('sales.invoices.create') }}" class="rounded-lg bg-slate-950 px-4 py-2.5 text-center text-sm font-semibold text-white dark:bg-teal-300 dark:text-slate-950">New invoice</a></div></div>
@if($summary->isNotEmpty())<div class="grid gap-px border-b border-slate-200 bg-slate-200 sm:grid-cols-2 xl:grid-cols-4 dark:border-slate-800 dark:bg-slate-800">@foreach($summary as $currency)<div class="bg-white p-4 text-sm dark:bg-slate-900"><p class="font-semibold text-slate-950 dark:text-white">{{ $currency['currency'] }} collection</p><dl class="mt-3 space-y-1 text-slate-500 dark:text-slate-400"><div class="flex justify-between gap-3"><dt>Invoiced</dt><dd>{{ number_format((float) $currency['total_invoiced'], 2) }}</dd></div><div class="flex justify-between gap-3"><dt>Collected</dt><dd class="text-teal-700 dark:text-teal-300">{{ number_format((float) $currency['total_collected'], 2) }}</dd></div><div class="flex justify-between gap-3"><dt>Outstanding</dt><dd>{{ number_format((float) $currency['outstanding'], 2) }}</dd></div><div class="flex justify-between gap-3"><dt>Overdue</dt><dd class="text-rose-700 dark:text-rose-300">{{ number_format((float) $currency['overdue'], 2) }}</dd></div></dl></div>@endforeach</div>@endif
<form class="flex flex-col gap-2 p-4 sm:flex-row"><input name="search" value="{{ request('search') }}" placeholder="Invoice, quotation, customer or email" class="flex-1 rounded-lg border border-slate-300 px-3 py-2 text-sm"><select name="status" class="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">All statuses</option>@foreach(\App\Enums\Crm\InvoiceStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status')===$status->value)>{{ $status->label() }}</option>@endforeach</select><button class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Filter</button></form><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500 dark:bg-slate-950"><tr><th class="p-4">Invoice</th><th class="p-4">Customer</th><th class="p-4">Status</th><th class="p-4 text-right">Total</th><th class="p-4 text-right">Balance</th><th class="p-4">Due</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($invoices as $invoice)<tr><td class="p-4"><a class="font-semibold text-teal-700" href="{{ route('sales.invoices.show',$invoice) }}">{{ $invoice->invoice_number }}</a><p class="mt-1 text-xs text-slate-500">{{ $invoice->quotation?->quotation_number }}</p></td><td class="p-4">{{ $invoice->billing_company ?: $invoice->billing_name }}</td><td class="p-4"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700">{{ $invoice->isOverdue() ? 'Overdue' : $invoice->status?->label() }}</span></td><td class="p-4 text-right">{{ $invoice->currency }} {{ number_format((float)$invoice->grand_total,2) }}</td><td class="p-4 text-right font-semibold">{{ $invoice->currency }} {{ number_format((float)$invoice->balance_due,2) }}</td><td class="p-4">{{ $invoice->due_date?->format('d M Y') ?? '—' }}</td></tr>@empty<tr><td colspan="6" class="p-10 text-center text-sm text-slate-500">No invoices yet.</td></tr>@endforelse</tbody></table></div>@if($invoices->hasPages())<div class="p-4">{{ $invoices->links() }}</div>@endif</section></div>
@endsection
