@extends('layouts.admin')
@section('title','Invoice Designs')
@section('page-title','Invoice Designs')
@section('breadcrumbs')<span>/</span><a href="{{ route('sales.invoices.index') }}">Invoices</a><span>/</span><span>Designs</span>@endsection
@section('content')
<form method="POST" action="{{ route('sales.invoices.templates.update') }}" class="mx-auto max-w-6xl space-y-6">@csrf @method('PUT')
<section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">@foreach($templates as $key => $template)<label class="cursor-pointer rounded-lg border p-4 transition hover:border-teal-500 @if($setting->template_key===$key) border-teal-600 ring-2 ring-teal-100 @else border-slate-200 @endif"><input class="sr-only" type="radio" name="template_key" value="{{ $key }}" @checked($setting->template_key===$key)><div class="h-24 border border-slate-300 p-3 text-xs" style="border-top:5px solid {{ $key === 'premium_elegant' ? '#b58b4a' : ($key === 'modern_split_panel' ? '#0f766e' : '#0f172a') }}"><b>{{ $template['name'] }}</b><div class="mt-3 border-t pt-2">Invoice &nbsp; Bill to &nbsp; Total</div></div><p class="mt-3 font-semibold">{{ $template['name'] }}</p><p class="mt-1 text-sm text-slate-500">{{ $template['businesses'] }}</p><p class="mt-2 text-xs font-medium text-slate-500">{{ str($template['density'])->headline() }} · {{ str($template['gst_detail'])->headline() }} GST</p></label>@endforeach</div></section>
<section class="grid gap-6 rounded-lg border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-2 dark:border-slate-800 dark:bg-slate-900"><label class="text-sm font-medium">Brand colour<input type="color" name="brand_color" value="{{ old('brand_color',$setting->brand_color) }}" class="mt-2 block h-10 w-full"></label><label class="text-sm font-medium">Copy label<select name="copy_label" class="mt-2 block w-full">@foreach(['original','duplicate','triplicate'] as $value)<option value="{{ $value }}" @selected($setting->copy_label===$value)>{{ str($value)->headline() }}</option>@endforeach</select></label><label class="text-sm font-medium">Payment QR URI (optional)<input name="payment_qr_uri" value="{{ old('payment_qr_uri',$setting->payment_qr_uri) }}" placeholder="upi://pay?..." class="mt-2 block w-full"><span class="mt-1 block text-xs text-slate-500">Shown only when a valid production payment URI is configured.</span></label><label class="text-sm font-medium">Print orientation<select name="orientation" class="mt-2 block w-full"><option value="portrait" @selected($setting->orientation==='portrait')>Portrait</option><option value="landscape" @selected($setting->orientation==='landscape')>Landscape</option></select></label><div class="md:col-span-2 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@foreach($defaults as $option => $default)<label class="flex items-center gap-2 text-sm"><input type="hidden" name="options[{{ $option }}]" value="0"><input type="checkbox" name="options[{{ $option }}]" value="1" @checked(old('options.'.$option, data_get($setting->options,$option,$default))) @disabled(in_array($option,['show_gst_breakup','show_gst_summary','show_hsn_sac']))>{{ str($option)->replace('_',' ')->headline() }}</label>@endforeach</div></section><button class="rounded-lg bg-slate-950 px-5 py-2.5 text-sm font-semibold text-white">Save invoice design</button></form>
@endsection
