@extends('layouts.admin')
@section('title','New Stock Count')
@section('page-title','New Stock Count')
@section('content')
@include('command-center.inventory.partials.nav')
<form method="POST" action="{{ route('inventory.counts.store') }}" class="mx-auto max-w-4xl space-y-5">@csrf
@if($errors->any())<div class="rounded-lg border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">{{ $errors->first() }}</div>@endif
<section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="text-lg font-semibold">What are you counting?</h2><p class="mt-1 text-sm text-slate-500">The system saves a stock snapshot now. Stock changes only after review, approval, and posting.</p><div class="mt-5 grid gap-4 md:grid-cols-2"><label class="text-sm font-semibold">Location<select name="warehouse_id" id="count-warehouse" required class="mt-1 min-h-11 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"><option value="">Choose location</option>@foreach($warehouses as $warehouse)<option value="{{$warehouse->id}}">{{$warehouse->name}}</option>@endforeach</select></label><label class="text-sm font-semibold">Bin <span class="font-normal text-slate-400">optional</span><select name="stock_location_id" id="count-location" class="mt-1 min-h-11 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"><option value="">Main stock area</option>@foreach($locations as $location)<option data-warehouse="{{$location->warehouse_id}}" value="{{$location->id}}">{{$location->code}} · {{$location->name}}</option>@endforeach</select></label><label class="text-sm font-semibold">Count type<select name="type" id="count-type" class="mt-1 min-h-11 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950">@foreach(['full'=>'Full location count','category'=>'Category count','selected'=>'Selected products','cycle'=>'Cycle count'] as $value=>$label)<option value="{{$value}}">{{$label}}</option>@endforeach</select></label><label class="text-sm font-semibold">Assign to <span class="font-normal text-slate-400">optional</span><select name="assigned_to" class="mt-1 min-h-11 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"><option value="">Unassigned</option>@foreach($users as $user)<option value="{{$user->id}}">{{$user->name}}</option>@endforeach</select></label><label id="category-field" class="hidden text-sm font-semibold">Category<select name="category_id" class="mt-1 min-h-11 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"><option value="">Choose category</option>@foreach($categories as $category)<option value="{{$category->id}}">{{$category->name}}</option>@endforeach</select></label><label class="text-sm font-semibold">Due date <span class="font-normal text-slate-400">optional</span><input type="date" name="due_date" class="mt-1 min-h-11 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label></div></section>
<section id="product-field" class="hidden rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h3 class="font-semibold">Products to count</h3><p class="mt-1 text-sm text-slate-500">Choose one or more products for a selected or cycle count.</p><select name="product_ids[]" multiple size="10" class="mt-4 w-full rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-950">@foreach($products as $product)<option value="{{$product->id}}">{{$product->name}} · {{$product->sku}}</option>@endforeach</select></section>
<section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><label class="text-sm font-semibold">Count note <span class="font-normal text-slate-400">optional</span><textarea name="notes" rows="3" class="mt-1 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></textarea></label><div class="mt-5 flex justify-end gap-3"><a href="{{route('inventory.counts.index')}}" class="inline-flex min-h-11 items-center px-3 text-sm font-semibold text-slate-500">Cancel</a><button class="min-h-11 rounded-lg bg-slate-950 px-5 text-sm font-semibold text-white dark:bg-teal-300 dark:text-slate-950">Create count</button></div></section></form>
<script>document.addEventListener('DOMContentLoaded',()=>{const type=document.getElementById('count-type');const update=()=>{document.getElementById('category-field').classList.toggle('hidden',type.value!=='category');document.getElementById('product-field').classList.toggle('hidden',!['selected','cycle'].includes(type.value));};type.addEventListener('change',update);update();document.getElementById('count-warehouse').addEventListener('change',event=>{const select=document.getElementById('count-location');[...select.options].forEach((option,index)=>{if(index)option.hidden=option.dataset.warehouse!==event.target.value;});select.value='';});});</script>
@endsection
