@extends('layouts.admin')
@section('title', 'Client Logos') @section('page-title', 'Client Logo Manager')
@section('breadcrumbs')<span>/</span><a href="{{ route('cms.dashboard') }}">CMS</a><span>/</span><span>Client Logos</span>@endsection
@section('content')
    <div class="space-y-6">@include('command-center.cms.partials.nav')
        <section class="cms-panel"><p class="cms-kicker">Content library</p><h1 class="mt-2 text-xl font-semibold text-slate-900">Client logo manager</h1><p class="mt-2 text-sm leading-6 text-slate-600">Use approved logos only. Homepage visibility and display treatment are independent of the original media file.</p></section>
        <div class="grid gap-6 xl:grid-cols-[0.72fr_1.28fr]">
            <form method="POST" action="{{ route('cms.client-logos.store') }}" class="cms-panel">@csrf<p class="cms-kicker">New logo</p><h2 class="mt-2 text-lg font-semibold text-slate-900">Add client logo</h2><div class="mt-5 space-y-4"><label class="cms-control-label">Client name<input name="name" required placeholder="Client name" class="mt-2 block w-full"></label><label class="cms-control-label">Logo media<select name="logo_media_id" class="mt-2 block w-full"><option value="">Logo media (optional)</option>@foreach ($media as $item)<option value="{{ $item->id }}">{{ $item->filename }}</option>@endforeach</select></label><div class="grid gap-4 sm:grid-cols-2"><input name="industry" placeholder="Industry"><input name="location" placeholder="Location"></div><input name="website_url" placeholder="Website URL"><textarea name="short_description" rows="4" placeholder="Demo-only description or approved client context"></textarea><label class="cms-control-label">Display style<select name="display_style" class="mt-2 block w-full"><option value="color">Color</option><option value="grayscale">Grayscale</option><option value="monochrome">Monochrome</option></select></label><div class="grid gap-3"><label class="cms-toggle"><input type="checkbox" name="show_on_homepage" value="1" checked> Show on homepage</label><label class="cms-toggle"><input type="checkbox" name="is_active" value="1" checked> Active</label></div><button class="cms-button-primary w-full">Add logo</button></div></form>
            <section class="cms-panel"><div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="cms-kicker">Logo library</p><h2 class="mt-2 text-lg font-semibold text-slate-900">Visual client list</h2></div><form class="flex gap-2"><input name="search" value="{{ request('search') }}" placeholder="Search client"><button class="cms-button-secondary">Filter</button></form></div><div class="mt-6 grid gap-4 sm:grid-cols-2 2xl:grid-cols-3">@forelse ($logos as $logo)@php($logoUrl = $logo->logoMedia ? \Illuminate\Support\Facades\Storage::disk($logo->logoMedia->disk ?: config('filesystems.default'))->url($logo->logoMedia->path) : null)<article class="cms-section-card"><div class="flex items-start justify-between gap-3"><div class="grid size-14 place-items-center overflow-hidden rounded-xl bg-slate-100 text-sm font-bold text-slate-400">@if($logoUrl)<img src="{{ $logoUrl }}" alt="{{ $logo->name }}" class="h-full w-full object-contain p-2">@else{{ str($logo->name)->substr(0, 2)->upper() }}@endif</div><x-status-badge :status="$logo->is_active ? 'active' : 'inactive'"/></div><p class="mt-4 font-semibold text-slate-900">{{ $logo->name }}</p><p class="mt-1 text-sm text-slate-500">{{ $logo->industry ?: 'Industry not set' }}{{ $logo->location ? ' · '.$logo->location : '' }}</p><div class="mt-4 flex flex-wrap gap-2"><span class="cms-chip">{{ str($logo->display_style)->headline() }}</span>@if($logo->is_featured)<span class="rounded-full bg-amber-100 px-2.5 py-1 text-xs font-semibold text-amber-700">Featured</span>@endif@if($logo->show_on_homepage)<span class="rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-semibold text-emerald-700">Homepage</span>@endif</div><div class="mt-5 flex items-center justify-between gap-3"><span class="text-xs text-slate-500">Position {{ $logo->sort_order }}</span><div class="flex items-center gap-3"><a href="#logo-{{ $logo->id }}" class="text-sm font-semibold text-teal-700 hover:text-teal-800">Quick edit</a><form method="POST" action="{{ route('cms.client-logos.destroy', $logo) }}">@csrf @method('DELETE')<button class="text-sm font-semibold text-rose-700">Trash</button></form></div></div><form id="logo-{{ $logo->id }}" method="POST" action="{{ route('cms.client-logos.update', $logo) }}" class="mt-4 border-t border-slate-100 pt-4">@csrf @method('PUT')<div class="flex gap-2"><input name="name" value="{{ $logo->name }}"><input type="hidden" name="display_style" value="{{ $logo->display_style }}"><input type="hidden" name="is_active" value="{{ $logo->is_active ? 1 : 0 }}"><button class="cms-button-secondary shrink-0">Save</button></div></form></article>@empty<div class="cms-subtle-panel col-span-full text-center text-sm text-slate-500">No client logos yet.</div>@endforelse</div><div class="mt-6">{{ $logos->links() }}</div></section>
        </div>
    </div>
@endsection
