@extends('layouts.admin')
@section('title', 'SaaS Billing')
@section('page-title', 'SaaS Billing')
@section('breadcrumbs')<span>/</span><span>Platform</span><span>/</span><span>Billing</span>@endsection
@section('content')
@include('command-center.saas.partials.nav')
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach(['Outstanding'=>$metrics['outstanding'],'Overdue invoices'=>$metrics['overdue'],'Paid this month'=>$metrics['paid_this_month'],'Refunds awaiting approval'=>$metrics['refunds_pending']] as $label=>$value)<section class="rounded-lg border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p class="text-xs font-medium uppercase text-slate-500">{{ $label }}</p><p class="mt-2 text-2xl font-semibold text-slate-950 dark:text-white">@if(is_numeric($value) && !str_contains(strtolower($label),'invoice') && !str_contains(strtolower($label),'refund')) INR {{ number_format((float)$value,2) }}@else{{ number_format($value) }}@endif</p></section>@endforeach</div>
<form class="mt-6 flex gap-3"><select name="status" class="rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-950"><option value="">All statuses</option>@foreach(['draft','issued','partially_paid','paid','overdue','void','refunded'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ str($status)->headline() }}</option>@endforeach</select><button class="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold dark:border-slate-700">Filter</button></form>
<section class="mt-4 overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm dark:divide-slate-800"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500 dark:bg-slate-800"><tr><th class="px-5 py-3">Invoice</th><th class="px-5 py-3">Tenant</th><th class="px-5 py-3">Period</th><th class="px-5 py-3">Total</th><th class="px-5 py-3">Status</th><th class="px-5 py-3"></th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($invoices as $invoice)<tr><td class="px-5 py-4 font-medium">{{ $invoice->invoice_number }}</td><td class="px-5 py-4">{{ $invoice->company?->name }}</td><td class="px-5 py-4 text-slate-500">{{ $invoice->billing_period_starts_at?->format('d M Y') }} - {{ $invoice->billing_period_ends_at?->format('d M Y') }}</td><td class="px-5 py-4">{{ $invoice->currency }} {{ number_format((float)$invoice->grand_total,2) }}</td><td class="px-5 py-4"><x-status-badge :status="$invoice->status" /></td><td class="px-5 py-4 text-right"><a href="{{ route('saas.billing.show',$invoice) }}" class="font-semibold text-teal-700 dark:text-teal-300">Open</a></td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center text-sm text-slate-500">No subscription invoices have been created yet.</td></tr>@endforelse</tbody></table></div></section><div class="mt-4">{{ $invoices->links() }}</div>
@endsection
