@extends('layouts.admin')

@section('title', 'Send Proforma Email')
@section('page-title', 'Send Proforma Email')

@section('breadcrumbs')
    <span>/</span><span>CRM</span><span>/</span><a href="{{ route('crm.proformas.show', $proforma) }}" class="hover:text-slate-950 dark:hover:text-white">{{ $proforma->proforma_number }}</a><span>/</span><span>Send Email</span>
@endsection

@section('content')
    <div class="space-y-6">
        @include('command-center.crm.partials.nav')
        <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p class="text-sm font-medium text-teal-700 dark:text-teal-300">Proforma delivery</p><h1 class="mt-2 text-2xl font-semibold text-slate-950 dark:text-white">Send proforma by email</h1><p class="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">The email includes a secure public proforma link. A PDF can be attached without exposing private CRM storage.</p></section>
        <form method="POST" action="{{ route('crm.proformas.email.send', $proforma) }}" class="space-y-6">@csrf
            <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="grid gap-5 md:grid-cols-2"><label class="block"><span class="text-sm font-medium text-slate-700 dark:text-slate-200">To <span class="text-rose-600">*</span></span><input type="email" name="to_email" required value="{{ old('to_email', $defaults['to_email']) }}" class="mt-2 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-950 shadow-sm outline-none focus:border-teal-600 focus:ring-2 focus:ring-teal-100 dark:border-slate-700 dark:bg-slate-950 dark:text-white">@error('to_email')<span class="mt-1 block text-xs text-rose-600">{{ $message }}</span>@enderror</label><label class="block"><span class="text-sm font-medium text-slate-700 dark:text-slate-200">CC</span><input name="cc" value="{{ old('cc') }}" placeholder="name@example.com, team@example.com" class="mt-2 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-950 shadow-sm outline-none focus:border-teal-600 focus:ring-2 focus:ring-teal-100 dark:border-slate-700 dark:bg-slate-950 dark:text-white">@error('cc')<span class="mt-1 block text-xs text-rose-600">{{ $message }}</span>@enderror</label></div><label class="mt-5 block"><span class="text-sm font-medium text-slate-700 dark:text-slate-200">Subject <span class="text-rose-600">*</span></span><input name="subject" required value="{{ old('subject', $defaults['subject']) }}" class="mt-2 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-950 shadow-sm outline-none focus:border-teal-600 focus:ring-2 focus:ring-teal-100 dark:border-slate-700 dark:bg-slate-950 dark:text-white">@error('subject')<span class="mt-1 block text-xs text-rose-600">{{ $message }}</span>@enderror</label><label class="mt-5 block"><span class="text-sm font-medium text-slate-700 dark:text-slate-200">Message <span class="text-rose-600">*</span></span><textarea name="message_body" rows="14" required class="mt-2 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-950 shadow-sm outline-none focus:border-teal-600 focus:ring-2 focus:ring-teal-100 dark:border-slate-700 dark:bg-slate-950 dark:text-white">{{ old('message_body', $defaults['message_body']) }}</textarea>@error('message_body')<span class="mt-1 block text-xs text-rose-600">{{ $message }}</span>@enderror</label><label class="mt-5 flex items-start gap-3 text-sm text-slate-700 dark:text-slate-200"><input type="checkbox" name="attach_pdf" value="1" @checked(old('attach_pdf', true)) class="mt-0.5 rounded border-slate-300 text-teal-700 focus:ring-teal-600"><span><strong>Attach proforma PDF</strong><span class="mt-1 block text-slate-500 dark:text-slate-400">If the PDF cannot be generated, the secure proforma link is still sent.</span></span></label></section>
            <div class="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><a href="{{ route('crm.proformas.show', $proforma) }}" class="inline-flex items-center justify-center rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:text-slate-200 dark:hover:bg-slate-800">Cancel</a><button class="inline-flex items-center justify-center rounded-lg bg-slate-950 px-5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-slate-800 dark:bg-teal-300 dark:text-slate-950">Send proforma email</button></div>
        </form>
    </div>
@endsection
