@extends('layouts.admin')

@section('title', 'Proforma Invoices')
@section('page-title', 'Proforma Invoices')

@section('content')
    <div class="space-y-6">
        @include('command-center.crm.partials.nav')
        <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h1 class="text-2xl font-semibold text-slate-950 dark:text-white">Proforma Invoices</h1><form class="mt-5 grid gap-3 md:grid-cols-[1fr_12rem_auto]"><input name="search" value="{{ request('search') }}" placeholder="Search number, customer, email, phone" class="rounded-lg border border-slate-300 px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-slate-950"><select name="status" class="rounded-lg border border-slate-300 px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-slate-950"><option value="">All statuses</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(request('status') === $status->value)>{{ $status->label() }}</option>@endforeach</select><button class="rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white dark:bg-teal-300 dark:text-slate-950">Filter</button></form></section>
        <section class="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="overflow-x-auto"><table class="w-full min-w-[920px] text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500 dark:bg-slate-950"><tr><th class="p-4">Proforma</th><th class="p-4">Customer</th><th class="p-4">Status</th><th class="p-4 text-right">Total</th><th class="p-4 text-right">Paid</th><th class="p-4 text-right">Balance</th><th class="p-4">Due</th><th class="p-4">Actions</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($proformas as $proforma)<tr><td class="p-4"><a class="font-semibold text-teal-700 dark:text-teal-300" href="{{ route('crm.proformas.show', $proforma) }}">{{ $proforma->proforma_number }}</a><p class="mt-1 text-xs text-slate-500">{{ $proforma->title }}</p></td><td class="p-4">{{ $proforma->customer_company ?: $proforma->customer_name }}</td><td class="p-4"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700 dark:bg-slate-800 dark:text-slate-200">{{ $proforma->status?->label() }}</span></td><td class="p-4 text-right">{{ $proforma->currency }} {{ number_format((float) $proforma->grand_total, 2) }}</td><td class="p-4 text-right">{{ number_format((float) $proforma->paid_amount, 2) }}</td><td class="p-4 text-right font-semibold">{{ number_format((float) $proforma->balance_amount, 2) }}</td><td class="p-4">{{ $proforma->due_date?->format('d M Y') }}</td><td class="p-4"><div class="flex flex-wrap gap-x-3 gap-y-2 text-xs font-semibold"><a class="text-teal-700 dark:text-teal-300" href="{{ route('crm.proformas.show', $proforma) }}">View</a><a href="{{ route('crm.proformas.pdf', $proforma) }}">PDF</a>@if($proforma->public_url)<button type="button" data-copy-text="{{ $proforma->public_url }}">Copy Link</button>@endif<a href="{{ route('crm.proformas.whatsapp', $proforma) }}">WhatsApp</a><a href="{{ route('crm.proformas.email.create', $proforma) }}">Email</a></div></td></tr>@empty<tr><td colspan="8" class="p-10 text-center text-slate-500">No proforma invoices found.</td></tr>@endforelse</tbody></table></div>@if($proformas->hasPages())<div class="p-4">{{ $proformas->links() }}</div>@endif</section>
    </div>
@endsection
