@extends('layouts.admin')
@section('title', $reseller->exists ? 'Edit reseller' : 'New reseller')
@section('page-title', $reseller->exists ? 'Edit reseller' : 'New reseller')
@section('breadcrumbs')<span>/</span><a href="{{ route('saas.resellers.index') }}">Resellers</a><span>/</span><span>{{ $reseller->exists ? 'Edit' : 'New' }}</span>@endsection
@section('content')
    @include('command-center.saas.partials.nav')
    <form method="POST" action="{{ $reseller->exists ? route('saas.resellers.update', $reseller) : route('saas.resellers.store') }}" class="mx-auto max-w-4xl rounded-lg border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">@csrf @if($reseller->exists) @method('PUT') @endif
        <div class="grid gap-5 md:grid-cols-2"><label class="text-sm font-medium">Partner code<input name="partner_code" required maxlength="80" value="{{ old('partner_code',$reseller->partner_code) }}" class="mt-1 block w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Company name<input name="company_name" required value="{{ old('company_name',$reseller->company_name) }}" class="mt-1 block w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Contact person<input name="contact_person" value="{{ old('contact_person',$reseller->contact_person) }}" class="mt-1 block w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Email<input name="email" type="email" value="{{ old('email',$reseller->email) }}" class="mt-1 block w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Phone<input name="phone" value="{{ old('phone',$reseller->phone) }}" class="mt-1 block w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Status<select name="status" class="mt-1 block w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950">@foreach(['active','inactive','prospect','terminated'] as $status)<option value="{{ $status }}" @selected(old('status',$reseller->status)===$status)>{{ str($status)->headline() }}</option>@endforeach</select></label><label class="text-sm font-medium">Referral source<input name="referral_source" value="{{ old('referral_source',$reseller->referral_source) }}" class="mt-1 block w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Agreement starts<input type="date" name="agreement_starts_at" value="{{ old('agreement_starts_at',$reseller->agreement_starts_at?->toDateString()) }}" class="mt-1 block w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Agreement ends<input type="date" name="agreement_ends_at" value="{{ old('agreement_ends_at',$reseller->agreement_ends_at?->toDateString()) }}" class="mt-1 block w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium md:col-span-2">Internal notes<textarea name="internal_notes" rows="5" class="mt-1 block w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950">{{ old('internal_notes',$reseller->internal_notes) }}</textarea></label></div><div class="mt-6 flex justify-end"><button class="rounded-md bg-slate-950 px-4 py-2 text-sm font-semibold text-white dark:bg-teal-300 dark:text-slate-950">Save reseller</button></div>
    </form>
@endsection
