@extends('layouts.admin')
@section('title', $reseller->company_name)
@section('page-title', $reseller->company_name)
@section('breadcrumbs')<span>/</span><a href="{{ route('saas.resellers.index') }}">Resellers</a><span>/</span><span>{{ $reseller->company_name }}</span>@endsection
@section('content')
    @include('command-center.saas.partials.nav')
    <div class="mb-5 flex justify-end"><a href="{{ route('saas.resellers.edit',$reseller) }}" class="rounded-md border border-slate-300 px-4 py-2 text-sm font-semibold dark:border-slate-700">Edit reseller</a></div>
    <div class="grid gap-6 lg:grid-cols-3"><section class="lg:col-span-2 rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold text-slate-950 dark:text-white">Tenant assignments</h2><form method="POST" action="{{ route('saas.resellers.tenants.assign',$reseller) }}" class="mt-5 grid gap-3 sm:grid-cols-[1fr_1fr_auto]">@csrf<select name="company_id" required class="rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"><option value="">Select tenant</option>@foreach($companies as $company)<option value="{{ $company->id }}">{{ $company->name }}</option>@endforeach</select><input name="notes" maxlength="1000" placeholder="Assignment note (optional)" class="rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"><button class="rounded-md bg-slate-950 px-4 py-2 text-sm font-semibold text-white dark:bg-teal-300 dark:text-slate-950">Assign</button></form><div class="mt-5 divide-y divide-slate-100 dark:divide-slate-800">@forelse($reseller->tenantAssignments->sortByDesc('assigned_at') as $assignment)<div class="flex flex-wrap items-center justify-between gap-3 py-4"><div><p class="font-medium text-slate-950 dark:text-white">{{ $assignment->company?->name }}</p><p class="mt-1 text-xs text-slate-500">Assigned {{ $assignment->assigned_at?->format('d M Y H:i') }} by {{ $assignment->assignedBy?->name ?? 'System' }}{{ $assignment->unassigned_at ? ' · unassigned '.$assignment->unassigned_at->format('d M Y H:i') : '' }}</p></div>@if(!$assignment->unassigned_at)<form method="POST" action="{{ route('saas.resellers.tenants.unassign',[$reseller,$assignment]) }}" onsubmit="return confirm('Close this tenant assignment?')">@csrf @method('DELETE')<button class="text-sm font-medium text-rose-700 dark:text-rose-300">Unassign</button></form>@endif</div>@empty<p class="py-8 text-center text-sm text-slate-500">No tenant assignments yet.</p>@endforelse</div></section><aside class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold text-slate-950 dark:text-white">Partner details</h2><dl class="mt-5 space-y-4 text-sm"><div><dt class="text-slate-500">Code</dt><dd class="font-medium">{{ $reseller->partner_code }}</dd></div><div><dt class="text-slate-500">Status</dt><dd class="mt-1"><x-status-badge :status="$reseller->status" /></dd></div><div><dt class="text-slate-500">Owner</dt><dd class="font-medium">{{ $reseller->owner?->name ?? '—' }}</dd></div><div><dt class="text-slate-500">Agreement</dt><dd>{{ $reseller->agreement_starts_at?->format('d M Y') ?? '—' }} to {{ $reseller->agreement_ends_at?->format('d M Y') ?? '—' }}</dd></div></dl></aside></div>
@endsection
