@extends('layouts.admin')

@section('title', 'Create Credit Note')
@section('page-title', 'Create Return / Credit Note')

@section('content')
<div class="mx-auto max-w-7xl space-y-6">
    <div class="flex flex-wrap items-center gap-2 text-sm"><a href="{{ route('sales.invoices.show', $invoice) }}" class="font-semibold text-teal-700 dark:text-teal-300">{{ $invoice->invoice_number }}</a><span class="text-slate-400">/</span><span class="text-slate-500">Create return</span></div>

    <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-6">
        <div class="grid gap-5 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-start"><div><p class="text-xs font-semibold uppercase text-amber-700 dark:text-amber-300">Review before finalizing</p><h1 class="mt-1 text-2xl font-semibold text-slate-950 dark:text-white">Credit items from {{ $invoice->invoice_number }}</h1><p class="mt-2 text-sm text-slate-500 dark:text-slate-400">{{ $invoice->billing_company ?: $invoice->billing_name }} · issued {{ $invoice->issue_date?->format('d M Y') }} · {{ $invoice->currency }} {{ number_format((float) $invoice->grand_total, 2) }}</p></div><button type="button" data-return-all class="min-h-11 rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:text-slate-200 dark:hover:bg-slate-800">Return All Remaining Items</button></div>
        <div class="mt-5 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950 dark:border-amber-900 dark:bg-amber-950/25 dark:text-amber-100"><p class="font-semibold">A finalized credit note cannot be edited.</p><p>The original invoice stays unchanged. The credit reduces the outstanding balance; it does not automatically refund cash, card, UPI, or bank payments.</p></div>
    </section>

    <form method="POST" action="{{ route('sales.invoices.returns.store', $invoice) }}" class="space-y-6" data-return-form onsubmit="return confirm('Finalize this credit note? This cannot be edited afterward.')">@csrf
        <input type="hidden" name="idempotency_key" value="{{ old('idempotency_key', (string) Str::uuid()) }}">
        <section class="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">
            <div class="border-b border-slate-200 p-5 dark:border-slate-800"><h2 class="font-semibold text-slate-950 dark:text-white">Items to return</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Enter only the quantity being returned now. Earlier finalized credits are already deducted.</p></div>
            <div class="divide-y divide-slate-100 dark:divide-slate-800">
                @foreach($lines as $index => $line)
                    @php($item = $line['item'])
                    <article class="grid gap-4 p-5 xl:grid-cols-[minmax(0,1.4fr)_10rem_10rem_minmax(0,1fr)] xl:items-start" data-return-line data-original-quantity="{{ $item->quantity }}" data-gross="{{ $item->gross_sales_snapshot ?? ((float) $item->line_subtotal + (float) $item->discount_amount) }}" data-discount="{{ $item->discount_amount }}" data-tax="{{ $item->tax_amount }}" data-credit="{{ $item->line_total }}" data-cogs="{{ $item->total_cost_snapshot }}">
                        <input type="hidden" name="items[{{ $index }}][invoice_item_id]" value="{{ $item->id }}">
                        <div><p class="font-semibold text-slate-950 dark:text-white">{{ $item->name }}</p><p class="mt-1 text-xs text-slate-500">{{ $item->sku_snapshot ?: 'Custom line' }} · {{ $item->quantity }} {{ $item->unit }} originally · {{ $item->tax_rate }}% tax</p><p class="mt-1 text-xs text-slate-500">Unit price {{ $invoice->currency }} {{ number_format((float) $item->unit_price, 2) }}</p><p class="mt-2 text-sm font-medium text-slate-700 dark:text-slate-200">{{ $line['returned_quantity'] }} already returned · <span class="text-teal-700 dark:text-teal-300">{{ $line['remaining_quantity'] }} remaining</span></p></div>
                        <label class="grid gap-1 text-sm font-medium text-slate-700 dark:text-slate-300">Return quantity<input data-return-quantity data-remaining="{{ $line['remaining_quantity'] }}" name="items[{{ $index }}][return_quantity]" value="{{ old("items.$index.return_quantity", '0') }}" type="number" min="0" max="{{ $line['remaining_quantity'] }}" step="0.001" class="rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950 dark:text-white"></label>
                        <div><p class="text-sm font-medium text-slate-700 dark:text-slate-300">Original line value</p><p class="mt-2 font-semibold text-slate-950 dark:text-white">{{ $invoice->currency }} {{ number_format((float) $item->line_total, 2) }}</p><p class="mt-1 text-xs text-slate-500">Tax {{ $invoice->currency }} {{ number_format((float) $item->tax_amount, 2) }}</p></div>
                        <div class="space-y-3">@if($line['can_restock'])<label class="flex items-start gap-3 rounded-lg border border-slate-200 p-3 text-sm dark:border-slate-700"><input type="hidden" name="items[{{ $index }}][restock]" value="0"><input type="checkbox" name="items[{{ $index }}][restock]" value="1" class="mt-0.5"><span><span class="font-semibold text-slate-900 dark:text-white">Return to sellable stock</span><span class="mt-1 block text-xs text-slate-500">Uses the original invoice stock location.</span></span></label>@else<p class="rounded-lg bg-slate-100 p-3 text-xs text-slate-600 dark:bg-slate-800 dark:text-slate-300">No stock will be added. This line has no authoritative original CRM stock movement.</p>@endif<input name="items[{{ $index }}][condition_note]" maxlength="1000" placeholder="Condition note (optional)" class="w-full rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-950 dark:text-white"></div>
                    </article>
                @endforeach
            </div>
        </section>

        <section class="grid gap-6 lg:grid-cols-[minmax(0,1fr)_22rem]">
            <div class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold text-slate-950 dark:text-white">Return reason</h2><div class="mt-4 grid gap-4 sm:grid-cols-2"><label class="grid gap-1 text-sm font-medium text-slate-700 dark:text-slate-300">Reason<select name="reason_code" required class="rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950 dark:text-white">@foreach(['customer_return'=>'Customer return','damaged'=>'Damaged','defective'=>'Defective','wrong_item'=>'Wrong item','billing_correction'=>'Billing correction','other'=>'Other'] as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label><label class="grid gap-1 text-sm font-medium text-slate-700 dark:text-slate-300 sm:col-span-2">Internal note<textarea name="reason_note" rows="3" maxlength="2000" class="rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950 dark:text-white" placeholder="Add helpful context for the audit history.">{{ old('reason_note') }}</textarea></label></div></div>
            <aside class="rounded-lg border border-teal-200 bg-teal-50/70 p-5 shadow-sm dark:border-teal-900 dark:bg-teal-950/20"><p class="text-xs font-semibold uppercase text-teal-700 dark:text-teal-300">Credit Note Summary</p><h2 class="mt-1 text-lg font-semibold text-slate-950 dark:text-white">Selected return</h2><dl class="mt-4 space-y-2 text-sm text-slate-600 dark:text-slate-300"><div class="flex justify-between gap-3"><dt>Subtotal reversal</dt><dd data-summary-gross>{{ $invoice->currency }} 0.00</dd></div><div class="flex justify-between gap-3"><dt>Discount reversal</dt><dd data-summary-discount>{{ $invoice->currency }} 0.00</dd></div><div class="flex justify-between gap-3"><dt>Tax reversal</dt><dd data-summary-tax>{{ $invoice->currency }} 0.00</dd></div><div class="flex justify-between gap-3 border-t border-teal-200 pt-2 font-semibold text-slate-950 dark:border-teal-900 dark:text-white"><dt>Grand credit</dt><dd data-summary-credit>{{ $invoice->currency }} 0.00</dd></div><div class="flex justify-between gap-3"><dt>Inventory effect</dt><dd data-summary-stock>No stock selected</dd></div><div class="flex justify-between gap-3"><dt>Known COGS reversal</dt><dd data-summary-cogs>{{ $invoice->currency }} 0.00</dd></div></dl><p class="mt-3 text-xs leading-5 text-slate-500 dark:text-slate-400">Previewed from the original invoice snapshots. Final amounts are recalculated securely with cumulative rounding when you confirm. No payment refund is created.</p><button class="mt-5 min-h-11 w-full rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-800 dark:bg-teal-300 dark:text-slate-950 dark:hover:bg-teal-200">Finalize Credit Note</button></aside>
        </section>
    </form>
</div>
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const currency=@json($invoice->currency);const money=value=>`${currency} ${value.toFixed(2)}`;const update=()=>{let gross=0,discount=0,tax=0,credit=0,cogs=0,restocked=0;document.querySelectorAll('[data-return-line]').forEach(line=>{const quantity=Math.max(0,Math.min(Number(line.querySelector('[data-return-quantity]')?.value||0),Number(line.dataset.originalQuantity||0)));const ratio=Number(line.dataset.originalQuantity)>0?quantity/Number(line.dataset.originalQuantity):0;gross+=Number(line.dataset.gross||0)*ratio;discount+=Number(line.dataset.discount||0)*ratio;tax+=Number(line.dataset.tax||0)*ratio;credit+=Number(line.dataset.credit||0)*ratio;if(line.dataset.cogs!=='')cogs+=Number(line.dataset.cogs||0)*ratio;if(quantity>0&&line.querySelector('input[type="checkbox"][name$="[restock]"]')?.checked)restocked+=quantity;});document.querySelector('[data-summary-gross]').textContent=money(gross);document.querySelector('[data-summary-discount]').textContent=money(discount);document.querySelector('[data-summary-tax]').textContent=money(tax);document.querySelector('[data-summary-credit]').textContent=money(credit);document.querySelector('[data-summary-cogs]').textContent=money(cogs);document.querySelector('[data-summary-stock]').textContent=restocked>0?`${restocked.toFixed(3)} units to sellable stock`:'No stock selected';};document.querySelector('[data-return-all]')?.addEventListener('click',()=>{document.querySelectorAll('[data-return-quantity]').forEach(input=>input.value=input.dataset.remaining);update();});document.querySelector('[data-return-form]')?.addEventListener('input',update);update();});</script>@endpush
@endsection
