@extends('layouts.admin')

@section('title', 'Website Content')
@section('page-title', 'Website Content')

@section('content')
    <div class="space-y-6">
        @include('command-center.cms.partials.nav')
        <section class="cms-panel">
            <div class="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p class="cms-kicker">Website Content</p><h1 class="mt-2 text-2xl font-semibold text-slate-900">Simple content editor</h1><p class="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Edit the words, calls to action, and content sections your website can use. Nothing here requires code knowledge.</p></div><a href="#add-page" class="inline-flex w-fit min-h-11 items-center rounded-lg bg-teal-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-teal-700">Add page</a></div>
        </section>

        <section class="cms-panel"><form method="GET" class="grid gap-3 md:grid-cols-4"><input name="search" value="{{ request('search') }}" placeholder="Search title, website path or page key" class="md:col-span-2"><select name="page_type"><option value="">All page types</option>@foreach ($pageTypes as $type)<option value="{{ $type }}" @selected(request('page_type') === $type)>{{ str($type)->replace('_', ' ')->headline() }}</option>@endforeach</select><select name="status"><option value="">Any status</option>@foreach (['draft', 'published', 'archived'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ str($status)->headline() }}</option>@endforeach</select><div class="md:col-span-4 flex gap-3"><button class="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Apply filters</button><a href="{{ route('cms.content.pages.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700">Clear</a></div></form></section>

        <section class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">@forelse ($pages as $page)<a href="{{ route('cms.content.pages.show', $page) }}" class="cms-section-card group"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><p class="truncate font-semibold text-slate-900">{{ $page->title }}</p><p class="mt-1 truncate text-sm text-slate-500">{{ $page->route_path ?: 'No public path yet' }}</p></div><x-status-badge :status="$page->status"/></div><div class="mt-5 flex items-center justify-between text-xs text-slate-500"><span>{{ str($page->page_type)->replace('_', ' ')->headline() }}</span><span>{{ $page->sections_count }} sections</span></div><p class="mt-3 text-sm font-semibold text-teal-700 group-hover:text-teal-800">Edit content</p></a>@empty<div class="cms-subtle-panel md:col-span-2 xl:col-span-3 text-center text-sm text-slate-500">No content pages match these filters. Add a page to start managing a new website path.</div>@endforelse</section>
        <div>{{ $pages->links() }}</div>

        @can('cms.content.create')
            <section id="add-page" class="cms-panel"><div><p class="cms-kicker">New content page</p><h2 class="mt-2 text-lg font-semibold text-slate-900">Add a website page</h2><p class="mt-1 text-sm text-slate-600">Choose a simple page type and the public path where the website may use this content later.</p></div><form method="POST" action="{{ route('cms.content.pages.store') }}" class="mt-5 grid gap-4 md:grid-cols-2">@csrf<div><label class="text-sm font-semibold text-slate-700">Page name</label><p class="mt-1 text-xs text-slate-500">Internal name for your team.</p><input name="title" value="{{ old('title') }}" required class="mt-2 w-full" placeholder="Retail ERP product page"></div><div><label class="text-sm font-semibold text-slate-700">Page key</label><p class="mt-1 text-xs text-slate-500">A short internal reference, for example retail-erp.</p><input name="page_key" value="{{ old('page_key') }}" required class="mt-2 w-full" placeholder="retail-erp"></div><div><label class="text-sm font-semibold text-slate-700">Website path</label><p class="mt-1 text-xs text-slate-500">Start with /, for example /products/retail-erp.</p><input name="route_path" value="{{ old('route_path') }}" class="mt-2 w-full" placeholder="/products/retail-erp"></div><div><label class="text-sm font-semibold text-slate-700">Page type</label><p class="mt-1 text-xs text-slate-500">This helps your team organize similar pages.</p><select name="page_type" class="mt-2 w-full">@foreach ($pageTypes as $type)<option value="{{ $type }}" @selected(old('page_type') === $type)>{{ str($type)->replace('_', ' ')->headline() }}</option>@endforeach</select></div><div class="md:col-span-2"><button class="rounded-lg bg-teal-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-teal-700">Create page</button></div></form></section>
        @endcan
    </div>
@endsection
