@extends('layouts.admin')

@section('title', $page->title)
@section('page-title', 'Website Content')

@section('content')
    <div class="space-y-6">
        @include('command-center.cms.partials.nav')
        <section class="cms-panel"><div class="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between"><div><p class="cms-kicker">{{ $page->route_path ?: 'No public path set' }}</p><h1 class="mt-2 text-2xl font-semibold text-slate-900">{{ $page->title }}</h1><p class="mt-2 text-sm text-slate-600">{{ str($page->page_type)->replace('_', ' ')->headline() }} page · {{ $page->sections->count() }} content sections</p></div><div class="flex flex-wrap gap-2"><a href="{{ route('cms.content.pages.preview', $page) }}" target="_blank" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700">Preview API output</a>@if ($page->status === 'published')<form method="POST" action="{{ route('cms.content.pages.unpublish', $page) }}">@csrf<button class="rounded-lg border border-amber-300 px-4 py-2.5 text-sm font-semibold text-amber-800">Move to draft</button></form>@else<form method="POST" action="{{ route('cms.content.pages.publish', $page) }}">@csrf<button class="rounded-lg bg-teal-600 px-4 py-2.5 text-sm font-semibold text-white">Publish</button></form>@endif</div></div></section>

        @if ($health)<section class="rounded-lg border border-amber-200 bg-amber-50 p-5"><h2 class="font-semibold text-amber-950">Content health</h2><p class="mt-1 text-sm text-amber-800">A few simple checks can help this page feel complete.</p><ul class="mt-3 grid gap-2 text-sm text-amber-900 sm:grid-cols-2">@foreach ($health as $warning)<li class="rounded-md bg-white/70 px-3 py-2">{{ $warning }}</li>@endforeach</ul></section>@endif

        <section class="cms-panel"><form method="POST" action="{{ route('cms.content.pages.update', $page) }}" class="grid gap-4 md:grid-cols-2">@csrf @method('PUT')<div><label class="text-sm font-semibold text-slate-700">Page name</label><p class="mt-1 text-xs text-slate-500">Visible only to your team.</p><input name="title" value="{{ old('title', $page->title) }}" required class="mt-2 w-full"></div><div><label class="text-sm font-semibold text-slate-700">Page key</label><p class="mt-1 text-xs text-slate-500">Internal reference used by the public API.</p><input name="page_key" value="{{ old('page_key', $page->page_key) }}" required class="mt-2 w-full"></div><div><label class="text-sm font-semibold text-slate-700">Website path</label><p class="mt-1 text-xs text-slate-500">A path starting with /. Leave blank for content not attached to a route yet.</p><input name="route_path" value="{{ old('route_path', $page->route_path) }}" class="mt-2 w-full"></div><div><label class="text-sm font-semibold text-slate-700">Page type</label><p class="mt-1 text-xs text-slate-500">Helps keep similar content together.</p><select name="page_type" class="mt-2 w-full">@foreach (config('cms-content.page_types') as $type)<option value="{{ $type }}" @selected(old('page_type', $page->page_type) === $type)>{{ str($type)->replace('_', ' ')->headline() }}</option>@endforeach</select></div><div class="md:col-span-2"><button class="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">{{ $page->status === 'published' ? 'Save page details' : 'Save Draft' }}</button></div></form></section>

        <section class="space-y-4"><div class="flex items-end justify-between gap-4"><div><p class="cms-kicker">Page sections</p><h2 class="mt-2 text-lg font-semibold text-slate-900">What visitors see</h2><p class="mt-1 text-sm text-slate-600">Use the cards below to edit each section. Disabled sections remain saved but are hidden from the public API.</p></div><a href="#add-section" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700">Add section</a></div>
            @foreach ($page->sections as $section)
                <details class="cms-panel" {{ $loop->first ? 'open' : '' }}><summary class="flex cursor-pointer list-none items-center justify-between gap-4"><div><p class="font-semibold text-slate-900">{{ $section->title ?: str($section->section_type)->replace('_', ' ')->headline() }}</p><p class="mt-1 text-sm text-slate-500">{{ str($section->section_type)->replace('_', ' ')->headline() }} · {{ $section->is_enabled ? 'Visible on the website' : 'Disabled' }}</p></div><span class="text-sm font-semibold text-teal-700">Edit</span></summary><div class="mt-5 border-t border-slate-100 pt-5"><form method="POST" action="{{ route('cms.content.sections.update', [$page, $section]) }}">@csrf @method('PUT')@include('command-center.cms.content.pages.section-form', ['section' => $section, 'sectionTypes' => $sectionTypes])<div class="mt-5 flex flex-wrap gap-2"><button class="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Save section</button></form><form method="POST" action="{{ route('cms.content.sections.move', [$page, $section]) }}">@csrf<input type="hidden" name="direction" value="up"><button class="rounded-lg border border-slate-300 px-3 py-2.5 text-sm font-semibold text-slate-700">Move Up</button></form><form method="POST" action="{{ route('cms.content.sections.move', [$page, $section]) }}">@csrf<input type="hidden" name="direction" value="down"><button class="rounded-lg border border-slate-300 px-3 py-2.5 text-sm font-semibold text-slate-700">Move Down</button></form><form method="POST" action="{{ route('cms.content.sections.toggle', [$page, $section]) }}">@csrf<input type="hidden" name="is_enabled" value="{{ $section->is_enabled ? 0 : 1 }}"><button class="rounded-lg border border-amber-300 px-3 py-2.5 text-sm font-semibold text-amber-800">{{ $section->is_enabled ? 'Disable Section' : 'Enable Section' }}</button></form><form method="POST" action="{{ route('cms.content.sections.destroy', [$page, $section]) }}" onsubmit="return confirm('Remove this section? This cannot be undone.')">@csrf @method('DELETE')<button class="rounded-lg border border-rose-300 px-3 py-2.5 text-sm font-semibold text-rose-700">Remove section</button></form></div></div></details>
            @endforeach
        </section>

        <section id="add-section" class="cms-panel"><p class="cms-kicker">Add section</p><h2 class="mt-2 text-lg font-semibold text-slate-900">Add new website content</h2><p class="mt-1 text-sm text-slate-600">Choose the content type first. The fields stay simple and adapt to the type you select.</p><form method="POST" action="{{ route('cms.content.sections.store', $page) }}" class="mt-5">@csrf @include('command-center.cms.content.pages.section-form', ['section' => null, 'sectionTypes' => $sectionTypes])<button class="mt-5 rounded-lg bg-teal-600 px-4 py-2.5 text-sm font-semibold text-white">Add Section</button></form></section>

        @can('cms.content.delete')<section class="border border-rose-200 bg-rose-50 p-5"><h2 class="font-semibold text-rose-950">Archive this page</h2><p class="mt-1 text-sm text-rose-800">Archiving removes this page from the public API but keeps its saved content for your records.</p><form method="POST" action="{{ route('cms.content.pages.archive', $page) }}" onsubmit="return confirm('Archive this page? It will no longer appear in the public API.')" class="mt-4">@csrf<button class="rounded-lg border border-rose-300 px-4 py-2.5 text-sm font-semibold text-rose-700">Archive page</button></form></section>@endcan
    </div>
@endsection
