<?php

return [
    'homepage_sections' => [
        'hero' => ['name' => 'Hero', 'sort_order' => 10],
        'features' => ['name' => 'Features', 'sort_order' => 20],
        'benefits' => ['name' => 'Benefits', 'sort_order' => 30],
        'modules' => ['name' => 'Modules', 'sort_order' => 40],
        'industries' => ['name' => 'Industries', 'sort_order' => 50],
        'solutions' => ['name' => 'Solutions', 'sort_order' => 60],
        'pricing_cta' => ['name' => 'Pricing CTA', 'sort_order' => 70],
        'testimonials' => ['name' => 'Testimonials', 'sort_order' => 80],
        'partners' => ['name' => 'Partners', 'sort_order' => 90],
        'statistics' => ['name' => 'Statistics', 'sort_order' => 100],
        'faq' => ['name' => 'FAQ', 'sort_order' => 110],
        'final_cta' => ['name' => 'Final CTA', 'sort_order' => 120],
        'footer_cta' => ['name' => 'Footer CTA', 'sort_order' => 130],
        'trust_metrics' => ['name' => 'Trust Metrics', 'sort_order' => 135],
        'client_logos' => ['name' => 'Client Logo Wall', 'sort_order' => 140],
        'product_showcase' => ['name' => 'Product Showcase', 'sort_order' => 145],
        'ai_features' => ['name' => 'AI Features', 'sort_order' => 150],
        'mobile_app' => ['name' => 'Mobile App', 'sort_order' => 155],
        'screenshots' => ['name' => 'Screenshots and Mockups', 'sort_order' => 160],
        'case_studies' => ['name' => 'Case Studies', 'sort_order' => 165],
    ],

    'settings' => [
        'website_name' => ['label' => 'Website Name', 'type' => 'text'],
        'tagline' => ['label' => 'Tagline', 'type' => 'text'],
        'default_meta' => ['label' => 'Default Meta', 'type' => 'textarea'],
        'default_og_image' => ['label' => 'Default OG Image', 'type' => 'media'],
        'logo' => ['label' => 'Logo', 'type' => 'media'],
        'dark_logo' => ['label' => 'Dark Logo', 'type' => 'media'],
        'favicon' => ['label' => 'Favicon', 'type' => 'media'],
        'email' => ['label' => 'Email', 'type' => 'email'],
        'phone' => ['label' => 'Phone', 'type' => 'text'],
        'whatsapp' => ['label' => 'WhatsApp', 'type' => 'text'],
        'address' => ['label' => 'Address', 'type' => 'textarea'],
        'business_hours' => ['label' => 'Business Hours', 'type' => 'textarea'],
        'google_map' => ['label' => 'Google Map', 'type' => 'url'],
    ],

    'menu_locations' => [
        'header' => 'Header Menu',
        'footer' => 'Footer Menu',
        'mega' => 'Mega Menu',
        'legal' => 'Legal Links',
        'mobile' => 'Mobile Menu',
    ],

    'branding_settings' => [
        'brand_name' => ['label' => 'Brand Name', 'type' => 'text'],
        'brand_tagline' => ['label' => 'Brand Tagline', 'type' => 'text'],
        'primary_logo' => ['label' => 'Primary Logo', 'type' => 'media'],
        'light_logo' => ['label' => 'Light Logo', 'type' => 'media'],
        'dark_logo' => ['label' => 'Dark Logo', 'type' => 'media'],
        'icon_logo' => ['label' => 'Icon Logo', 'type' => 'media'],
        'favicon' => ['label' => 'Favicon', 'type' => 'media'],
        'apple_touch_icon' => ['label' => 'Apple Touch Icon', 'type' => 'media'],
        'default_og_image' => ['label' => 'Default Open Graph Image', 'type' => 'media'],
        'primary_brand_color' => ['label' => 'Primary Brand Color', 'type' => 'text'],
        'secondary_brand_color' => ['label' => 'Secondary Brand Color', 'type' => 'text'],
        'accent_brand_color' => ['label' => 'Accent Brand Color', 'type' => 'text'],
        'button_style' => ['label' => 'Button Style', 'type' => 'text'],
        'default_cta_text' => ['label' => 'Default CTA Text', 'type' => 'text'],
        'default_cta_link' => ['label' => 'Default CTA Link', 'type' => 'url'],
    ],

    'header_settings' => [
        'header_logo' => ['label' => 'Header Logo', 'type' => 'media'],
        'header_sticky' => ['label' => 'Sticky Header', 'type' => 'boolean'],
        'header_cta_text' => ['label' => 'Header CTA Text', 'type' => 'text'],
        'header_cta_link' => ['label' => 'Header CTA Link', 'type' => 'url'],
        'header_login_label' => ['label' => 'Login Button Label', 'type' => 'text'],
        'header_demo_label' => ['label' => 'Demo Button Label', 'type' => 'text'],
        'header_whatsapp_cta' => ['label' => 'WhatsApp CTA Foundation', 'type' => 'text'],
    ],

    'media_types' => [
        'image' => ['image/jpeg', 'image/png', 'image/webp', 'image/gif'],
        'svg' => ['image/svg+xml'],
        'pdf' => ['application/pdf'],
        'video' => ['video/mp4', 'video/webm', 'video/quicktime'],
    ],
];
