<?php

$channels = ['database', 'email', 'webhook'];
$futureChannels = ['whatsapp', 'sms', 'push'];

return [
    'retention_days' => env('DOMAIN_EVENT_RETENTION_DAYS', 180),

    'channels' => [
        'database' => ['name' => 'In-app', 'enabled' => true],
        'email' => ['name' => 'Email', 'enabled' => true],
        'webhook' => ['name' => 'Webhook', 'enabled' => true],
        'whatsapp' => ['name' => 'WhatsApp', 'enabled' => false],
        'sms' => ['name' => 'SMS', 'enabled' => false],
        'push' => ['name' => 'Push', 'enabled' => false],
    ],

    'catalog' => [
        'auth.login' => ['name' => 'User login', 'description' => 'A user signed in.', 'category' => 'Authentication', 'default_channels' => ['database'], 'allowed_channels' => $channels, 'severity' => 'info', 'user_preference_enabled' => false, 'webhook_enabled' => false, 'future_ai_eligible' => false],
        'auth.logout' => ['name' => 'User logout', 'description' => 'A user signed out.', 'category' => 'Authentication', 'default_channels' => ['database'], 'allowed_channels' => $channels, 'severity' => 'info', 'user_preference_enabled' => false, 'webhook_enabled' => false, 'future_ai_eligible' => false],
        'auth.password_reset_requested' => ['name' => 'Password reset requested', 'description' => 'A password reset link was requested.', 'category' => 'Authentication', 'default_channels' => ['database'], 'allowed_channels' => $channels, 'severity' => 'warning', 'user_preference_enabled' => false, 'webhook_enabled' => false, 'future_ai_eligible' => false],
        'auth.password_reset_completed' => ['name' => 'Password reset completed', 'description' => 'A password was reset.', 'category' => 'Authentication', 'default_channels' => ['database'], 'allowed_channels' => $channels, 'severity' => 'warning', 'user_preference_enabled' => false, 'webhook_enabled' => false, 'future_ai_eligible' => false],

        'crm.lead.created' => ['name' => 'Lead created', 'description' => 'A CRM lead was created.', 'category' => 'CRM', 'default_channels' => ['database'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'info', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'crm.lead.updated' => ['name' => 'Lead updated', 'description' => 'A CRM lead was updated.', 'category' => 'CRM', 'default_channels' => ['database'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'info', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'crm.lead.assigned' => ['name' => 'Lead assigned', 'description' => 'A CRM lead was assigned to a user.', 'category' => 'CRM', 'default_channels' => ['database', 'email'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'info', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'crm.lead.status_changed' => ['name' => 'Lead status changed', 'description' => 'A CRM lead moved to a new status.', 'category' => 'CRM', 'default_channels' => ['database'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'info', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'crm.lead.converted' => ['name' => 'Lead converted', 'description' => 'A CRM lead was converted.', 'category' => 'CRM', 'default_channels' => ['database'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'success', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'crm.follow_up.due' => ['name' => 'Follow-up due', 'description' => 'A CRM follow-up is due.', 'category' => 'CRM', 'default_channels' => ['database', 'email'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'warning', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'crm.follow_up.overdue' => ['name' => 'Follow-up overdue', 'description' => 'A CRM follow-up is overdue.', 'category' => 'CRM', 'default_channels' => ['database', 'email'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'danger', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'crm.activity.created' => ['name' => 'Activity created', 'description' => 'A CRM activity was created.', 'category' => 'CRM', 'default_channels' => ['database'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'info', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'crm.activity.completed' => ['name' => 'Activity completed', 'description' => 'A CRM activity was completed.', 'category' => 'CRM', 'default_channels' => ['database'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'success', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],

        'cms.page.created' => ['name' => 'CMS page created', 'description' => 'A CMS page was created.', 'category' => 'CMS', 'default_channels' => ['database'], 'allowed_channels' => $channels, 'severity' => 'info', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => false],
        'cms.page.updated' => ['name' => 'CMS page updated', 'description' => 'A CMS page was updated.', 'category' => 'CMS', 'default_channels' => ['database'], 'allowed_channels' => $channels, 'severity' => 'info', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => false],
        'cms.page.published' => ['name' => 'CMS page published', 'description' => 'A CMS page was published.', 'category' => 'CMS', 'default_channels' => ['database'], 'allowed_channels' => $channels, 'severity' => 'success', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => false],
        'cms.page.unpublished' => ['name' => 'CMS page unpublished', 'description' => 'A CMS page was unpublished.', 'category' => 'CMS', 'default_channels' => ['database'], 'allowed_channels' => $channels, 'severity' => 'warning', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => false],
        'cms.media.uploaded' => ['name' => 'CMS media uploaded', 'description' => 'A media file was uploaded.', 'category' => 'CMS', 'default_channels' => ['database'], 'allowed_channels' => $channels, 'severity' => 'info', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => false],
        'cms.redirect.created' => ['name' => 'CMS redirect created', 'description' => 'A redirect was created.', 'category' => 'CMS', 'default_channels' => ['database'], 'allowed_channels' => $channels, 'severity' => 'info', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => false],
        'cms.broken_link.detected' => ['name' => 'Broken link detected', 'description' => 'A broken website link was detected.', 'category' => 'CMS', 'default_channels' => ['database', 'email'], 'allowed_channels' => $channels, 'severity' => 'danger', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => false],

        'inventory.product.created' => ['name' => 'Product created', 'description' => 'An inventory product was created.', 'category' => 'Inventory', 'default_channels' => ['database'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'info', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'inventory.product.updated' => ['name' => 'Product updated', 'description' => 'An inventory product was updated.', 'category' => 'Inventory', 'default_channels' => ['database'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'info', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'inventory.stock.opening_recorded' => ['name' => 'Opening stock recorded', 'description' => 'Opening stock was recorded for a product.', 'category' => 'Inventory', 'default_channels' => ['database'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'info', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'inventory.stock.adjusted' => ['name' => 'Stock adjusted', 'description' => 'A stock adjustment was approved and posted to the ledger.', 'category' => 'Inventory', 'default_channels' => ['database'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'warning', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'inventory.stock.low' => ['name' => 'Low stock detected', 'description' => 'Available stock reached the configured threshold.', 'category' => 'Inventory', 'default_channels' => ['database', 'email'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'warning', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'inventory.stock.out' => ['name' => 'Out of stock detected', 'description' => 'A tracked product is out of stock.', 'category' => 'Inventory', 'default_channels' => ['database', 'email'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'danger', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'inventory.reorder.suggested' => ['name' => 'Reorder suggested', 'description' => 'A reorder suggestion was generated from inventory rules.', 'category' => 'Inventory', 'default_channels' => ['database', 'email'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'warning', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'inventory.channel.sync_warning' => ['name' => 'Channel sync warning', 'description' => 'An internal sales channel sync warning was recorded.', 'category' => 'Inventory', 'default_channels' => ['database', 'email'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'warning', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],

        'purchase.supplier.created' => ['name' => 'Supplier created', 'description' => 'A supplier was created.', 'category' => 'Purchases', 'default_channels' => ['database'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'info', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'purchase.supplier.updated' => ['name' => 'Supplier updated', 'description' => 'A supplier was updated.', 'category' => 'Purchases', 'default_channels' => ['database'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'info', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'purchase.supplier.score_updated' => ['name' => 'Supplier score updated', 'description' => 'A supplier score snapshot was recalculated.', 'category' => 'Purchases', 'default_channels' => ['database'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'warning', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'purchase.request.created' => ['name' => 'Purchase request created', 'description' => 'A purchase request was created.', 'category' => 'Purchases', 'default_channels' => ['database'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'info', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'purchase.request.submitted' => ['name' => 'Purchase request submitted', 'description' => 'A purchase request is waiting for approval.', 'category' => 'Purchases', 'default_channels' => ['database', 'email'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'warning', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'purchase.request.approved' => ['name' => 'Purchase request approved', 'description' => 'A purchase request was approved.', 'category' => 'Purchases', 'default_channels' => ['database'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'success', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'purchase.request.rejected' => ['name' => 'Purchase request rejected', 'description' => 'A purchase request was rejected.', 'category' => 'Purchases', 'default_channels' => ['database'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'danger', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'purchase.request.converted_to_po' => ['name' => 'Purchase request converted to PO', 'description' => 'An approved purchase request was converted to a purchase order.', 'category' => 'Purchases', 'default_channels' => ['database'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'success', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'purchase.reorder_request.created' => ['name' => 'Reorder request created', 'description' => 'A purchase request was created from reorder suggestions.', 'category' => 'Purchases', 'default_channels' => ['database', 'email'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'warning', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'purchase.order.created' => ['name' => 'Purchase order created', 'description' => 'A purchase order was created.', 'category' => 'Purchases', 'default_channels' => ['database'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'info', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'purchase.order.submitted' => ['name' => 'Purchase order submitted', 'description' => 'A purchase order is waiting for approval.', 'category' => 'Purchases', 'default_channels' => ['database', 'email'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'warning', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'purchase.order.approved' => ['name' => 'Purchase order approved', 'description' => 'A purchase order was approved.', 'category' => 'Purchases', 'default_channels' => ['database'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'success', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'purchase.order.sent' => ['name' => 'Purchase order sent', 'description' => 'A purchase order was marked as sent to supplier.', 'category' => 'Purchases', 'default_channels' => ['database'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'info', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'purchase.order.cancelled' => ['name' => 'Purchase order cancelled', 'description' => 'A purchase order was cancelled.', 'category' => 'Purchases', 'default_channels' => ['database'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'danger', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'purchase.goods_received' => ['name' => 'Goods received', 'description' => 'A goods receipt was posted to stock.', 'category' => 'Purchases', 'default_channels' => ['database', 'email'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'success', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'purchase.return.created' => ['name' => 'Purchase return created', 'description' => 'A purchase return was created.', 'category' => 'Purchases', 'default_channels' => ['database'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'info', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'purchase.return.approved' => ['name' => 'Purchase return approved', 'description' => 'A purchase return was approved.', 'category' => 'Purchases', 'default_channels' => ['database'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'success', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],
        'purchase.return.completed' => ['name' => 'Purchase return completed', 'description' => 'A purchase return was posted to stock.', 'category' => 'Purchases', 'default_channels' => ['database', 'email'], 'allowed_channels' => array_merge($channels, $futureChannels), 'severity' => 'warning', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => true],

        'system.user.created' => ['name' => 'User created', 'description' => 'A platform user was created.', 'category' => 'System', 'default_channels' => ['database'], 'allowed_channels' => $channels, 'severity' => 'info', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => false],
        'system.user.deactivated' => ['name' => 'User deactivated', 'description' => 'A platform user was deactivated.', 'category' => 'System', 'default_channels' => ['database'], 'allowed_channels' => $channels, 'severity' => 'warning', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => false],
        'system.settings.updated' => ['name' => 'Settings updated', 'description' => 'Command Center settings were updated.', 'category' => 'System', 'default_channels' => ['database'], 'allowed_channels' => $channels, 'severity' => 'info', 'user_preference_enabled' => true, 'webhook_enabled' => true, 'future_ai_eligible' => false],
        'system.webhook.failed' => ['name' => 'Webhook failed', 'description' => 'A webhook delivery failed.', 'category' => 'System', 'default_channels' => ['database', 'email'], 'allowed_channels' => $channels, 'severity' => 'danger', 'user_preference_enabled' => true, 'webhook_enabled' => false, 'future_ai_eligible' => false],
        'system.queue.failed' => ['name' => 'Queue failed', 'description' => 'A queued job failed.', 'category' => 'System', 'default_channels' => ['database', 'email'], 'allowed_channels' => $channels, 'severity' => 'danger', 'user_preference_enabled' => true, 'webhook_enabled' => false, 'future_ai_eligible' => false],
    ],
];
