<?php

$allRoles = ['administrator', 'manager', 'sales', 'staff'];
$managementRoles = ['administrator', 'manager'];
$administratorRoles = ['administrator'];
$crmRoles = ['administrator', 'manager', 'sales'];
$notificationRoles = ['administrator', 'manager', 'sales'];
$operationsRoles = ['administrator', 'manager'];
$inventoryRoles = ['administrator', 'manager', 'sales'];
$promotionRoles = ['administrator', 'manager', 'sales'];
$promotionManagementRoles = ['administrator', 'manager'];
$customerRoles = ['administrator', 'manager', 'sales'];
$posRoles = ['administrator', 'manager', 'sales'];

return [
    'modules' => [
        'dashboard' => [
            'name' => 'Dashboard',
            'description' => 'Executive operating overview for the Command Center.',
            'icon' => 'dashboard',
            'route' => 'dashboard',
            'route_params' => [],
            'sort_order' => 10,
            'category' => 'Overview',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $allRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'crm' => [
            'name' => 'CRM',
            'description' => 'Enterprise sales and relationship command center.',
            'icon' => 'crm',
            'route' => 'crm.dashboard',
            'route_params' => [],
            'sort_order' => 100,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $crmRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'crm-dashboard' => [
            'name' => 'CRM Dashboard',
            'description' => 'Pipeline, activity, and lead health metrics.',
            'icon' => 'dashboard',
            'route' => 'crm.dashboard',
            'route_params' => [],
            'sort_order' => 101,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $crmRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'crm',
        ],
        'contacts' => [
            'name' => 'Contacts',
            'description' => 'People and decision makers linked to CRM accounts.',
            'icon' => 'contacts',
            'route' => 'crm.contacts.index',
            'route_params' => [],
            'sort_order' => 110,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $crmRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'crm',
        ],
        'leads' => [
            'name' => 'Leads',
            'description' => 'Qualified opportunities and follow-up lifecycle.',
            'icon' => 'leads',
            'route' => 'crm.leads.index',
            'route_params' => [],
            'sort_order' => 120,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $crmRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'crm',
        ],
        'demo-requests' => [
            'name' => 'Demo Requests',
            'description' => 'Website and campaign demo enquiries awaiting follow-up.',
            'icon' => 'leads',
            'route' => 'crm.demo-requests.index',
            'route_params' => [],
            'sort_order' => 121,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $crmRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'crm',
        ],
        'crm-quotations' => [
            'name' => 'Quotations',
            'description' => 'Professional proposals and customer-ready quotation links.',
            'icon' => 'sales',
            'route' => 'crm.quotations.index',
            'route_params' => [],
            'sort_order' => 122,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $crmRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'crm',
        ],
        'crm-companies' => [
            'name' => 'Companies',
            'description' => 'CRM account records, owners, timelines, and related leads.',
            'icon' => 'company',
            'route' => 'crm.companies.index',
            'route_params' => [],
            'sort_order' => 125,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $crmRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'crm',
        ],
        'crm-pipeline' => [
            'name' => 'Pipeline',
            'description' => 'Server-rendered sales pipeline by status.',
            'icon' => 'sales',
            'route' => 'crm.pipeline.index',
            'route_params' => [],
            'sort_order' => 126,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $crmRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'crm',
        ],
        'crm-activities' => [
            'name' => 'Activities',
            'description' => 'Calls, meetings, emails, WhatsApp tasks, and follow-ups.',
            'icon' => 'audit',
            'route' => 'crm.activities.index',
            'route_params' => [],
            'sort_order' => 127,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $crmRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'crm',
        ],
        'crm-follow-ups' => [
            'name' => 'Follow-ups',
            'description' => 'Upcoming and overdue follow-up queue.',
            'icon' => 'bell',
            'route' => 'crm.followups.index',
            'route_params' => [],
            'sort_order' => 128,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $crmRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'crm',
        ],
        'sales' => [
            'name' => 'Sales',
            'description' => 'Sales activity module foundation.',
            'icon' => 'sales',
            'route' => 'modules.show',
            'route_params' => ['module' => 'sales'],
            'sort_order' => 130,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $allRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'pos' => [
            'name' => 'POS',
            'description' => 'Cashier billing with desktop and mobile PWA-ready experiences.',
            'icon' => 'pos',
            'route' => 'pos.index',
            'route_params' => [],
            'sort_order' => 140,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $posRoles,
            'badge' => ['label' => 'New', 'tone' => 'info'],
            'license_key' => null,
            'parent_id' => null,
        ],
        'pos-billing' => ['name'=>'Terminal','description'=>'Full-screen cashier billing terminal.','icon'=>'pos','route'=>'pos.terminal','route_params'=>[],'sort_order'=>141,'category'=>'Sales & CRM','enabled'=>true,'visible_in_sidebar'=>true,'roles'=>$posRoles,'badge'=>null,'license_key'=>null,'parent_id'=>'pos'],
        'pos-held' => ['name'=>'Held Bills','description'=>'Resume bills held by the current cashier.','icon'=>'audit','route'=>'pos.held.index','route_params'=>[],'sort_order'=>142,'category'=>'Sales & CRM','enabled'=>true,'visible_in_sidebar'=>true,'roles'=>$posRoles,'badge'=>null,'license_key'=>null,'parent_id'=>'pos'],
        'pos-offline' => ['name'=>'Offline Sync','description'=>'Review offline POS synchronization records.','icon'=>'activity','route'=>'pos.offline.index','route_params'=>[],'sort_order'=>143,'category'=>'Sales & CRM','enabled'=>true,'visible_in_sidebar'=>true,'roles'=>['administrator','manager'],'badge'=>null,'license_key'=>null,'parent_id'=>'pos'],
        'customers' => [
            'name' => 'Customers',
            'description' => 'Customer intelligence, loyalty, wallet, and retention foundation.',
            'icon' => 'customers',
            'route' => 'customers.dashboard',
            'route_params' => [],
            'sort_order' => 150,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $customerRoles,
            'badge' => ['label' => 'New', 'tone' => 'info'],
            'license_key' => null,
            'parent_id' => null,
        ],
        'customer-dashboard' => ['name'=>'Customer Dashboard','description'=>'Customer health, retention, and value overview.','icon'=>'dashboard','route'=>'customers.dashboard','route_params'=>[],'sort_order'=>151,'category'=>'Sales & CRM','enabled'=>true,'visible_in_sidebar'=>true,'roles'=>$customerRoles,'badge'=>null,'license_key'=>null,'parent_id'=>'customers'],
        'customer-records' => ['name'=>'Customers','description'=>'Customer directory and profiles.','icon'=>'customers','route'=>'customers.index','route_params'=>[],'sort_order'=>152,'category'=>'Sales & CRM','enabled'=>true,'visible_in_sidebar'=>true,'roles'=>$customerRoles,'badge'=>null,'license_key'=>null,'parent_id'=>'customers'],
        'customer-groups' => ['name'=>'Customer Groups','description'=>'Customer segments for loyalty and future promotions.','icon'=>'users','route'=>'customers.groups.index','route_params'=>[],'sort_order'=>153,'category'=>'Sales & CRM','enabled'=>true,'visible_in_sidebar'=>true,'roles'=>$customerRoles,'badge'=>null,'license_key'=>null,'parent_id'=>'customers'],
        'customer-loyalty' => ['name'=>'Loyalty Foundation','description'=>'Loyalty accounts and points history.','icon'=>'analytics','route'=>'customers.insights.index','route_params'=>[],'sort_order'=>154,'category'=>'Sales & CRM','enabled'=>true,'visible_in_sidebar'=>true,'roles'=>$customerRoles,'badge'=>null,'license_key'=>null,'parent_id'=>'customers'],
        'customer-birthdays' => ['name'=>'Birthday Reminders','description'=>'Upcoming customer birthday foundation.','icon'=>'calendar','route'=>'customers.birthdays.index','route_params'=>[],'sort_order'=>155,'category'=>'Sales & CRM','enabled'=>true,'visible_in_sidebar'=>true,'roles'=>$customerRoles,'badge'=>null,'license_key'=>null,'parent_id'=>'customers'],
        'customer-insights' => ['name'=>'Customer Insights','description'=>'Rule-based customer intelligence.','icon'=>'analytics','route'=>'customers.insights.index','route_params'=>[],'sort_order'=>156,'category'=>'Sales & CRM','enabled'=>true,'visible_in_sidebar'=>true,'roles'=>$customerRoles,'badge'=>null,'license_key'=>null,'parent_id'=>'customers'],
        'customer-inactive' => ['name'=>'Inactive Customers','description'=>'Customers reaching the configured inactivity threshold.','icon'=>'analytics','route'=>'customers.inactive.index','route_params'=>[],'sort_order'=>157,'category'=>'Sales & CRM','enabled'=>true,'visible_in_sidebar'=>true,'roles'=>$customerRoles,'badge'=>null,'license_key'=>null,'parent_id'=>'customers'],
        'customer-lost' => ['name'=>'Lost Customers','description'=>'Customers reaching the configured lost threshold.','icon'=>'analytics','route'=>'customers.lost.index','route_params'=>[],'sort_order'=>158,'category'=>'Sales & CRM','enabled'=>true,'visible_in_sidebar'=>true,'roles'=>$customerRoles,'badge'=>null,'license_key'=>null,'parent_id'=>'customers'],
        'customer-returns' => ['name'=>'Frequent Returns','description'=>'Customers flagged by return behavior.','icon'=>'analytics','route'=>'customers.returns.index','route_params'=>[],'sort_order'=>159,'category'=>'Sales & CRM','enabled'=>true,'visible_in_sidebar'=>true,'roles'=>$customerRoles,'badge'=>null,'license_key'=>null,'parent_id'=>'customers'],
        'customer-wallet' => ['name'=>'Customer Wallet','description'=>'Customer wallet balances and profile adjustments.','icon'=>'finance','route'=>'customers.index','route_params'=>[],'sort_order'=>160,'category'=>'Sales & CRM','enabled'=>true,'visible_in_sidebar'=>true,'roles'=>$customerRoles,'badge'=>null,'license_key'=>null,'parent_id'=>'customers'],
        'customer-settings' => ['name'=>'Customer Settings','description'=>'Customer numbering, loyalty, wallet, and intelligence thresholds.','icon'=>'settings','route'=>'customers.settings.index','route_params'=>[],'sort_order'=>161,'category'=>'Sales & CRM','enabled'=>true,'visible_in_sidebar'=>true,'roles'=>$customerRoles,'badge'=>null,'license_key'=>null,'parent_id'=>'customers'],
        'orders' => [
            'name' => 'Orders',
            'description' => 'Order management module foundation.',
            'icon' => 'orders',
            'route' => 'modules.show',
            'route_params' => ['module' => 'orders'],
            'sort_order' => 160,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $allRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'promotions' => [
            'name' => 'Promotions',
            'description' => 'Centralized discount, coupon, campaign, and retail offer operations.',
            'icon' => 'tag',
            'route' => 'promotions.dashboard',
            'route_params' => [],
            'sort_order' => 170,
            'category' => 'Sales & Marketing',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $promotionRoles,
            'badge' => ['label' => 'New', 'tone' => 'info'],
            'license_key' => null,
            'parent_id' => null,
        ],
        'promotion-dashboard' => [
            'name' => 'Promotion Dashboard', 'description' => 'Promotion health, active offers, and simulation signals.', 'icon' => 'dashboard', 'route' => 'promotions.dashboard', 'route_params' => [], 'sort_order' => 171, 'category' => 'Sales & Marketing', 'enabled' => true, 'visible_in_sidebar' => true, 'roles' => $promotionRoles, 'badge' => null, 'license_key' => null, 'parent_id' => 'promotions',
        ],
        'promotion-campaigns' => [
            'name' => 'Campaigns', 'description' => 'Seasonal, festival, clearance, branch, and channel campaigns.', 'icon' => 'marketing', 'route' => 'promotions.campaigns.index', 'route_params' => [], 'sort_order' => 172, 'category' => 'Sales & Marketing', 'enabled' => true, 'visible_in_sidebar' => true, 'roles' => $promotionRoles, 'badge' => null, 'license_key' => null, 'parent_id' => 'promotions',
        ],
        'promotion-rules' => [
            'name' => 'Discount Rules', 'description' => 'Targeted discount and offer rule management.', 'icon' => 'tag', 'route' => 'promotions.rules.index', 'route_params' => [], 'sort_order' => 173, 'category' => 'Sales & Marketing', 'enabled' => true, 'visible_in_sidebar' => true, 'roles' => $promotionRoles, 'badge' => null, 'license_key' => null, 'parent_id' => 'promotions',
        ],
        'promotion-buy-x-get-y' => [
            'name' => 'Buy X Get Y', 'description' => 'Buy-and-get offer rule workspace.', 'icon' => 'tag', 'route' => 'promotions.rules.index', 'route_params' => ['promotion_type' => 'buy_x_get_y'], 'sort_order' => 174, 'category' => 'Sales & Marketing', 'enabled' => true, 'visible_in_sidebar' => true, 'roles' => $promotionRoles, 'badge' => null, 'license_key' => null, 'parent_id' => 'promotions',
        ],
        'promotion-coupons' => [
            'name' => 'Coupons', 'description' => 'Coupon lifecycle, activation, and redemption foundation.', 'icon' => 'tag', 'route' => 'promotions.coupons.index', 'route_params' => [], 'sort_order' => 175, 'category' => 'Sales & Marketing', 'enabled' => true, 'visible_in_sidebar' => true, 'roles' => $promotionRoles, 'badge' => null, 'license_key' => null, 'parent_id' => 'promotions',
        ],
        'promotion-combos' => [
            'name' => 'Combo Offers', 'description' => 'Fixed-price and bundle discount foundation.', 'icon' => 'tag', 'route' => 'promotions.rules.index', 'route_params' => ['promotion_type' => 'bundle_discount'], 'sort_order' => 176, 'category' => 'Sales & Marketing', 'enabled' => true, 'visible_in_sidebar' => true, 'roles' => $promotionRoles, 'badge' => null, 'license_key' => null, 'parent_id' => 'promotions',
        ],
        'promotion-product-offers' => [
            'name' => 'Product Offers', 'description' => 'Product and variant-targeted discounts.', 'icon' => 'products', 'route' => 'promotions.rules.index', 'route_params' => ['promotion_type' => 'percentage_discount'], 'sort_order' => 177, 'category' => 'Sales & Marketing', 'enabled' => true, 'visible_in_sidebar' => true, 'roles' => $promotionRoles, 'badge' => null, 'license_key' => null, 'parent_id' => 'promotions',
        ],
        'promotion-category-offers' => [
            'name' => 'Category Offers', 'description' => 'Category-targeted discount rules.', 'icon' => 'package', 'route' => 'promotions.rules.index', 'route_params' => ['promotion_type' => 'percentage_discount'], 'sort_order' => 178, 'category' => 'Sales & Marketing', 'enabled' => true, 'visible_in_sidebar' => true, 'roles' => $promotionRoles, 'badge' => null, 'license_key' => null, 'parent_id' => 'promotions',
        ],
        'promotion-brand-offers' => [
            'name' => 'Brand Offers', 'description' => 'Brand-targeted discount rules.', 'icon' => 'marketing', 'route' => 'promotions.rules.index', 'route_params' => ['promotion_type' => 'percentage_discount'], 'sort_order' => 179, 'category' => 'Sales & Marketing', 'enabled' => true, 'visible_in_sidebar' => true, 'roles' => $promotionRoles, 'badge' => null, 'license_key' => null, 'parent_id' => 'promotions',
        ],
        'promotion-channel-offers' => [
            'name' => 'Channel Offers', 'description' => 'Store, web, WhatsApp, and marketplace-ready channel offers.', 'icon' => 'sales', 'route' => 'promotions.rules.index', 'route_params' => ['promotion_type' => 'channel_discount'], 'sort_order' => 180, 'category' => 'Sales & Marketing', 'enabled' => true, 'visible_in_sidebar' => true, 'roles' => $promotionRoles, 'badge' => null, 'license_key' => null, 'parent_id' => 'promotions',
        ],
        'promotion-branch-offers' => [
            'name' => 'Branch Offers', 'description' => 'Branch-targeted promotion rules.', 'icon' => 'branches', 'route' => 'promotions.rules.index', 'route_params' => ['promotion_type' => 'branch_discount'], 'sort_order' => 181, 'category' => 'Sales & Marketing', 'enabled' => true, 'visible_in_sidebar' => true, 'roles' => $promotionRoles, 'badge' => null, 'license_key' => null, 'parent_id' => 'promotions',
        ],
        'promotion-simulator' => [
            'name' => 'Promotion Simulator', 'description' => 'Test cart outcomes before POS billing exists.', 'icon' => 'analytics', 'route' => 'promotions.simulator.index', 'route_params' => [], 'sort_order' => 182, 'category' => 'Sales & Marketing', 'enabled' => true, 'visible_in_sidebar' => true, 'roles' => $promotionManagementRoles, 'badge' => ['label' => 'Test', 'tone' => 'success'], 'license_key' => null, 'parent_id' => 'promotions',
        ],
        'promotion-usage' => [
            'name' => 'Promotion Usage', 'description' => 'Promotion and coupon usage history foundation.', 'icon' => 'analytics', 'route' => 'promotions.usage.index', 'route_params' => [], 'sort_order' => 183, 'category' => 'Sales & Marketing', 'enabled' => true, 'visible_in_sidebar' => true, 'roles' => $promotionManagementRoles, 'badge' => null, 'license_key' => null, 'parent_id' => 'promotions',
        ],
        'promotion-settings' => [
            'name' => 'Promotion Settings', 'description' => 'Stacking, approval, and discount cap controls.', 'icon' => 'settings', 'route' => 'promotions.settings.index', 'route_params' => [], 'sort_order' => 184, 'category' => 'Sales & Marketing', 'enabled' => true, 'visible_in_sidebar' => true, 'roles' => $promotionManagementRoles, 'badge' => null, 'license_key' => null, 'parent_id' => 'promotions',
        ],
        'inventory' => [
            'name' => 'Inventory',
            'description' => 'Product catalog, stock availability, barcode labels, and reorder operations.',
            'icon' => 'package',
            'route' => 'inventory.dashboard',
            'route_params' => [],
            'sort_order' => 200,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $inventoryRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'inventory-dashboard' => [
            'name' => 'Inventory Dashboard',
            'description' => 'Inventory value, stock health, low stock, and operating shortcuts.',
            'icon' => 'dashboard',
            'route' => 'inventory.dashboard',
            'route_params' => [],
            'sort_order' => 201,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $inventoryRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'inventory',
        ],
        'inventory-decision-dashboard' => [
            'name' => 'Decision Dashboard',
            'description' => 'Product-wise stock risk, sales-day coverage, reorder recommendations, and AI-ready decision signals.',
            'icon' => 'analytics',
            'route' => 'inventory.decision-dashboard',
            'route_params' => [],
            'sort_order' => 202,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => ['label' => 'New', 'tone' => 'info'],
            'license_key' => null,
            'parent_id' => 'inventory',
        ],
        'products' => [
            'name' => 'Products',
            'description' => 'Tenant-scoped product catalog with SKU, barcode, pricing, tax, and stock flags.',
            'icon' => 'products',
            'route' => 'inventory.products.index',
            'route_params' => [],
            'sort_order' => 210,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $inventoryRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'inventory',
        ],
        'inventory-categories' => [
            'name' => 'Categories',
            'description' => 'Product hierarchy and category merchandising foundation.',
            'icon' => 'folders',
            'route' => 'inventory.categories.index',
            'route_params' => [],
            'sort_order' => 211,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'inventory',
        ],
        'inventory-brands' => [
            'name' => 'Brands',
            'description' => 'Brand master data for catalog and labels.',
            'icon' => 'tag',
            'route' => 'inventory.brands.index',
            'route_params' => [],
            'sort_order' => 212,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'inventory',
        ],
        'inventory-units' => [
            'name' => 'Units',
            'description' => 'Unit of measure and decimal quantity settings.',
            'icon' => 'ruler',
            'route' => 'inventory.units.index',
            'route_params' => [],
            'sort_order' => 213,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'inventory',
        ],
        'inventory-tax-rates' => [
            'name' => 'Tax Rates',
            'description' => 'GST and tax master data for product pricing.',
            'icon' => 'percent',
            'route' => 'inventory.tax-rates.index',
            'route_params' => [],
            'sort_order' => 214,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'inventory',
        ],
        'inventory-variants' => [
            'name' => 'Variants',
            'description' => 'Variant product foundation through attributes, values, SKU, and barcode mapping.',
            'icon' => 'layers',
            'route' => 'inventory.products.index',
            'route_params' => ['type' => 'variant'],
            'sort_order' => 215,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'inventory',
        ],
        'inventory-barcodes' => [
            'name' => 'Barcodes',
            'description' => 'Barcode label templates and print batch foundation.',
            'icon' => 'barcode',
            'route' => 'inventory.barcode-templates.index',
            'route_params' => [],
            'sort_order' => 216,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'inventory',
        ],
        'inventory-barcode-labels' => [
            'name' => 'Barcode Labels',
            'description' => 'Prepared label print batches with preview-ready label data.',
            'icon' => 'printer',
            'route' => 'inventory.barcode-batches.index',
            'route_params' => [],
            'sort_order' => 217,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'inventory',
        ],
        'inventory-warehouses' => [
            'name' => 'Warehouses',
            'description' => 'Warehouses and branch-linked stock holding points.',
            'icon' => 'warehouse',
            'route' => 'inventory.warehouses.index',
            'route_params' => [],
            'sort_order' => 218,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'inventory',
        ],
        'inventory-stock-locations' => [
            'name' => 'Stock Locations',
            'description' => 'Bins, racks, shelves, and stock locations under warehouses.',
            'icon' => 'map-pin',
            'route' => 'inventory.locations.index',
            'route_params' => [],
            'sort_order' => 219,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'inventory',
        ],
        'inventory-stock-ledger' => [
            'name' => 'Stock Ledger',
            'description' => 'Auditable stock movements by product, warehouse, and date.',
            'icon' => 'audit',
            'route' => 'inventory.stock.ledger',
            'route_params' => [],
            'sort_order' => 220,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'inventory',
        ],
        'inventory-stock-adjustments' => [
            'name' => 'Stock Adjustments',
            'description' => 'Draft and approved adjustment workflow with ledger writes.',
            'icon' => 'activity',
            'route' => 'inventory.adjustments.index',
            'route_params' => [],
            'sort_order' => 221,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'inventory',
        ],
        'inventory-opening-stock' => [
            'name' => 'Opening Stock',
            'description' => 'Initial stock entry with duplicate prevention.',
            'icon' => 'boxes',
            'route' => 'inventory.opening-stock.create',
            'route_params' => [],
            'sort_order' => 222,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'inventory',
        ],
        'inventory-low-stock' => [
            'name' => 'Low Stock',
            'description' => 'Stock health filters for low and out-of-stock products.',
            'icon' => 'bell',
            'route' => 'inventory.dashboard',
            'route_params' => ['filter' => 'low-stock'],
            'sort_order' => 223,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => ['label' => 'Live', 'tone' => 'warning'],
            'license_key' => null,
            'parent_id' => 'inventory',
        ],
        'inventory-reorder-suggestions' => [
            'name' => 'Reorder Suggestions',
            'description' => 'Rules, reorder points, stockout risk, and suggestion review.',
            'icon' => 'calendar',
            'route' => 'inventory.reorder.index',
            'route_params' => [],
            'sort_order' => 224,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'inventory',
        ],
        'inventory-sales-channels' => [
            'name' => 'Sales Channels',
            'description' => 'Internal omnichannel sales channel records.',
            'icon' => 'server',
            'route' => 'inventory.channels.index',
            'route_params' => [],
            'sort_order' => 225,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'inventory',
        ],
        'inventory-channel-mapping' => [
            'name' => 'Channel Product Mapping',
            'description' => 'Per-channel SKU, price, stock buffer, and sync state foundation.',
            'icon' => 'layout',
            'route' => 'inventory.channel-mappings.index',
            'route_params' => [],
            'sort_order' => 226,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'inventory',
        ],
        'inventory-settings' => [
            'name' => 'Inventory Settings',
            'description' => 'Costing, low stock, barcode, and negative stock defaults.',
            'icon' => 'settings',
            'route' => 'inventory.settings.index',
            'route_params' => [],
            'sort_order' => 227,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'inventory',
        ],
        'purchases' => [
            'name' => 'Purchases',
            'description' => 'Supplier, purchase request, purchase order, receiving, and return command center.',
            'icon' => 'shopping-bag',
            'route' => 'purchases.dashboard',
            'route_params' => [],
            'sort_order' => 228,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => 'future_purchase_module',
            'parent_id' => null,
        ],
        'purchase-dashboard' => [
            'name' => 'Purchase Dashboard',
            'description' => 'Purchase value, open approvals, recent orders, and reorder conversion shortcuts.',
            'icon' => 'dashboard',
            'route' => 'purchases.dashboard',
            'route_params' => [],
            'sort_order' => 229,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'purchases',
        ],
        'supplier-dashboard' => [
            'name' => 'Supplier Dashboard',
            'description' => 'Supplier performance, scoring, product coverage, receipts, and returns.',
            'icon' => 'truck',
            'route' => 'purchases.supplier-dashboard',
            'route_params' => [],
            'sort_order' => 230,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'purchases',
        ],
        'suppliers' => [
            'name' => 'Suppliers',
            'description' => 'Supplier records, contacts, addresses, tax details, and operating notes.',
            'icon' => 'suppliers',
            'route' => 'purchases.suppliers.index',
            'route_params' => [],
            'sort_order' => 231,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'purchases',
        ],
        'supplier-contacts' => [
            'name' => 'Supplier Contacts',
            'description' => 'Named supplier contact and WhatsApp-ready communication records.',
            'icon' => 'contacts',
            'route' => 'purchases.suppliers.index',
            'route_params' => ['focus' => 'contacts'],
            'sort_order' => 232,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'purchases',
        ],
        'supplier-products' => [
            'name' => 'Supplier Products',
            'description' => 'Product-supplier mapping, preferred supplier, price, MOQ, and lead-time foundation.',
            'icon' => 'products',
            'route' => 'purchases.suppliers.index',
            'route_params' => ['focus' => 'products'],
            'sort_order' => 233,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'purchases',
        ],
        'supplier-ratings' => [
            'name' => 'Supplier Ratings',
            'description' => 'Rule-based supplier scoring snapshots without fake POS sales inputs.',
            'icon' => 'analytics',
            'route' => 'purchases.supplier-dashboard',
            'route_params' => ['focus' => 'ratings'],
            'sort_order' => 234,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'purchases',
        ],
        'purchase-requests' => [
            'name' => 'Purchase Requests',
            'description' => 'Manual and reorder-generated purchase request workflow.',
            'icon' => 'orders',
            'route' => 'purchases.requests.index',
            'route_params' => [],
            'sort_order' => 235,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'purchases',
        ],
        'purchase-orders' => [
            'name' => 'Purchase Orders',
            'description' => 'Purchase order approval, send, cancellation, and print-ready workflow.',
            'icon' => 'shopping-bag',
            'route' => 'purchases.orders.index',
            'route_params' => [],
            'sort_order' => 236,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'purchases',
        ],
        'goods-receipts' => [
            'name' => 'Goods Receipts',
            'description' => 'GRN receiving that posts purchase stock movements.',
            'icon' => 'truck',
            'route' => 'purchases.grn.index',
            'route_params' => [],
            'sort_order' => 237,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'purchases',
        ],
        'purchase-returns' => [
            'name' => 'Purchase Returns',
            'description' => 'Supplier return approval and stock reversal workflow.',
            'icon' => 'returns',
            'route' => 'purchases.returns.index',
            'route_params' => [],
            'sort_order' => 238,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'purchases',
        ],
        'pending-approvals' => [
            'name' => 'Pending Approvals',
            'description' => 'Purchase requests, orders, and returns waiting for manager action.',
            'icon' => 'bell',
            'route' => 'purchases.dashboard',
            'route_params' => ['focus' => 'approvals'],
            'sort_order' => 239,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => ['label' => 'Review', 'tone' => 'warning'],
            'license_key' => null,
            'parent_id' => 'purchases',
        ],
        'reorder-to-purchase' => [
            'name' => 'Reorder to Purchase',
            'description' => 'Convert inventory reorder suggestions into purchase requests.',
            'icon' => 'calendar',
            'route' => 'inventory.reorder.index',
            'route_params' => ['focus' => 'purchase'],
            'sort_order' => 240,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'purchases',
        ],
        'purchase-settings' => [
            'name' => 'Purchase Settings',
            'description' => 'Purchase numbering, approvals, tax behavior, and receiving controls.',
            'icon' => 'settings',
            'route' => 'purchases.settings.index',
            'route_params' => [],
            'sort_order' => 241,
            'category' => 'Retail Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'purchases',
        ],
        'projects' => [
            'name' => 'Projects',
            'description' => 'Project tracking module foundation.',
            'icon' => 'projects',
            'route' => 'modules.show',
            'route_params' => ['module' => 'projects'],
            'sort_order' => 240,
            'category' => 'Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'support' => [
            'name' => 'Support',
            'description' => 'Support desk module foundation.',
            'icon' => 'support',
            'route' => 'modules.show',
            'route_params' => ['module' => 'support'],
            'sort_order' => 250,
            'category' => 'Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $allRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'finance' => [
            'name' => 'Finance',
            'description' => 'Finance module foundation.',
            'icon' => 'finance',
            'route' => 'modules.show',
            'route_params' => ['module' => 'finance'],
            'sort_order' => 300,
            'category' => 'Finance',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'expenses' => [
            'name' => 'Expenses',
            'description' => 'Expense tracking module foundation.',
            'icon' => 'expenses',
            'route' => 'modules.show',
            'route_params' => ['module' => 'expenses'],
            'sort_order' => 310,
            'category' => 'Finance',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'employees' => [
            'name' => 'Employees',
            'description' => 'Employee records module foundation.',
            'icon' => 'employees',
            'route' => 'modules.show',
            'route_params' => ['module' => 'employees'],
            'sort_order' => 400,
            'category' => 'People',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'hr' => [
            'name' => 'HR',
            'description' => 'Human resources module foundation.',
            'icon' => 'hr',
            'route' => 'modules.show',
            'route_params' => ['module' => 'hr'],
            'sort_order' => 410,
            'category' => 'People',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'payroll' => [
            'name' => 'Payroll',
            'description' => 'Payroll module foundation.',
            'icon' => 'payroll',
            'route' => 'modules.show',
            'route_params' => ['module' => 'payroll'],
            'sort_order' => 420,
            'category' => 'People',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $administratorRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'marketing' => [
            'name' => 'Marketing',
            'description' => 'Marketing campaign module foundation.',
            'icon' => 'marketing',
            'route' => 'modules.show',
            'route_params' => ['module' => 'marketing'],
            'sort_order' => 500,
            'category' => 'Growth',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'whatsapp' => [
            'name' => 'WhatsApp',
            'description' => 'WhatsApp communication module foundation.',
            'icon' => 'whatsapp',
            'route' => 'modules.show',
            'route_params' => ['module' => 'whatsapp'],
            'sort_order' => 510,
            'category' => 'Growth',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'cms' => [
            'name' => 'CMS',
            'description' => 'Enterprise website builder, content library, SEO, and brand management.',
            'icon' => 'layout',
            'route' => 'cms.dashboard',
            'route_params' => [],
            'sort_order' => 520,
            'category' => 'Content Management',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => ['label' => 'Pro', 'tone' => 'info'],
            'license_key' => null,
            'parent_id' => null,
        ],
        'cms-control-center' => [
            'name' => 'Website Control Center', 'description' => 'CMS readiness, content health, and publishing overview.', 'icon' => 'dashboard', 'route' => 'cms.dashboard', 'route_params' => [], 'sort_order' => 521, 'category' => 'Content Management', 'enabled' => true, 'visible_in_sidebar' => true, 'roles' => $managementRoles, 'badge' => null, 'license_key' => null, 'parent_id' => 'cms',
        ],
        'cms-branding' => [
            'name' => 'Website Settings', 'description' => 'Brand identity, header settings, contact details, and analytics.', 'icon' => 'layout', 'route' => 'website.settings.index', 'route_params' => [], 'sort_order' => 522, 'category' => 'Content Management', 'enabled' => true, 'visible_in_sidebar' => true, 'roles' => $managementRoles, 'badge' => null, 'license_key' => null, 'parent_id' => 'cms',
        ],
        'cms-theme' => [
            'name' => 'Theme', 'description' => 'Website theme tokens and visual presentation settings.', 'icon' => 'settings', 'route' => 'cms.theme.index', 'route_params' => [], 'sort_order' => 523, 'category' => 'Content Management', 'enabled' => true, 'visible_in_sidebar' => true, 'roles' => $managementRoles, 'badge' => null, 'license_key' => null, 'parent_id' => 'cms',
        ],
        'cms-pages' => [
            'name' => 'Website Pages', 'description' => 'Marketing, product, solution, industry, and landing pages.', 'icon' => 'cms', 'route' => 'cms.pages.index', 'route_params' => [], 'sort_order' => 524, 'category' => 'Content Management', 'enabled' => true, 'visible_in_sidebar' => true, 'roles' => $managementRoles, 'badge' => null, 'license_key' => null, 'parent_id' => 'cms',
        ],
        'cms-content-library' => [
            'name' => 'Content Library', 'description' => 'Case studies, testimonials, client logos, trust metrics, FAQs, and CTAs.', 'icon' => 'blog', 'route' => 'cms.case-studies.index', 'route_params' => [], 'sort_order' => 525, 'category' => 'Content Management', 'enabled' => true, 'visible_in_sidebar' => true, 'roles' => $managementRoles, 'badge' => null, 'license_key' => null, 'parent_id' => 'cms',
        ],
        'cms-seo-center' => [
            'name' => 'SEO Center', 'description' => 'Website SEO defaults, redirects, sitemap, robots, and verification settings.', 'icon' => 'seo', 'route' => 'cms.seo.index', 'route_params' => [], 'sort_order' => 526, 'category' => 'Content Management', 'enabled' => true, 'visible_in_sidebar' => true, 'roles' => $managementRoles, 'badge' => null, 'license_key' => null, 'parent_id' => 'cms',
        ],
        'blog' => [
            'name' => 'Blog',
            'description' => 'Blog content module foundation retained from Phase 1 navigation.',
            'icon' => 'blog',
            'route' => 'modules.show',
            'route_params' => ['module' => 'blog'],
            'sort_order' => 525,
            'category' => 'Growth',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'website-cms' => [
            'name' => 'Website',
            'description' => 'Website pages, navigation, settings, and SEO publishing foundation.',
            'icon' => 'layout',
            'route' => 'website.pages.index',
            'route_params' => [],
            'sort_order' => 526,
            'category' => 'Content Management',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'website-pages' => [
            'name' => 'Pages', 'description' => 'Manage public website pages and structured sections.', 'icon' => 'cms', 'route' => 'website.pages.index', 'route_params' => [], 'sort_order' => 527, 'category' => 'Content Management', 'enabled' => true, 'visible_in_sidebar' => true, 'roles' => $managementRoles, 'badge' => null, 'license_key' => null, 'parent_id' => 'website-cms',
        ],
        'website-navigation' => [
            'name' => 'Navigation', 'description' => 'Manage header, footer, and mobile website menus.', 'icon' => 'settings', 'route' => 'website.navigation.index', 'route_params' => [], 'sort_order' => 528, 'category' => 'Content Management', 'enabled' => true, 'visible_in_sidebar' => true, 'roles' => $managementRoles, 'badge' => null, 'license_key' => null, 'parent_id' => 'website-cms',
        ],
        'website-settings' => [
            'name' => 'Settings', 'description' => 'Manage global website identity, contact, social, and analytics settings.', 'icon' => 'settings', 'route' => 'website.settings.index', 'route_params' => [], 'sort_order' => 529, 'category' => 'Content Management', 'enabled' => true, 'visible_in_sidebar' => true, 'roles' => $managementRoles, 'badge' => null, 'license_key' => null, 'parent_id' => 'website-cms',
        ],
        'seo' => [
            'name' => 'SEO',
            'description' => 'Search optimization module foundation.',
            'icon' => 'seo',
            'route' => 'modules.show',
            'route_params' => ['module' => 'seo'],
            'sort_order' => 530,
            'category' => 'Growth',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'reports' => [
            'name' => 'Reports',
            'description' => 'Report center module foundation.',
            'icon' => 'reports',
            'route' => 'modules.show',
            'route_params' => ['module' => 'reports'],
            'sort_order' => 600,
            'category' => 'Insights',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'analytics' => [
            'name' => 'Analytics',
            'description' => 'Analytics module foundation.',
            'icon' => 'analytics',
            'route' => 'modules.show',
            'route_params' => ['module' => 'analytics'],
            'sort_order' => 610,
            'category' => 'Insights',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'ai-assistant' => [
            'name' => 'AI Assistant',
            'description' => 'AI assistant module foundation.',
            'icon' => 'ai',
            'route' => 'modules.show',
            'route_params' => ['module' => 'ai-assistant'],
            'sort_order' => 620,
            'category' => 'Insights',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => ['label' => 'Beta', 'tone' => 'info'],
            'license_key' => null,
            'parent_id' => null,
        ],
        'company' => [
            'name' => 'Company',
            'description' => 'Company profile module foundation.',
            'icon' => 'company',
            'route' => 'modules.show',
            'route_params' => ['module' => 'company'],
            'sort_order' => 700,
            'category' => 'Administration',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'branches' => [
            'name' => 'Branches',
            'description' => 'Branch management module foundation.',
            'icon' => 'branches',
            'route' => 'modules.show',
            'route_params' => ['module' => 'branches'],
            'sort_order' => 710,
            'category' => 'Administration',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'users' => [
            'name' => 'Users',
            'description' => 'User administration module foundation.',
            'icon' => 'users',
            'route' => 'modules.show',
            'route_params' => ['module' => 'users'],
            'sort_order' => 720,
            'category' => 'Administration',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $administratorRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'roles' => [
            'name' => 'Roles',
            'description' => 'Role and permission module foundation.',
            'icon' => 'roles',
            'route' => 'modules.show',
            'route_params' => ['module' => 'roles'],
            'sort_order' => 730,
            'category' => 'Administration',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $administratorRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'settings' => [
            'name' => 'Settings',
            'description' => 'Command Center settings foundation.',
            'icon' => 'settings',
            'route' => 'settings.show',
            'route_params' => ['section' => 'general'],
            'sort_order' => 740,
            'category' => 'Administration',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'integrations' => [
            'name' => 'Integrations',
            'description' => 'Manage secure third-party connections for the Command Center.',
            'icon' => 'settings',
            'route' => 'integrations.google.index',
            'route_params' => [],
            'sort_order' => 741,
            'category' => 'Administration',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $administratorRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'operations' => [
            'name' => 'Operations Monitor',
            'description' => 'System health, queue, scheduler, and operational telemetry.',
            'icon' => 'activity',
            'route' => 'operations.dashboard',
            'route_params' => [],
            'sort_order' => 742,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $operationsRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'operations-health' => [
            'name' => 'System Health',
            'description' => 'Application, infrastructure, and configuration health checks.',
            'icon' => 'activity',
            'route' => 'operations.health.index',
            'route_params' => [],
            'sort_order' => 743,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $operationsRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'operations',
        ],
        'operations-queue' => [
            'name' => 'Queue Monitor',
            'description' => 'Queue connection, pending jobs, and queue snapshots.',
            'icon' => 'server',
            'route' => 'operations.queue.index',
            'route_params' => [],
            'sort_order' => 744,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $operationsRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'operations',
        ],
        'operations-failed-jobs' => [
            'name' => 'Failed Jobs',
            'description' => 'Failed queue job inspection and admin recovery actions.',
            'icon' => 'audit',
            'route' => 'operations.failed-jobs.index',
            'route_params' => [],
            'sort_order' => 745,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $operationsRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'operations',
        ],
        'operations-schedule' => [
            'name' => 'Schedule Monitor',
            'description' => 'Scheduled command definitions and last tracked runs.',
            'icon' => 'calendar',
            'route' => 'operations.schedule.index',
            'route_params' => [],
            'sort_order' => 746,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $operationsRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'operations',
        ],
        'operations-notification-deliveries' => [
            'name' => 'Notification Deliveries',
            'description' => 'Notification delivery monitor from the Notification Center.',
            'icon' => 'bell',
            'route' => 'notifications.deliveries.index',
            'route_params' => [],
            'sort_order' => 747,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $operationsRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'operations',
        ],
        'operations-webhooks' => [
            'name' => 'Webhook Deliveries',
            'description' => 'Outbound webhook endpoint and delivery monitor.',
            'icon' => 'server',
            'route' => 'notifications.webhooks.index',
            'route_params' => [],
            'sort_order' => 748,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $operationsRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'operations',
        ],
        'operations-event-logs' => [
            'name' => 'Event Logs',
            'description' => 'Domain event monitor from the Event Center.',
            'icon' => 'audit',
            'route' => 'notifications.events.index',
            'route_params' => [],
            'sort_order' => 749,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $operationsRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'operations',
        ],
        'operations-application' => [
            'name' => 'Application Info',
            'description' => 'Runtime, version, driver, and deployment metadata.',
            'icon' => 'settings',
            'route' => 'operations.application.index',
            'route_params' => [],
            'sort_order' => 750,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $operationsRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'operations',
        ],
        'notifications' => [
            'name' => 'Notification Center',
            'description' => 'Shared event, notification, delivery, and webhook foundation.',
            'icon' => 'bell',
            'route' => 'notifications.index',
            'route_params' => [],
            'sort_order' => 745,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $notificationRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'notification-inbox' => [
            'name' => 'Notifications',
            'description' => 'Personal in-app notifications inbox.',
            'icon' => 'bell',
            'route' => 'notifications.index',
            'route_params' => [],
            'sort_order' => 746,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $notificationRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'notifications',
        ],
        'notification-preferences' => [
            'name' => 'Notification Preferences',
            'description' => 'Personal event notification channel preferences.',
            'icon' => 'settings',
            'route' => 'notifications.preferences.index',
            'route_params' => [],
            'sort_order' => 747,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $notificationRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'notifications',
        ],
        'notification-event-log' => [
            'name' => 'Event Log',
            'description' => 'Operational domain event log.',
            'icon' => 'audit',
            'route' => 'notifications.events.index',
            'route_params' => [],
            'sort_order' => 748,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'notifications',
        ],
        'notification-webhooks' => [
            'name' => 'Webhooks',
            'description' => 'Outbound webhook endpoints and subscriptions.',
            'icon' => 'settings',
            'route' => 'notifications.webhooks.index',
            'route_params' => [],
            'sort_order' => 749,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'notifications',
        ],
        'notification-delivery-log' => [
            'name' => 'Delivery Log',
            'description' => 'Notification and webhook delivery history.',
            'icon' => 'audit',
            'route' => 'notifications.deliveries.index',
            'route_params' => [],
            'sort_order' => 750,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'notifications',
        ],
        'audit-logs' => [
            'name' => 'Audit Logs',
            'description' => 'Audit activity module foundation.',
            'icon' => 'audit',
            'route' => 'modules.show',
            'route_params' => ['module' => 'audit-logs'],
            'sort_order' => 760,
            'category' => 'Administration',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $administratorRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
    ],
];
