<?php

$allRoles = ['administrator', 'manager', 'sales', 'staff'];
$managementRoles = ['administrator', 'manager'];
$administratorRoles = ['administrator'];
$crmRoles = ['administrator', 'manager', 'sales'];
$notificationRoles = ['administrator', 'manager', 'sales'];
$operationsRoles = ['administrator', 'manager'];

return [
    'modules' => [
        'dashboard' => [
            'name' => 'Dashboard',
            'description' => 'Executive operating overview for the Command Center.',
            'icon' => 'dashboard',
            'route' => 'dashboard',
            'route_params' => [],
            'sort_order' => 10,
            'category' => 'Overview',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $allRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'crm' => [
            'name' => 'CRM',
            'description' => 'Enterprise sales and relationship command center.',
            'icon' => 'crm',
            'route' => 'crm.dashboard',
            'route_params' => [],
            'sort_order' => 100,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $crmRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'crm-dashboard' => [
            'name' => 'CRM Dashboard',
            'description' => 'Pipeline, activity, and lead health metrics.',
            'icon' => 'dashboard',
            'route' => 'crm.dashboard',
            'route_params' => [],
            'sort_order' => 101,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $crmRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'crm',
        ],
        'contacts' => [
            'name' => 'Contacts',
            'description' => 'People and decision makers linked to CRM accounts.',
            'icon' => 'contacts',
            'route' => 'crm.contacts.index',
            'route_params' => [],
            'sort_order' => 110,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $crmRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'crm',
        ],
        'leads' => [
            'name' => 'Leads',
            'description' => 'Qualified opportunities and follow-up lifecycle.',
            'icon' => 'leads',
            'route' => 'crm.leads.index',
            'route_params' => [],
            'sort_order' => 120,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $crmRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'crm',
        ],
        'crm-companies' => [
            'name' => 'Companies',
            'description' => 'CRM account records, owners, timelines, and related leads.',
            'icon' => 'company',
            'route' => 'crm.companies.index',
            'route_params' => [],
            'sort_order' => 125,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $crmRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'crm',
        ],
        'crm-pipeline' => [
            'name' => 'Pipeline',
            'description' => 'Server-rendered sales pipeline by status.',
            'icon' => 'sales',
            'route' => 'crm.pipeline.index',
            'route_params' => [],
            'sort_order' => 126,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $crmRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'crm',
        ],
        'crm-activities' => [
            'name' => 'Activities',
            'description' => 'Calls, meetings, emails, WhatsApp tasks, and follow-ups.',
            'icon' => 'audit',
            'route' => 'crm.activities.index',
            'route_params' => [],
            'sort_order' => 127,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $crmRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'crm',
        ],
        'crm-follow-ups' => [
            'name' => 'Follow-ups',
            'description' => 'Upcoming and overdue follow-up queue.',
            'icon' => 'bell',
            'route' => 'crm.followups.index',
            'route_params' => [],
            'sort_order' => 128,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $crmRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'crm',
        ],
        'sales' => [
            'name' => 'Sales',
            'description' => 'Sales activity module foundation.',
            'icon' => 'sales',
            'route' => 'modules.show',
            'route_params' => ['module' => 'sales'],
            'sort_order' => 130,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $allRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'pos' => [
            'name' => 'POS',
            'description' => 'Point-of-sale module foundation.',
            'icon' => 'pos',
            'route' => 'modules.show',
            'route_params' => ['module' => 'pos'],
            'sort_order' => 140,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $allRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'customers' => [
            'name' => 'Customers',
            'description' => 'Customer records and retail history foundation.',
            'icon' => 'customers',
            'route' => 'modules.show',
            'route_params' => ['module' => 'customers'],
            'sort_order' => 150,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $allRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'orders' => [
            'name' => 'Orders',
            'description' => 'Order management module foundation.',
            'icon' => 'orders',
            'route' => 'modules.show',
            'route_params' => ['module' => 'orders'],
            'sort_order' => 160,
            'category' => 'Sales & CRM',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $allRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'inventory' => [
            'name' => 'Inventory',
            'description' => 'Stock and availability module foundation.',
            'icon' => 'inventory',
            'route' => 'modules.show',
            'route_params' => ['module' => 'inventory'],
            'sort_order' => 200,
            'category' => 'Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $allRoles,
            'badge' => ['label' => '8', 'tone' => 'warning'],
            'license_key' => null,
            'parent_id' => null,
        ],
        'products' => [
            'name' => 'Products',
            'description' => 'Product catalog module foundation.',
            'icon' => 'products',
            'route' => 'modules.show',
            'route_params' => ['module' => 'products'],
            'sort_order' => 210,
            'category' => 'Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $allRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'purchases' => [
            'name' => 'Purchases',
            'description' => 'Purchase workflow module foundation.',
            'icon' => 'purchases',
            'route' => 'modules.show',
            'route_params' => ['module' => 'purchases'],
            'sort_order' => 220,
            'category' => 'Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'suppliers' => [
            'name' => 'Suppliers',
            'description' => 'Supplier directory module foundation.',
            'icon' => 'suppliers',
            'route' => 'modules.show',
            'route_params' => ['module' => 'suppliers'],
            'sort_order' => 230,
            'category' => 'Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'projects' => [
            'name' => 'Projects',
            'description' => 'Project tracking module foundation.',
            'icon' => 'projects',
            'route' => 'modules.show',
            'route_params' => ['module' => 'projects'],
            'sort_order' => 240,
            'category' => 'Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'support' => [
            'name' => 'Support',
            'description' => 'Support desk module foundation.',
            'icon' => 'support',
            'route' => 'modules.show',
            'route_params' => ['module' => 'support'],
            'sort_order' => 250,
            'category' => 'Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $allRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'finance' => [
            'name' => 'Finance',
            'description' => 'Finance module foundation.',
            'icon' => 'finance',
            'route' => 'modules.show',
            'route_params' => ['module' => 'finance'],
            'sort_order' => 300,
            'category' => 'Finance',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'expenses' => [
            'name' => 'Expenses',
            'description' => 'Expense tracking module foundation.',
            'icon' => 'expenses',
            'route' => 'modules.show',
            'route_params' => ['module' => 'expenses'],
            'sort_order' => 310,
            'category' => 'Finance',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'employees' => [
            'name' => 'Employees',
            'description' => 'Employee records module foundation.',
            'icon' => 'employees',
            'route' => 'modules.show',
            'route_params' => ['module' => 'employees'],
            'sort_order' => 400,
            'category' => 'People',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'hr' => [
            'name' => 'HR',
            'description' => 'Human resources module foundation.',
            'icon' => 'hr',
            'route' => 'modules.show',
            'route_params' => ['module' => 'hr'],
            'sort_order' => 410,
            'category' => 'People',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'payroll' => [
            'name' => 'Payroll',
            'description' => 'Payroll module foundation.',
            'icon' => 'payroll',
            'route' => 'modules.show',
            'route_params' => ['module' => 'payroll'],
            'sort_order' => 420,
            'category' => 'People',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $administratorRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'marketing' => [
            'name' => 'Marketing',
            'description' => 'Marketing campaign module foundation.',
            'icon' => 'marketing',
            'route' => 'modules.show',
            'route_params' => ['module' => 'marketing'],
            'sort_order' => 500,
            'category' => 'Growth',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'whatsapp' => [
            'name' => 'WhatsApp',
            'description' => 'WhatsApp communication module foundation.',
            'icon' => 'whatsapp',
            'route' => 'modules.show',
            'route_params' => ['module' => 'whatsapp'],
            'sort_order' => 510,
            'category' => 'Growth',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'cms' => [
            'name' => 'CMS',
            'description' => 'Enterprise website content management foundation.',
            'icon' => 'layout',
            'route' => 'cms.dashboard',
            'route_params' => [],
            'sort_order' => 520,
            'category' => 'Content Management',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'blog' => [
            'name' => 'Blog',
            'description' => 'Blog content module foundation retained from Phase 1 navigation.',
            'icon' => 'blog',
            'route' => 'modules.show',
            'route_params' => ['module' => 'blog'],
            'sort_order' => 525,
            'category' => 'Growth',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'website-cms' => [
            'name' => 'Website CMS',
            'description' => 'Legacy Phase 1 CMS module route retained for compatibility.',
            'icon' => 'cms',
            'route' => 'modules.show',
            'route_params' => ['module' => 'website-cms'],
            'sort_order' => 526,
            'category' => 'Growth',
            'enabled' => true,
            'visible_in_sidebar' => false,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'seo' => [
            'name' => 'SEO',
            'description' => 'Search optimization module foundation.',
            'icon' => 'seo',
            'route' => 'modules.show',
            'route_params' => ['module' => 'seo'],
            'sort_order' => 530,
            'category' => 'Growth',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'reports' => [
            'name' => 'Reports',
            'description' => 'Report center module foundation.',
            'icon' => 'reports',
            'route' => 'modules.show',
            'route_params' => ['module' => 'reports'],
            'sort_order' => 600,
            'category' => 'Insights',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'analytics' => [
            'name' => 'Analytics',
            'description' => 'Analytics module foundation.',
            'icon' => 'analytics',
            'route' => 'modules.show',
            'route_params' => ['module' => 'analytics'],
            'sort_order' => 610,
            'category' => 'Insights',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'ai-assistant' => [
            'name' => 'AI Assistant',
            'description' => 'AI assistant module foundation.',
            'icon' => 'ai',
            'route' => 'modules.show',
            'route_params' => ['module' => 'ai-assistant'],
            'sort_order' => 620,
            'category' => 'Insights',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => ['label' => 'Beta', 'tone' => 'info'],
            'license_key' => null,
            'parent_id' => null,
        ],
        'company' => [
            'name' => 'Company',
            'description' => 'Company profile module foundation.',
            'icon' => 'company',
            'route' => 'modules.show',
            'route_params' => ['module' => 'company'],
            'sort_order' => 700,
            'category' => 'Administration',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'branches' => [
            'name' => 'Branches',
            'description' => 'Branch management module foundation.',
            'icon' => 'branches',
            'route' => 'modules.show',
            'route_params' => ['module' => 'branches'],
            'sort_order' => 710,
            'category' => 'Administration',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'users' => [
            'name' => 'Users',
            'description' => 'User administration module foundation.',
            'icon' => 'users',
            'route' => 'modules.show',
            'route_params' => ['module' => 'users'],
            'sort_order' => 720,
            'category' => 'Administration',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $administratorRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'roles' => [
            'name' => 'Roles',
            'description' => 'Role and permission module foundation.',
            'icon' => 'roles',
            'route' => 'modules.show',
            'route_params' => ['module' => 'roles'],
            'sort_order' => 730,
            'category' => 'Administration',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $administratorRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'settings' => [
            'name' => 'Settings',
            'description' => 'Command Center settings foundation.',
            'icon' => 'settings',
            'route' => 'settings.show',
            'route_params' => ['section' => 'general'],
            'sort_order' => 740,
            'category' => 'Administration',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'operations' => [
            'name' => 'Operations Monitor',
            'description' => 'System health, queue, scheduler, and operational telemetry.',
            'icon' => 'activity',
            'route' => 'operations.dashboard',
            'route_params' => [],
            'sort_order' => 742,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $operationsRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'operations-health' => [
            'name' => 'System Health',
            'description' => 'Application, infrastructure, and configuration health checks.',
            'icon' => 'activity',
            'route' => 'operations.health.index',
            'route_params' => [],
            'sort_order' => 743,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $operationsRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'operations',
        ],
        'operations-queue' => [
            'name' => 'Queue Monitor',
            'description' => 'Queue connection, pending jobs, and queue snapshots.',
            'icon' => 'server',
            'route' => 'operations.queue.index',
            'route_params' => [],
            'sort_order' => 744,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $operationsRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'operations',
        ],
        'operations-failed-jobs' => [
            'name' => 'Failed Jobs',
            'description' => 'Failed queue job inspection and admin recovery actions.',
            'icon' => 'audit',
            'route' => 'operations.failed-jobs.index',
            'route_params' => [],
            'sort_order' => 745,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $operationsRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'operations',
        ],
        'operations-schedule' => [
            'name' => 'Schedule Monitor',
            'description' => 'Scheduled command definitions and last tracked runs.',
            'icon' => 'calendar',
            'route' => 'operations.schedule.index',
            'route_params' => [],
            'sort_order' => 746,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $operationsRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'operations',
        ],
        'operations-notification-deliveries' => [
            'name' => 'Notification Deliveries',
            'description' => 'Notification delivery monitor from the Notification Center.',
            'icon' => 'bell',
            'route' => 'notifications.deliveries.index',
            'route_params' => [],
            'sort_order' => 747,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $operationsRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'operations',
        ],
        'operations-webhooks' => [
            'name' => 'Webhook Deliveries',
            'description' => 'Outbound webhook endpoint and delivery monitor.',
            'icon' => 'server',
            'route' => 'notifications.webhooks.index',
            'route_params' => [],
            'sort_order' => 748,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $operationsRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'operations',
        ],
        'operations-event-logs' => [
            'name' => 'Event Logs',
            'description' => 'Domain event monitor from the Event Center.',
            'icon' => 'audit',
            'route' => 'notifications.events.index',
            'route_params' => [],
            'sort_order' => 749,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $operationsRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'operations',
        ],
        'operations-application' => [
            'name' => 'Application Info',
            'description' => 'Runtime, version, driver, and deployment metadata.',
            'icon' => 'settings',
            'route' => 'operations.application.index',
            'route_params' => [],
            'sort_order' => 750,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $operationsRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'operations',
        ],
        'notifications' => [
            'name' => 'Notification Center',
            'description' => 'Shared event, notification, delivery, and webhook foundation.',
            'icon' => 'bell',
            'route' => 'notifications.index',
            'route_params' => [],
            'sort_order' => 745,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $notificationRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
        'notification-inbox' => [
            'name' => 'Notifications',
            'description' => 'Personal in-app notifications inbox.',
            'icon' => 'bell',
            'route' => 'notifications.index',
            'route_params' => [],
            'sort_order' => 746,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $notificationRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'notifications',
        ],
        'notification-preferences' => [
            'name' => 'Notification Preferences',
            'description' => 'Personal event notification channel preferences.',
            'icon' => 'settings',
            'route' => 'notifications.preferences.index',
            'route_params' => [],
            'sort_order' => 747,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $notificationRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'notifications',
        ],
        'notification-event-log' => [
            'name' => 'Event Log',
            'description' => 'Operational domain event log.',
            'icon' => 'audit',
            'route' => 'notifications.events.index',
            'route_params' => [],
            'sort_order' => 748,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'notifications',
        ],
        'notification-webhooks' => [
            'name' => 'Webhooks',
            'description' => 'Outbound webhook endpoints and subscriptions.',
            'icon' => 'settings',
            'route' => 'notifications.webhooks.index',
            'route_params' => [],
            'sort_order' => 749,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'notifications',
        ],
        'notification-delivery-log' => [
            'name' => 'Delivery Log',
            'description' => 'Notification and webhook delivery history.',
            'icon' => 'audit',
            'route' => 'notifications.deliveries.index',
            'route_params' => [],
            'sort_order' => 750,
            'category' => 'System & Operations',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $managementRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => 'notifications',
        ],
        'audit-logs' => [
            'name' => 'Audit Logs',
            'description' => 'Audit activity module foundation.',
            'icon' => 'audit',
            'route' => 'modules.show',
            'route_params' => ['module' => 'audit-logs'],
            'sort_order' => 760,
            'category' => 'Administration',
            'enabled' => true,
            'visible_in_sidebar' => true,
            'roles' => $administratorRoles,
            'badge' => null,
            'license_key' => null,
            'parent_id' => null,
        ],
    ],
];
