@extends('layouts.admin')
@section('title', 'Case Studies') @section('page-title', 'Case Study Manager')
@section('breadcrumbs')<span>/</span><a href="{{ route('cms.dashboard') }}">CMS</a><span>/</span><span>Case Studies</span>@endsection
@section('content')
    <div class="space-y-6">@include('command-center.cms.partials.nav')
        <section class="cms-panel flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="cms-kicker">Content library</p><h1 class="mt-2 text-xl font-semibold text-slate-900">Case studies</h1><p class="mt-2 text-sm leading-6 text-slate-600">Build a clear, section-based story with approved client context and outcome metrics.</p><p class="mt-2 text-xs font-medium text-amber-700">Optional claims should be approved before publication.</p></div><a href="{{ route($routePrefix.'.case-studies.create') }}" class="cms-button-primary">New case study</a></section>
        <form class="cms-panel grid gap-3 md:grid-cols-[1fr_180px_auto]"><input name="search" value="{{ request('search') }}" placeholder="Search title or client"><select name="status"><option value="">All statuses</option>@foreach(['draft', 'published', 'scheduled'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ str($status)->headline() }}</option>@endforeach</select><button class="cms-button-secondary">Filter</button></form>
        <div class="grid gap-5 lg:grid-cols-2 xl:grid-cols-3">@forelse ($studies as $study)<article class="cms-section-card"><div class="flex items-start justify-between gap-3"><div><div class="flex flex-wrap gap-2"><x-status-badge :status="$study->status"/>@if($study->is_featured)<span class="rounded-full bg-amber-100 px-2.5 py-1 text-xs font-semibold text-amber-700">Featured</span>@endif</div><h2 class="mt-4 text-base font-semibold text-slate-900">{{ $study->title }}</h2><p class="mt-1 text-sm text-slate-500">{{ $study->client_name }}{{ $study->industry ? ' · '.$study->industry : '' }}</p></div><span class="grid size-10 place-items-center rounded-xl bg-teal-50 text-sm font-bold text-teal-700">{{ str($study->client_name)->substr(0, 1)->upper() }}</span></div><p class="mt-4 line-clamp-3 text-sm leading-6 text-slate-600">{{ $study->short_summary ?: 'Add a concise approved summary for this case study.' }}</p><div class="mt-5 grid grid-cols-2 gap-2">@forelse(collect($study->metrics ?? [])->take(2) as $label => $value)<div class="rounded-lg bg-slate-50 p-3"><p class="text-xs text-slate-500">{{ str($label)->headline() }}</p><p class="mt-1 font-semibold text-slate-800">{{ $value }}</p></div>@empty<div class="col-span-2 rounded-lg bg-slate-50 p-3 text-sm text-slate-500">Outcome metrics have not been added.</div>@endforelse</div><div class="mt-5 flex flex-wrap items-center gap-3"><a href="{{ route($routePrefix.'.case-studies.edit', $study) }}" class="text-sm font-semibold text-teal-700 hover:text-teal-800">Edit story</a>@if($study->status !== 'published')<form method="POST" action="{{ route($routePrefix.'.case-studies.publish', $study) }}">@csrf<button class="text-sm font-semibold text-emerald-700">Publish</button></form>@else<form method="POST" action="{{ route($routePrefix.'.case-studies.unpublish', $study) }}">@csrf<button class="text-sm font-semibold text-amber-700">Unpublish</button></form>@endif<form method="POST" action="{{ route($routePrefix.'.case-studies.destroy', $study) }}">@csrf @method('DELETE')<button class="text-sm font-semibold text-rose-700" onclick="return confirm('Move this case study to trash?')">Trash</button></form></div></article>@empty<div class="cms-subtle-panel col-span-full py-10 text-center text-sm text-slate-500">No case studies match this view.</div>@endforelse</div><div>{{ $studies->links() }}</div>
    </div>
@endsection
