@extends('layouts.admin')
@section('title','Batch, Serial and Expiry')
@section('page-title','Batch, Serial and Expiry')
@section('content')
@include('command-center.inventory.partials.nav')
<div class="mx-auto max-w-7xl space-y-6">
    @if($errors->any())<div class="rounded-lg border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">{{$errors->first()}}</div>@endif
    <div class="grid grid-cols-2 gap-3 lg:grid-cols-4">@foreach([['Expired',$expiry['expired'],'rose'],['Within 7 days',$expiry['seven'],'amber'],['Within 30 days',$expiry['thirty'],'blue'],['Within 90 days',$expiry['ninety'],'slate']] as [$label,$value,$tone])<a href="{{route('inventory.traceability.index',['expiry'=>$label==='Expired'?'expired':(int)filter_var($label,FILTER_SANITIZE_NUMBER_INT)])}}" class="rounded-lg border border-slate-200 bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md dark:border-slate-800 dark:bg-slate-900"><p class="text-xs font-medium text-slate-500">{{$label}}</p><p class="mt-2 text-2xl font-semibold">{{number_format((float)$value,3)}}</p></a>@endforeach</div>
    <div class="grid gap-6 xl:grid-cols-2">
        @can('inventory.batch.manage')<form method="POST" action="{{route('inventory.traceability.batches.store')}}" class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">@csrf<h2 class="text-lg font-semibold">Add batch</h2><p class="mt-1 text-sm text-slate-500">Assign existing physical stock to a batch. This does not change the stock balance.</p><div class="mt-4 grid gap-3 sm:grid-cols-2"><label class="text-sm font-semibold">Product<select name="product_id" required class="mt-1 min-h-11 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"><option value="">Choose batch-tracked product</option>@foreach($products->where('track_batches',true) as $product)<option value="{{$product->id}}">{{$product->name}} · {{$product->sku}}</option>@endforeach</select></label><label class="text-sm font-semibold">Location<select name="warehouse_id" required class="mt-1 min-h-11 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"><option value="">Choose location</option>@foreach($warehouses as $warehouse)<option value="{{$warehouse->id}}">{{$warehouse->name}}</option>@endforeach</select></label><label class="text-sm font-semibold">Batch number<input name="batch_number" required maxlength="120" class="mt-1 min-h-11 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-semibold">Quantity<input name="quantity_on_hand" required type="number" min="0" step="0.001" class="mt-1 min-h-11 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-semibold">Manufactured <span class="font-normal text-slate-400">optional</span><input name="manufactured_at" type="date" class="mt-1 min-h-11 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-semibold">Expires <span class="font-normal text-slate-400">optional</span><input name="expires_at" type="date" class="mt-1 min-h-11 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label></div><button class="mt-4 min-h-11 rounded-lg bg-slate-950 px-5 text-sm font-semibold text-white dark:bg-teal-300 dark:text-slate-950">Save batch</button></form>@endcan
        @can('inventory.serial.manage')<form method="POST" action="{{route('inventory.traceability.serials.store')}}" class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">@csrf<h2 class="text-lg font-semibold">Add serial numbers</h2><p class="mt-1 text-sm text-slate-500">Paste one serial per line or separate them with commas. Duplicates are rejected.</p><div class="mt-4 grid gap-3 sm:grid-cols-2"><label class="text-sm font-semibold">Product<select name="product_id" required class="mt-1 min-h-11 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"><option value="">Choose serial-tracked product</option>@foreach($products->where('track_serials',true) as $product)<option value="{{$product->id}}">{{$product->name}} · {{$product->sku}}</option>@endforeach</select></label><label class="text-sm font-semibold">Location<select name="warehouse_id" required class="mt-1 min-h-11 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"><option value="">Choose location</option>@foreach($warehouses as $warehouse)<option value="{{$warehouse->id}}">{{$warehouse->name}}</option>@endforeach</select></label></div><label class="mt-3 block text-sm font-semibold">Serial numbers<textarea name="serial_numbers" required rows="6" placeholder="SN-10001&#10;SN-10002" class="mt-1 w-full rounded-lg border-slate-300 font-mono text-sm dark:border-slate-700 dark:bg-slate-950"></textarea></label><button class="mt-4 min-h-11 rounded-lg bg-slate-950 px-5 text-sm font-semibold text-white dark:bg-teal-300 dark:text-slate-950">Add serials</button></form>@endcan
    </div>
    <section class="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="border-b border-slate-200 px-5 py-4 dark:border-slate-800"><h2 class="font-semibold">Batches and expiry</h2></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500 dark:bg-slate-950"><tr><th class="px-5 py-3">Product / Batch</th><th class="px-5 py-3">Location</th><th class="px-5 py-3 text-right">Available</th><th class="px-5 py-3">Expiry</th><th class="px-5 py-3">Status</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($batches as $batch)<tr><td class="px-5 py-4"><p class="font-semibold">{{$batch->product?->name}}</p><p class="text-xs text-slate-500">{{$batch->batch_number}}</p></td><td class="px-5 py-4">{{$batch->warehouse?->name}}</td><td class="px-5 py-4 text-right font-semibold">{{$batch->quantity_available}}</td><td class="px-5 py-4 @if($batch->expires_at?->isPast()) text-rose-700 font-semibold @endif">{{$batch->expires_at?->format('d M Y')??'No expiry'}}</td><td class="px-5 py-4"><span class="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold dark:bg-slate-800">{{$batch->status}}</span></td></tr>@empty<tr><td colspan="5" class="p-10 text-center text-slate-500">No batches found.</td></tr>@endforelse</tbody></table></div>@if($batches->hasPages())<div class="border-t border-slate-200 p-4">{{$batches->links()}}</div>@endif</section>
    <section class="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="border-b border-slate-200 px-5 py-4 dark:border-slate-800"><h2 class="font-semibold">Serial numbers</h2></div><div class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($serials as $serial)<div class="grid gap-3 p-4 sm:grid-cols-[1fr_1fr_1fr_auto] sm:items-center"><div><p class="font-mono font-semibold">{{$serial->serial_number}}</p><p class="text-xs text-slate-500">{{$serial->product?->name}}</p></div><p class="text-sm">{{$serial->warehouse?->name??'No physical location'}}</p><span class="w-fit rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold dark:bg-slate-800">{{str($serial->status)->headline()}}</span>@can('inventory.serial.manage')<form method="POST" action="{{route('inventory.traceability.serials.update',$serial)}}" class="flex gap-2">@csrf @method('PUT')<select name="status" class="min-h-11 rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-950">@foreach(['available','reserved','sold','returned','damaged','in_transit'] as $status)<option value="{{$status}}" @selected($serial->status===$status)>{{str($status)->replace('_',' ')->headline()}}</option>@endforeach</select><input type="hidden" name="warehouse_id" value="{{$serial->warehouse_id}}"><button class="min-h-11 rounded-lg border border-slate-300 px-3 text-sm font-semibold">Save</button></form>@endcan</div>@empty<div class="p-10 text-center text-sm text-slate-500">No serial numbers found.</div>@endforelse</div>@if($serials->hasPages())<div class="border-t border-slate-200 p-4">{{$serials->links()}}</div>@endif</section>
</div>
@endsection
