@extends('layouts.admin')
@section('title','Purchase Reports')
@section('page-title','Purchase Reports')
@section('content')
@include('command-center.purchases.partials.nav')
<div class="grid gap-4 md:grid-cols-3"><section class="rounded-lg border bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Supplier outstanding</p><p class="mt-2 text-2xl font-semibold">₹{{ number_format((float)$payable['outstanding'],2) }}</p></section><section class="rounded-lg border bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Supplier advances</p><p class="mt-2 text-2xl font-semibold">₹{{ number_format((float)$payable['advances'],2) }}</p></section><section class="rounded-lg border bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Net payable</p><p class="mt-2 text-2xl font-semibold">₹{{ number_format((float)$payable['net_payable'],2) }}</p></section></div>
<section class="mt-5 rounded-lg border bg-white p-5 shadow-sm"><h2 class="font-semibold">Ageing</h2><div class="mt-3 grid grid-cols-2 gap-3 text-sm md:grid-cols-5">@foreach($ageing as $bucket=>$amount)<div><p class="text-slate-500">{{ str($bucket)->replace('_','-')->headline() }}</p><p class="font-semibold">₹{{ number_format($amount/100,2) }}</p></div>@endforeach</div></section>
<section class="mt-5 overflow-hidden rounded-lg border bg-white shadow-sm"><div class="flex justify-between border-b p-4"><h2 class="font-semibold">Approved purchase register</h2><a href="{{ route('purchases.reports.input-gst') }}" class="text-sm font-medium text-teal-700">Input GST register</a></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Date</th><th>Supplier</th><th>Supplier invoice</th><th class="text-right">Taxable</th><th class="text-right">GST</th><th class="px-5 text-right">Total</th></tr></thead><tbody>@forelse($invoices as $invoice)<tr class="border-t"><td class="px-5 py-3">{{ $invoice->supplier_invoice_date->format('d M Y') }}</td><td>{{ $invoice->supplier->name }}</td><td>{{ $invoice->supplier_invoice_number }}</td><td class="text-right">₹{{ number_format((float)$invoice->taxable_total,2) }}</td><td class="text-right">₹{{ number_format((float)$invoice->input_cgst+(float)$invoice->input_sgst+(float)$invoice->input_igst,2) }}</td><td class="px-5 text-right">₹{{ number_format((float)$invoice->grand_total,2) }}</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-slate-500">No approved purchase invoices for this range.</td></tr>@endforelse</tbody></table></div><div class="border-t p-4">{{ $invoices->links() }}</div></section>
@endsection
