<!doctype html>
<html><head><style>
@page { margin: 18px; } body { color: #0f172a; font: 7.4px DejaVu Sans; } table { border-collapse: collapse; width: 100%; } th, td { vertical-align: top; } .right { text-align: right; } .muted { color: #475569; font-size: 6.8px; } .header { border: 1px solid #0f172a; } .header td { padding: 6px; } .company { font-size: 13px; font-weight: bold; } .invoice { background: #0f172a; color: white; font-size: 13px; font-weight: bold; } .facts td, .parties td { border: 1px solid #334155; padding: 4px; } .facts { margin-top: 5px; } .parties { margin-top: 5px; } .items-grid { margin-top: 6px; } .items-grid th, .items-grid td { border: 1px solid #334155; padding: 3px; } .items-grid th { background: #e2e8f0; font-size: 7px; } .items-grid thead, .gst-summary thead { display: table-header-group; } .items-grid tr { page-break-inside: avoid; } .gst-summary { margin-top: 6px; } .gst-summary h3 { margin: 0 0 3px; font-size: 8px; } .gst-summary th, .gst-summary td { border: 1px solid #475569; padding: 3px; } .gst-summary th { background: #e2e8f0; } .summary { margin-top: 6px; } .totals td { border: 1px solid #334155; padding: 3px; } .grand td, .balance td { background: #dbeafe; font-weight: bold; } .payment-qr { display: table; margin-top: 5px; } .payment-qr img, .payment-qr div { display: table-cell; vertical-align: middle; padding-right: 5px; } .small { font-size: 6.8px; } .avoid-break { page-break-inside: avoid; }
</style></head><body>
<table class="header" role="presentation"><tr><td width="68%">@include('invoice-templates.partials.company-branding', ['nameClass' => 'company']){{ $invoice->company->address }}@if($invoice->supplier_gstin_snapshot)<br>GSTIN: {{ $invoice->supplier_gstin_snapshot }}@endif</td><td class="invoice right">TAX INVOICE<br><span class="small">{{ $invoice->invoice_number }}<br>{{ str($render['setting']->copy_label)->headline() }}</span></td></tr></table>
<table class="facts" role="presentation"><tr><td><strong>Issue</strong><br>{{ $invoice->issue_date?->format('d M Y') }}</td><td><strong>Due</strong><br>{{ $invoice->due_date?->format('d M Y') ?: '—' }}</td><td><strong>POS</strong><br>{{ $invoice->place_of_supply ?: '—' }}</td><td><strong>Status</strong><br>{{ $invoice->status->label() }}</td></tr></table>
<table class="parties" role="presentation"><tr><td width="65%"><strong>Buyer</strong><br>{{ $invoice->billing_company ?: $invoice->billing_name }}<br>{{ $invoice->billing_address }}<br>GSTIN: {{ $invoice->customer_tax_number ?: '—' }}</td><td><strong>Reference</strong><br>Currency: {{ $invoice->currency }}<br>Tax classification: {{ $invoice->tax_classification ?: '—' }}</td></tr></table>
@include('invoice-templates.partials.items-grid')
<table class="summary" role="presentation"><tr><td width="57%">@include('invoice-templates.partials.gst-summary')</td><td>@include('invoice-templates.partials.totals')</td></tr></table>
<table class="parties avoid-break" role="presentation"><tr><td width="55%"><strong>Terms</strong><br>{{ $invoice->terms_conditions ?: 'Payment is due according to the terms stated above.' }}</td><td>@include('invoice-templates.partials.payment-qr')</td><td class="right"><strong>For {{ $invoice->company->name }}</strong><br><br><br>Authorised signatory</td></tr></table>
</body></html>
