<!doctype html>
<html><head><style>@include('invoice-templates.partials.print-page')
@page { margin: 26px; } body { color: #172033; font: 8.5px DejaVu Sans; } table { border-collapse: collapse; width: 100%; } th, td { vertical-align: top; } .right { text-align: right; } .muted { color: #64748b; font-size: 7.5px; } .corporate-header { background: #102a43; color: white; } .corporate-header td { padding: 13px; } .company { font-size: 18px; font-weight: bold; } .invoice-heading { font-size: 17px; font-weight: bold; } .reference td { border: 1px solid #7c97aa; padding: 6px; } .reference { margin-top: 10px; } .customer-blocks { margin-top: 10px; } .customer-blocks td { border: 1px solid #7c97aa; padding: 8px; } .customer-blocks strong { color: #0f466d; } .items-grid { margin-top: 12px; } .items-grid th, .items-grid td { border: 1px solid #48677d; padding: 5px; } .items-grid th { background: #dce8ee; color: #102a43; } .items-grid thead, .gst-summary thead { display: table-header-group; } .items-grid tr { page-break-inside: avoid; } .gst-summary { margin-top: 12px; } .gst-summary h3 { margin: 0 0 5px; color: #102a43; font-size: 10px; } .gst-summary th, .gst-summary td { border: 1px solid #7c97aa; padding: 4px; } .gst-summary th { background: #eaf1f5; } .payable { background: #e8f2ed; border-left: 4px solid #0f766e; padding: 9px; } .totals td { border-bottom: 1px solid #bad0c2; padding: 5px 2px; } .grand td, .balance td { color: #0f5132; font-weight: bold; } .footer-grid { margin-top: 13px; } .declaration { border: 1px solid #7c97aa; padding: 8px; min-height: 60px; } .payment-qr { display: table; margin-top: 8px; } .payment-qr img, .payment-qr div { display: table-cell; vertical-align: middle; padding-right: 8px; } .seal { border: 1px dashed #7c97aa; height: 54px; padding: 8px; text-align: center; } .avoid-break { page-break-inside: avoid; }
</style></head><body>
@include('invoice-templates.partials.watermark')
<table class="corporate-header" role="presentation"><tr><td width="64%">@include('invoice-templates.partials.company-branding', ['nameClass' => 'company']){{ $invoice->company->address }}@if($render['is_gst'] && $invoice->supplier_gstin_snapshot)<br>GSTIN: {{ $invoice->supplier_gstin_snapshot }}@endif</td><td class="right"><div class="invoice-heading">{{ $render['is_gst'] ? 'TAX INVOICE' : 'INVOICE' }}</div>{{ $invoice->invoice_number }}<br>{{ str($render['setting']->copy_label)->headline() }} copy</td></tr></table>
<table class="reference" role="presentation"><tr><td><strong>Invoice date</strong><br>{{ $invoice->issue_date?->format('d M Y') }}</td><td><strong>Due date</strong><br>{{ $invoice->due_date?->format('d M Y') ?: '—' }}</td><td><strong>Branch / store</strong><br>{{ $invoice->company->name }}</td><td><strong>Place of supply</strong><br>{{ $invoice->place_of_supply ?: '—' }}</td><td><strong>Status</strong><br>{{ $invoice->status->label() }}</td></tr></table>
<table class="customer-blocks" role="presentation"><tr><td width="50%"><strong>Billing customer</strong><br>{{ $invoice->billing_company ?: $invoice->billing_name }}<br>{{ $invoice->billing_address }}@if($render['is_gst'])<br>GSTIN: {{ $invoice->customer_tax_number ?: '—' }}@endif</td><td><strong>Supply and reference</strong>@if($render['is_gst'])<br>Tax classification: {{ $invoice->tax_classification ?: '—' }}@endif<br>Customer email: {{ $invoice->billing_email ?: '—' }}<br>Customer phone: {{ $invoice->billing_phone ?: '—' }}</td></tr></table>
@include('invoice-templates.partials.items-grid')
@include('invoice-templates.partials.gst-summary')
<table class="footer-grid" role="presentation"><tr><td width="57%"><div class="declaration"><strong>Declaration</strong><br>We declare that the particulars given above are true and the tax presentation uses the GST information retained with this invoice.<br><br><strong>Terms</strong><br>{{ $invoice->terms_conditions ?: 'Payment is due according to the stated due date.' }}</div>@include('invoice-templates.partials.payment-qr')</td><td><div class="payable"><strong>Payable and outstanding</strong>@include('invoice-templates.partials.totals')</div></td></tr></table>
<table class="footer-grid" role="presentation"><tr><td><div class="seal">Company seal</div></td><td class="right"><strong>For {{ $invoice->company->legal_name ?: $invoice->company->name }}</strong><br><br><br>Authorised signatory</td></tr></table>
@include('invoice-templates.partials.payment-details')
</body></html>
