<!doctype html>
<html><head><style>@include('invoice-templates.partials.print-page')
@page { margin: 25px; } body { color: #172033; font: 9px DejaVu Sans; } table { border-collapse: separate; border-spacing: 0; width: 100%; } th, td { vertical-align: top; } .right { text-align: right; } .muted { color: #64748b; font-size: 8px; } .top { border-bottom: 1px solid #cbd5e1; padding-bottom: 14px; } .seller { font-size: 18px; font-weight: bold; color: {{ $render['setting']->brand_color }}; } .invoice-panel { background: #152c42; color: white; padding: 12px; } .invoice-panel .title { font-size: 16px; font-weight: bold; } .cards { margin-top: 14px; border-spacing: 8px 0; margin-left: -8px; width: calc(100% + 8px); } .cards td { background: #f1f5f9; padding: 10px; border-top: 3px solid {{ $render['setting']->brand_color }}; } .items-minimal { margin-top: 14px; } .items-minimal th { color: #64748b; border-bottom: 1px solid #94a3b8; padding: 7px; } .items-minimal td { border-bottom: 1px solid #e2e8f0; padding: 8px 7px; } .items-minimal thead { display: table-header-group; } .items-minimal tr { page-break-inside: avoid; } .lower { margin-top: 15px; } .summary-panel { background: #eaf4f2; padding: 11px; } .totals td { padding: 5px 0; border-bottom: 1px solid #cde2dd; } .grand td { color: #0f766e; font-size: 11px; font-weight: bold; } .balance td { background: #cfece6; font-weight: bold; padding: 7px 3px; } .payment-qr { display: table; margin-top: 12px; } .payment-qr img, .payment-qr div { display: table-cell; vertical-align: middle; padding-right: 8px; } .gst-summary { margin-top: 14px; } .gst-summary h3 { color: #0f766e; } .gst-summary th, .gst-summary td { border-bottom: 1px solid #dbe5e2; padding: 4px; } .gst-summary th { color: #475569; } .footer { border-top: 1px solid #cbd5e1; margin-top: 16px; padding-top: 10px; } .avoid-break { page-break-inside: avoid; }
</style></head><body>
@include('invoice-templates.partials.watermark')
<table class="top" role="presentation"><tr><td width="62%">@include('invoice-templates.partials.company-branding', ['nameClass' => 'seller'])<span>{{ $invoice->company->address }}</span>@if($render['is_gst'] && $invoice->supplier_gstin_snapshot)<br><strong>GSTIN</strong> {{ $invoice->supplier_gstin_snapshot }}@endif</td><td><div class="invoice-panel"><div class="title">{{ $render['is_gst'] ? 'Tax invoice' : 'Invoice' }}</div><strong>{{ $invoice->invoice_number }}</strong><br>{{ str($render['setting']->copy_label)->headline() }} copy<br><br>Status: {{ $invoice->status->label() }}</div></td></tr></table>
<table class="cards" role="presentation"><tr><td width="50%"><strong>Customer</strong><br>{{ $invoice->billing_company ?: $invoice->billing_name }}<br>{{ $invoice->billing_address }}@if($render['is_gst'])<br>{{ $invoice->customer_tax_number }}@endif</td><td><strong>Invoice schedule</strong><br>Issued {{ $invoice->issue_date?->format('d M Y') }}<br>Due {{ $invoice->due_date?->format('d M Y') ?: '—' }}<br>Place {{ $invoice->place_of_supply ?: '—' }}</td></tr></table>
@include('invoice-templates.partials.items-minimal')
<table class="lower" role="presentation"><tr><td width="58%"><div><strong>Payment status</strong><br>{{ $invoice->status->label() }}. Amounts shown are based on the stored invoice payment state.</div>@include('invoice-templates.partials.payment-qr')<div style="margin-top:12px"><strong>Notes</strong><br>{{ $invoice->notes ?: $invoice->terms_conditions ?: 'Thank you for your business.' }}</div></td><td><div class="summary-panel">@include('invoice-templates.partials.totals')</div></td></tr></table>
@include('invoice-templates.partials.gst-summary')
<div class="footer"><strong>{{ $invoice->company->name }}</strong> · This document is generated from the issued invoice and its recorded GST snapshots.</div>
@include('invoice-templates.partials.payment-details')
</body></html>
