<!doctype html>
<html><head><style>@include('invoice-templates.partials.print-page')
@page { margin: 28px; } body { color: #263238; font: 9px DejaVu Sans; } table { border-collapse: collapse; width: 100%; } th, td { vertical-align: top; } .right { text-align: right; } .muted { color: #78838c; font-size: 8px; } .page { border: 2px solid #c9a868; padding: 17px; } .masthead { border-bottom: 1px solid #d7c3a0; padding-bottom: 14px; } .brand { color: {{ $render['setting']->brand_color }}; font-size: 20px; font-weight: bold; letter-spacing: 1px; } .title { color: #9a7436; font-size: 19px; } .strip { background: #fbf7ef; margin-top: 12px; } .strip td { padding: 8px 10px; } .customer { margin-top: 12px; } .customer td { border: 1px solid #eadfc9; padding: 9px; } .customer strong { color: #8a6833; } .items-minimal { margin-top: 15px; } .items-minimal th { border-bottom: 2px solid #c9a868; color: #8a6833; padding: 6px; } .items-minimal td { border-bottom: 1px solid #eee5d6; padding: 7px 6px; } .items-minimal thead { display: table-header-group; } .items-minimal tr { page-break-inside: avoid; } .gst-summary { margin-top: 13px; } .gst-summary h3 { color: #8a6833; font-size: 10px; } .gst-summary th, .gst-summary td { border-bottom: 1px solid #e8decf; padding: 4px; } .gst-summary th { background: #fbf7ef; } .footer-grid { margin-top: 16px; } .notes { padding-right: 16px; } .totals { border: 1px solid #ddc79e; } .totals td { padding: 6px 8px; border-bottom: 1px solid #eadfc9; } .grand td, .balance td { background: #fbf4e5; font-weight: bold; color: #6d4f23; } .payment-qr { display: table; margin-top: 10px; } .payment-qr img, .payment-qr div { display: table-cell; vertical-align: middle; padding-right: 8px; } .signature { border: 1px solid #ddc79e; margin-top: 14px; padding: 10px; min-height: 55px; } .avoid-break { page-break-inside: avoid; }
</style></head><body><div class="page">
<table class="masthead" role="presentation"><tr><td>@include('invoice-templates.partials.company-branding', ['nameClass' => 'brand'])<span>{{ $invoice->company->address }}</span>@if($render['is_gst'] && $invoice->supplier_gstin_snapshot)<br><span>GSTIN {{ $invoice->supplier_gstin_snapshot }}</span>@endif</td><td class="right"><div class="title">{{ $render['is_gst'] ? 'Tax Invoice' : 'Invoice' }}</div><strong>{{ $invoice->invoice_number }}</strong><br>{{ str($render['setting']->copy_label)->headline() }} copy</td></tr></table>
<table class="strip" role="presentation"><tr><td><strong>Issued</strong><br>{{ $invoice->issue_date?->format('d M Y') }}</td><td><strong>Due</strong><br>{{ $invoice->due_date?->format('d M Y') ?: '—' }}</td><td><strong>Supply</strong><br>{{ $invoice->place_of_supply ?: '—' }}</td><td class="right"><strong>Status</strong><br>{{ $invoice->status->label() }}</td></tr></table>
<table class="customer" role="presentation"><tr><td width="50%"><strong>Billing customer</strong><br>{{ $invoice->billing_company ?: $invoice->billing_name }}<br>{{ $invoice->billing_address }}@if($render['is_gst'])<br>{{ $invoice->customer_tax_number }}@endif</td><td><strong>Contact</strong><br>{{ $invoice->billing_email }}<br>{{ $invoice->billing_phone }}</td></tr></table>
@include('invoice-templates.partials.items-minimal')
<table class="footer-grid" role="presentation"><tr><td class="notes" width="58%"><div><strong>A note from {{ $invoice->company->name }}</strong><br>{{ $invoice->notes ?: $invoice->terms_conditions ?: 'Thank you for your business.' }}</div>@include('invoice-templates.partials.payment-qr')<div class="signature"><strong>Authorised signature</strong><br><br><br>{{ $invoice->company->legal_name ?: $invoice->company->name }}</div></td><td>@include('invoice-templates.partials.totals')</td></tr></table>
@include('invoice-templates.partials.gst-summary')
</div></body></html>
