<!doctype html>
<html><head><style>@include('invoice-templates.partials.print-page')
@page { margin: 24px; } body { color: #111827; font: 9px DejaVu Sans; } table { border-collapse: collapse; width: 100%; } th, td { vertical-align: top; } .right { text-align: right; } .muted { color: #64748b; font-size: 8px; } .header { border-bottom: 3px solid {{ $render['setting']->brand_color }}; padding-bottom: 10px; } .header .company-name { font-size: 17px; font-weight: bold; margin: 0 0 3px; } .invoice-title { font-size: 18px; font-weight: bold; } .meta td, .party td { border: 1px solid #111827; padding: 7px; } .meta { margin-top: 12px; } .party { margin-top: 8px; } .items-grid { margin-top: 12px; } .items-grid th, .items-grid td { border: 1px solid #111827; padding: 5px; } .items-grid th { background: #e5e7eb; } .items-grid thead, .gst-summary thead { display: table-header-group; } .items-grid tr { page-break-inside: avoid; } .gst-summary { margin-top: 12px; } .gst-summary h3 { margin: 0 0 5px; font-size: 10px; } .gst-summary th, .gst-summary td { border: 1px solid #334155; padding: 4px; } .gst-summary th { background: #f1f5f9; } .bottom { margin-top: 12px; } .totals td { border: 1px solid #111827; padding: 5px; } .grand td, .balance td { font-weight: bold; background: #f8fafc; } .payment-qr { display: table; margin-top: 10px; } .payment-qr img, .payment-qr div { display: table-cell; vertical-align: middle; padding-right: 8px; } .avoid-break { page-break-inside: avoid; }
</style></head><body>
<table class="header" role="presentation"><tr><td>@include('invoice-templates.partials.company-branding', ['nameClass' => 'company-name'])<span>{{ $invoice->company->address }}</span><br>@if($render['is_gst'] && $invoice->supplier_gstin_snapshot)<strong>GSTIN:</strong> {{ $invoice->supplier_gstin_snapshot }}@endif</td><td class="right"><div class="invoice-title">{{ $render['is_gst'] ? 'TAX INVOICE' : 'INVOICE' }}</div><strong>{{ $invoice->invoice_number }}</strong><br>{{ str($render['setting']->copy_label)->headline() }} copy</td></tr></table>
<table class="meta" role="presentation"><tr><td width="50%"><strong>Invoice date</strong><br>{{ $invoice->issue_date?->format('d M Y') }}</td><td width="25%"><strong>Due date</strong><br>{{ $invoice->due_date?->format('d M Y') ?: '—' }}</td><td><strong>Place of supply</strong><br>{{ $invoice->place_of_supply ?: '—' }}</td></tr></table>
<table class="party" role="presentation"><tr><td width="50%"><strong>Bill to</strong><br>{{ $invoice->billing_company ?: $invoice->billing_name }}<br>{{ $invoice->billing_address }}@if($render['is_gst'])<br>{{ $invoice->customer_tax_number }}@endif</td><td><strong>Ship to</strong><br>{{ $render['setting']->options['show_ship_to'] ? ($invoice->billing_address ?: 'Same as billing address') : 'Same as billing address' }}</td></tr></table>
@include('invoice-templates.partials.items-grid')
@include('invoice-templates.partials.gst-summary')
<table class="bottom" role="presentation"><tr><td width="54%">@include('invoice-templates.partials.payment-qr')<div class="avoid-break"><strong>Bank and payment details</strong><br>Payment is accepted against the outstanding amount shown on this invoice.</div><div class="avoid-break" style="margin-top:10px"><strong>Terms and conditions</strong><br>{{ $invoice->terms_conditions ?: 'Payment is due according to the invoice due date.' }}</div></td><td>@include('invoice-templates.partials.totals')</td></tr></table>
<table class="party" role="presentation"><tr><td><strong>Declaration</strong><br>{{ $render['is_gst'] ? 'We declare that this invoice shows the applicable GST snapshots for the supply.' : 'We declare that the particulars given above are true and correct.' }}</td><td class="right">@include('invoice-templates.partials.authorized-signature')</td></tr></table>
</body></html>
