@extends('layouts.admin')
@section('title', $article->exists ? 'Edit article' : 'Create article')
@section('page-title', $article->exists ? 'Edit article' : 'Create article')
@section('content')
    <div class="space-y-6">
        @include('command-center.cms.partials.nav')
        <form method="POST" action="{{ $article->exists ? route('cms.articles.update', $article) : route('cms.articles.store') }}" class="grid gap-6 xl:grid-cols-[1.25fr_0.75fr]">@csrf @if($article->exists) @method('PUT') @endif
            <section class="space-y-5 rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="grid gap-4 md:grid-cols-2"><input name="title" required value="{{ old('title', $article->title) }}" placeholder="Article title"><input name="slug" required value="{{ old('slug', $article->slug) }}" placeholder="article-slug"></div><input type="number" name="cover_image_id" value="{{ old('cover_image_id', $article->cover_image_id) }}" placeholder="Cover image media ID" class="w-full"><textarea name="excerpt" rows="3" placeholder="Excerpt" class="w-full">{{ old('excerpt', $article->excerpt) }}</textarea><textarea name="content" rows="18" placeholder="Article content" class="w-full">{{ old('content', $article->content) }}</textarea></section>
            <aside class="space-y-5"><section class="space-y-4 rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><input name="author_name" value="{{ old('author_name', $article->author_name) }}" placeholder="Author name" class="w-full"><input name="category" value="{{ old('category', $article->category) }}" placeholder="Category" class="w-full"><textarea name="tags" rows="2" placeholder='Tags JSON ["retail","pos"]' class="w-full">{{ old('tags', $article->tags ? json_encode($article->tags) : '') }}</textarea><select name="status" class="w-full">@foreach(['draft','published','archived'] as $status)<option value="{{ $status }}" @selected(old('status', $article->status) === $status)>{{ str($status)->headline() }}</option>@endforeach</select></section><section class="space-y-4 rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold text-slate-950 dark:text-white">SEO preview</h2><p class="text-lg text-blue-700">{{ old('meta_title', $article->meta_title ?: $article->title ?: 'Article title') }}</p><textarea name="meta_title" rows="2" placeholder="Meta title" class="w-full">{{ old('meta_title', $article->meta_title) }}</textarea><textarea name="meta_description" rows="3" placeholder="Meta description" class="w-full">{{ old('meta_description', $article->meta_description) }}</textarea><input name="canonical_url" value="{{ old('canonical_url', $article->canonical_url) }}" placeholder="Canonical URL" class="w-full"><textarea name="schema_json" rows="4" placeholder="Schema JSON" class="w-full">{{ old('schema_json', $article->schema_json) }}</textarea><label class="flex gap-2 text-sm"><input type="hidden" name="include_in_sitemap" value="0"><input type="checkbox" name="include_in_sitemap" value="1" @checked(old('include_in_sitemap', $article->include_in_sitemap ?? true))> Include in sitemap</label><input type="number" name="sitemap_priority" step="0.1" min="0" max="1" value="{{ old('sitemap_priority', $article->sitemap_priority ?? '0.5') }}"><select name="sitemap_changefreq">@foreach(['monthly','weekly','yearly'] as $frequency)<option value="{{ $frequency }}" @selected(old('sitemap_changefreq', $article->sitemap_changefreq ?? 'monthly') === $frequency)>{{ str($frequency)->headline() }}</option>@endforeach</select><button class="w-full rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white dark:bg-teal-300 dark:text-slate-950">Save article</button></section></aside>
        </form>
        @if ($article->exists)
            <section class="flex gap-3">
                @if ($article->status !== 'published')
                    <form method="POST" action="{{ route('cms.articles.publish', $article) }}">@csrf<button class="rounded-lg border border-teal-300 px-3 py-2 text-sm font-semibold text-teal-700">Publish</button></form>
                @endif
                @if ($article->status === 'published')
                    <form method="POST" action="{{ route('cms.articles.unpublish', $article) }}">@csrf<button class="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700">Unpublish</button></form>
                @endif
                <form method="POST" action="{{ route('cms.articles.archive', $article) }}">@csrf<button class="rounded-lg border border-rose-300 px-3 py-2 text-sm font-semibold text-rose-700">Archive</button></form>
            </section>
        @endif
    </div>
@endsection
