@extends('layouts.admin')
@section('title', 'Articles')
@section('page-title', 'Articles')
@section('content')
    <div class="space-y-6">
        @include('command-center.cms.partials.nav')
        <section class="flex flex-col justify-between gap-4 rounded-lg border border-slate-200 bg-white p-5 shadow-sm sm:flex-row sm:items-end dark:border-slate-800 dark:bg-slate-900"><div><p class="text-sm font-medium text-teal-700">Content growth</p><h1 class="mt-2 text-2xl font-semibold text-slate-950 dark:text-white">Blog & Articles</h1><p class="mt-1 text-sm text-slate-500">Draft, publish, and prepare search-ready article content.</p></div><a href="{{ route('cms.articles.create') }}" class="rounded-lg bg-slate-950 px-4 py-2.5 text-center text-sm font-semibold text-white dark:bg-teal-300 dark:text-slate-950">Create article</a></section>
        <section class="rounded-lg border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><form class="flex flex-col gap-3 sm:flex-row"><input class="flex-1" name="search" value="{{ request('search') }}" placeholder="Search title or category"><select name="status"><option value="">All statuses</option>@foreach(['draft','published','archived'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ str($status)->headline() }}</option>@endforeach</select><button class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Filter</button></form></section>
        <section class="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="overflow-x-auto"><table class="min-w-[700px] w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-950"><tr><th class="px-5 py-3">Article</th><th class="px-5 py-3">Category</th><th class="px-5 py-3">SEO</th><th class="px-5 py-3">Status</th><th class="px-5 py-3"></th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($articles as $article)<tr><td class="px-5 py-4"><p class="font-semibold text-slate-950 dark:text-white">{{ $article->title }}</p><p class="mt-1 text-xs text-slate-500">/{{ $article->slug }}</p></td><td class="px-5 py-4">{{ $article->category ?: 'Uncategorized' }}</td><td class="px-5 py-4">{{ blank($article->meta_title) ? 'Needs meta title' : 'Ready' }}</td><td class="px-5 py-4"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold">{{ str($article->status)->headline() }}</span></td><td class="px-5 py-4 text-right"><a href="{{ route('cms.articles.edit', $article) }}" class="font-semibold text-teal-700">Edit</a></td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-slate-500">No articles yet.</td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-100 p-4">{{ $articles->links() }}</div></section>
    </div>
@endsection
