@extends('layouts.admin')

@section('title', 'Edit Lead Source')
@section('page-title', 'Edit Lead Source')
@section('breadcrumbs')<span>/</span><a href="{{ route('crm.settings.index') }}" class="hover:text-slate-950 dark:hover:text-white">CRM Settings</a><span>/</span><a href="{{ route('crm.settings.sources.index') }}" class="hover:text-slate-950 dark:hover:text-white">Lead Sources</a><span>/</span><span>Edit</span>@endsection

@section('content')
    <div class="mx-auto max-w-2xl"><section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex items-start justify-between gap-4"><div><h1 class="text-xl font-semibold">Edit {{ $source->name }}</h1><p class="mt-2 text-sm text-slate-500">The internal integration identifier stays stable when you rename a source.</p></div><a href="{{ route('crm.settings.sources.index') }}" class="text-sm font-semibold text-teal-700 dark:text-teal-300">Back</a></div><form method="POST" action="{{ route('crm.settings.sources.update', $source) }}" class="mt-6 grid gap-5 sm:grid-cols-2">@csrf @method('PUT')<div class="sm:col-span-2"><label for="name">Source name</label><input id="name" name="name" required value="{{ old('name', $source->name) }}" class="mt-1.5 w-full rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-950">@error('name')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div><div class="sm:col-span-2"><label for="description">Short description</label><textarea id="description" name="description" rows="4" class="mt-1.5 w-full rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-950">{{ old('description', $source->description) }}</textarea></div><div><label for="tone">Badge tone</label><select id="tone" name="tone" class="mt-1.5 w-full rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-950">@foreach (['neutral','info','success','warning','danger'] as $tone)<option value="{{ $tone }}" @selected(old('tone', $source->tone) === $tone)>{{ str($tone)->headline() }}</option>@endforeach</select></div><div><label for="color">Optional brand colour</label><input id="color" name="color" value="{{ old('color', $source->color) }}" placeholder="#0f766e" class="mt-1.5 w-full rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-950"></div><label class="sm:col-span-2 flex items-start gap-3 text-sm"><input type="checkbox" name="is_default" value="1" class="mt-0.5 rounded border-slate-300 text-teal-600" @checked(old('is_default', $source->is_default))><span><span class="font-medium">Make this the default</span><span class="mt-0.5 block text-xs text-slate-500">Optional. No source remains available.</span></span></label><div class="sm:col-span-2 flex justify-end gap-3"><a href="{{ route('crm.settings.sources.index') }}" class="rounded-lg px-4 py-2.5 text-sm font-semibold text-slate-600">Cancel</a><button class="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white dark:bg-teal-300 dark:text-slate-950">Save source</button></div></form></section></div>
@endsection
