@php($variant = $render['template']['variant'])
<!doctype html><html><head><style>@include('invoice-templates.partials.print-page')
body{color:#182235;font:9px DejaVu Sans}.right{text-align:right}.muted{color:#64748b;font-size:8px}table{border-collapse:collapse;width:100%}th,td{vertical-align:top}.masthead{background:#123b70;color:#fff}.masthead td{padding:15px}.company{font-size:18px;font-weight:bold}.title{font-size:19px;font-weight:bold;letter-spacing:.7px}.meta{margin-top:12px}.meta td{border:1px solid #cbd5e1;padding:7px}.customer{margin-top:10px;background:#f8fafc}.customer td{padding:10px;border-top:3px solid {{ $render['setting']->brand_color }} }.items-grid{margin-top:12px}.items-grid th,.items-grid td{border:1px solid #94a3b8;padding:5px}.items-grid th{background:#e7eff9;color:#123b70}.items-grid thead,.gst-summary thead{display:table-header-group}.items-grid tr,.avoid-break{page-break-inside:avoid}.gst-summary{margin-top:12px}.gst-summary h3{font-size:10px}.gst-summary th,.gst-summary td{border:1px solid #cbd5e1;padding:4px}.gst-summary th{background:#f1f5f9}.footer{margin-top:12px}.totals{border:1px solid #bfd0e4}.totals td{padding:5px;border-bottom:1px solid #dbe5f0}.grand td{background:#123b70;color:#fff;font-weight:bold}.balance td{background:#dbeafe;font-weight:bold}.payment-qr{display:table;margin-top:10px}.payment-qr img,.payment-qr div{display:table-cell;vertical-align:middle;padding-right:8px}.variant-dark .masthead{background:#111827;border-bottom:6px solid #475569}.variant-dark .customer{background:#eef2f7}.variant-green .masthead{background:#fff;color:#14532d;border-left:12px solid #166534;border-bottom:2px solid #166534}.variant-green .items-grid th{background:#e8f5ec;color:#14532d}.variant-green .grand td{background:#166534}.variant-split .masthead{background:#fff;color:#182235;border:1px solid #cbd5e1}.variant-split .masthead td:last-child{background:#123b70;color:#fff}.variant-split .customer td:first-child{border-left:6px solid #123b70}.variant-premium .masthead{background:#fff;color:#182235;border-top:7px solid #182235;border-bottom:1px solid #94a3b8}.variant-premium .title{letter-spacing:2px}.variant-premium .meta td{border:0;border-bottom:1px solid #cbd5e1}.variant-premium .items-grid th{background:#182235;color:#fff}.variant-premium .grand td{background:#182235}</style></head><body class="variant-{{ $variant }}">
<table class="masthead" role="presentation"><tr><td width="64%">@include('invoice-templates.partials.company-branding',['nameClass'=>'company']){{ $invoice->company->address }}@if($render['is_gst'] && $invoice->supplier_gstin_snapshot)<br>GSTIN: {{ $invoice->supplier_gstin_snapshot }}@endif</td><td class="right"><div class="title">{{ $variant === 'premium' ? 'BUSINESS '.($render['is_gst'] ? 'TAX INVOICE' : 'INVOICE') : ($render['is_gst'] ? 'TAX INVOICE' : 'INVOICE') }}</div>{{ $invoice->invoice_number }}<br>{{ str($render['setting']->copy_label)->replace('_',' ')->headline() }}</td></tr></table>
<table class="meta" role="presentation"><tr><td>Invoice date<br><strong>{{ $invoice->issue_date?->format('d M Y') }}</strong></td><td>Due date<br><strong>{{ $invoice->due_date?->format('d M Y') ?: '—' }}</strong></td><td>Place of supply<br><strong>{{ $invoice->place_of_supply ?: '—' }}</strong></td><td>Status<br><strong>{{ $invoice->status->label() }}</strong></td></tr></table>
<table class="customer" role="presentation"><tr><td width="55%"><strong>Bill to</strong><br>{{ $invoice->billing_company ?: $invoice->billing_name }}<br>{{ $invoice->billing_address }}@if($render['is_gst'])<br>GSTIN: {{ $invoice->customer_tax_number ?: '—' }}@endif</td><td><strong>Contact</strong><br>{{ $invoice->billing_email ?: '—' }}<br>{{ $invoice->billing_phone ?: '—' }}@if($render['is_gst'])<br>Tax classification: {{ $invoice->tax_classification ?: '—' }}@endif</td></tr></table>
@include('invoice-templates.partials.items-grid')
@if($render['is_gst'] && $render['setting']->gst_presentation === 'detailed') @include('invoice-templates.partials.gst-summary') @endif
<table class="footer" role="presentation"><tr><td width="58%">@if(data_get($render,'setting.options.show_terms',true))<strong>Terms and conditions</strong><br>{{ $invoice->terms_conditions ?: 'Payment is due according to the invoice due date.' }}@endif @include('invoice-templates.partials.payment-qr')</td><td>@include('invoice-templates.partials.totals')</td></tr></table>
</body></html>
