@php($variant = $render['template']['variant'])
@php($clientLabel = match($variant) {'construction' => 'Project / client', 'contractor' => 'Contracting client', 'medical' => 'Patient / client', 'catering' => 'Event client', 'rental' => 'Renter / customer', default => 'Bill to'})
<!doctype html>
<!-- {{ $render['template']['label'] }} -->
<html><head><style>
@include('invoice-templates.partials.print-page')
body{font:9px DejaVu Sans;color:#243447}.right{text-align:right}.muted{color:#62748a;font-size:8px}table{border-collapse:collapse;width:100%}th,td{vertical-align:top}.bar{height:10px;background:#0369a1;margin:-12mm -12mm 13px}.head td{padding-bottom:12px}.brand{font-size:20px;font-weight:bold}.title{font-size:18px;font-weight:bold}.facts{margin-top:9px}.facts td{border:1px solid #cbd5e1;padding:7px}.items-grid{margin-top:13px}.items-grid th,.items-grid td{border:1px solid #94a3b8;padding:5px}.items-grid th{background:#eaf1f8}.items-grid thead{display:table-header-group}.footer{margin-top:14px}.totals td{padding:5px;border-bottom:1px solid #dbe4ed}.grand td{background:#243447;color:#fff;font-weight:bold}.balance td{font-weight:bold;background:#eef6f3}.avoid-break,.items-grid tr{page-break-inside:avoid}.variant-construction .head{border-bottom:4px solid #0369a1}.variant-construction .facts td:first-child{background:#eff6ff}.variant-contractor .bar{height:16px;background:#b91c1c}.variant-contractor .facts{border-left:7px solid #b91c1c}.variant-contractor .items-grid th{background:#fee2e2;color:#7f1d1d}.variant-contractor .grand td{background:#b91c1c}.variant-medical{color:#164e63}.variant-medical .bar{height:4px;background:#0891b2}.variant-medical .head{background:#ecfeff}.variant-medical .head td{padding:13px}.variant-medical .facts td{border:0;border-bottom:1px solid #a5f3fc}.variant-medical .items-grid th{background:#cffafe;color:#155e75}.variant-medical .grand td{background:#0e7490}.variant-catering{color:#294236}.variant-catering .bar{background:#166534}.variant-catering .head{border-bottom:1px solid #86efac}.variant-catering .facts td:first-child{background:#f0fdf4}.variant-catering .items-grid th{background:#166534;color:#fff}.variant-catering .grand td{background:#166534}.variant-rental .bar{background:#ea580c}.variant-rental .head td:last-child{background:#fff7ed;padding:12px}.variant-rental .facts td{border-color:#fed7aa}.variant-rental .items-grid th{background:#ffedd5;color:#9a3412}.variant-rental .grand td{background:#ea580c}
</style></head><body class="variant-{{ $variant }}">
<div class="bar"></div>
<table class="head"><tr><td>@include('invoice-templates.partials.company-branding',['nameClass'=>'brand']){{ $invoice->company->address }}</td><td class="right"><div class="title">{{ $variant === 'medical' ? 'CONSULTATION '.($render['is_gst'] ? 'TAX INVOICE' : 'INVOICE') : ($render['is_gst'] ? 'TAX INVOICE' : 'INVOICE') }}</div>{{ $invoice->invoice_number }}<br>{{ $invoice->issue_date?->format('d M Y') }}</td></tr></table>
<table class="facts"><tr><td width="56%"><strong>{{ $clientLabel }}</strong><br>{{ $invoice->billing_company ?: $invoice->billing_name }}<br>{{ $invoice->billing_address }}</td><td><strong>{{ $variant === 'rental' ? 'Rental date' : 'Document date' }}</strong><br>{{ $invoice->issue_date?->format('d M Y') }}<br><strong>Reference</strong><br>{{ $invoice->tax_classification ?: '—' }}</td></tr></table>
@include('invoice-templates.partials.items-grid')
<table class="footer"><tr><td width="56%">@if($render['is_gst'] && $render['setting']->gst_presentation==='detailed')@include('invoice-templates.partials.gst-summary')@endif @if($invoice->terms_conditions)<strong>Terms</strong><br>{{ $invoice->terms_conditions }}@endif @include('invoice-templates.partials.payment-qr')</td><td>@include('invoice-templates.partials.totals')</td></tr></table>
</body></html>
