@php($variant = $render['template']['variant'])
<!doctype html><html><head><style>@include('invoice-templates.partials.print-page')
body{color:#263238;font:9px DejaVu Sans}.right{text-align:right}.muted{color:#78838c;font-size:8px}table{border-collapse:collapse;width:100%}th,td{vertical-align:top}.head{border-bottom:2px solid {{ $variant === 'purple' ? '#6d28d9' : $render['setting']->brand_color }};padding-bottom:13px}.brand{font-size:21px;font-weight:bold;letter-spacing:.6px;color:{{ $variant === 'purple' ? '#6d28d9' : $render['setting']->brand_color }} }.title{font-size:20px;font-weight:bold}.customer{margin-top:16px}.customer td{padding:9px;background:#f8fafc}.invoice-data{margin-top:8px}.invoice-data td{padding:7px;border-bottom:1px solid #e2e8f0}.items-minimal{margin-top:16px}.items-minimal th{padding:6px;border-bottom:2px solid #334155;color:#475569}.items-minimal td{padding:8px 6px;border-bottom:1px solid #edf2f7}.items-minimal thead{display:table-header-group}.items-minimal tr,.avoid-break{page-break-inside:avoid}.lower{margin-top:17px}.totals td{padding:6px;border-bottom:1px solid #e2e8f0}.grand td{font-size:12px;font-weight:bold;color:{{ $render['setting']->brand_color }} }.balance td{font-weight:bold;background:#f1f5f9}.gst-summary h3{font-size:10px}.gst-summary th,.gst-summary td{padding:4px;border-bottom:1px solid #e2e8f0}.payment-qr{display:table;margin-top:12px}.payment-qr img,.payment-qr div{display:table-cell;vertical-align:middle;padding-right:8px}.variant-minimal .customer td{background:#fff;border-bottom:1px solid #cbd5e1}.variant-minimal .items-minimal th{background:#fff}.variant-purple .head{border:0;background:#faf5ff;padding:15px}.variant-purple .title{color:#6d28d9;letter-spacing:1.4px}.variant-purple .customer td:first-child{border-left:7px solid #6d28d9}.variant-purple .items-minimal th{border-bottom-color:#6d28d9;color:#6d28d9}.variant-purple .grand td{background:#6d28d9;color:#fff;padding:8px}</style></head><body class="variant-{{ $variant }}">
<table class="head" role="presentation"><tr><td width="62%">@include('invoice-templates.partials.company-branding',['nameClass'=>'brand']){{ $invoice->company->address }}</td><td class="right"><div class="title">INVOICE</div><strong>{{ $invoice->invoice_number }}</strong><br>{{ str($render['setting']->copy_label)->replace('_',' ')->headline() }}</td></tr></table>
<table class="customer" role="presentation"><tr><td width="58%"><strong>Bill to</strong><br>{{ $invoice->billing_company ?: $invoice->billing_name }}<br>{{ $invoice->billing_address }}@if($render['is_gst'])<br>GSTIN {{ $invoice->customer_tax_number ?: '—' }}@endif</td><td><strong>From</strong><br>{{ $invoice->company->name }}@if($render['is_gst'])<br>GSTIN {{ $invoice->supplier_gstin_snapshot ?: '—' }}@endif</td></tr></table>
<table class="invoice-data" role="presentation"><tr><td>Issued {{ $invoice->issue_date?->format('d M Y') }}</td><td>Due {{ $invoice->due_date?->format('d M Y') ?: '—' }}</td><td>Place {{ $invoice->place_of_supply ?: '—' }}</td><td class="right">{{ $invoice->status->label() }}</td></tr></table>
@include('invoice-templates.partials.items-minimal')
<table class="lower" role="presentation"><tr><td width="58%">@if($render['is_gst'] && $render['setting']->gst_presentation === 'detailed') @include('invoice-templates.partials.gst-summary') @endif @if(data_get($render,'setting.options.show_terms',true))<div class="avoid-break"><strong>Notes</strong><br>{{ $invoice->notes ?: $invoice->terms_conditions ?: 'Thank you for your business.' }}</div>@endif @include('invoice-templates.partials.payment-qr')</td><td>@include('invoice-templates.partials.totals')</td></tr></table>
</body></html>
