@php($variant = $render['template']['variant'])
<!doctype html>
<html><head><style>
@include('invoice-templates.partials.print-page')
body{font:9px DejaVu Sans;color:#243047}.right{text-align:right}.muted{color:#64748b;font-size:8px}table{border-collapse:collapse;width:100%}th,td{vertical-align:top}.head{border-left:8px solid {{ $render['setting']->brand_color }};padding:14px;background:#f8fafc}.title{font-size:20px;font-weight:bold}.client{margin-top:14px}.client td{padding:9px;border-bottom:1px solid #dbe4ed}.items-minimal{margin-top:15px}.items-minimal th{padding:7px;color:#fff;background:#243047}.items-minimal td{padding:7px;border-bottom:1px solid #dbe4ed}.items-minimal thead{display:table-header-group}.summary{margin-top:15px}.summary td{vertical-align:top}.totals td{padding:6px;border-bottom:1px solid #dbe4ed}.grand td{background:{{ $render['setting']->brand_color }};color:#fff;font-weight:bold}.balance td{font-weight:bold;background:#eef6f3}.avoid-break,.items-minimal tr{page-break-inside:avoid}.variant-commercial .head{background:#243047;color:#fff;border-left:0;border-top:8px solid {{ $render['setting']->brand_color }}}.variant-commercial .items-minimal th{background:{{ $render['setting']->brand_color }}}.variant-consultation .head{background:#fff;border-left:3px solid {{ $render['setting']->brand_color }};border-bottom:1px solid #cbd5e1}.variant-consultation .client td{background:#f8fafc;border:0}.variant-consultation .items-minimal th{background:#fff;color:#243047;border-bottom:2px solid #243047}.variant-client .head{border:1px solid #dbe4ed;border-left:10px solid {{ $render['setting']->brand_color }}}.variant-client .client td:first-child{background:#eef6f3}.variant-client .grand td{font-size:11px}.variant-freelancer .head{background:#eaf2ff;border-left:0;border-bottom:5px solid #2563eb}.variant-freelancer .title{color:#1d4ed8}.variant-freelancer .items-minimal th{background:#2563eb}.variant-freelancer .grand td{background:#2563eb}
</style></head><body class="variant-{{ $variant }}">
@include('invoice-templates.partials.watermark')
<table class="head"><tr><td>@include('invoice-templates.partials.company-branding',['nameClass'=>'title'])<span>{{ $invoice->company->address }}</span></td><td class="right"><strong>{{ $render['document_title'] }}</strong><br>{{ $invoice->invoice_number }}<br>{{ $invoice->issue_date?->format('d M Y') }}</td></tr></table>
<table class="client"><tr><td width="60%"><strong>{{ $variant === 'client' ? 'Client account' : 'Prepared for' }}</strong><br>{{ $invoice->billing_company ?: $invoice->billing_name }}<br>{{ $invoice->billing_address }}</td><td><strong>Reference</strong><br>{{ $invoice->billing_email ?: '—' }}<br>{{ $invoice->billing_phone ?: '—' }}</td></tr></table>
@include('invoice-templates.partials.items-minimal')
<table class="summary"><tr><td width="58%">@if($render['is_gst'] && $render['setting']->gst_presentation==='detailed')@include('invoice-templates.partials.gst-summary')@endif @if($invoice->terms_conditions)<strong>Terms</strong><br>{{ $invoice->terms_conditions }}@endif @include('invoice-templates.partials.payment-qr')</td><td>@include('invoice-templates.partials.totals')</td></tr></table>
@include('invoice-templates.partials.payment-details')
</body></html>
