@php($variant = $render['template']['variant'])
<!doctype html><html><head><style>@include('invoice-templates.partials.print-page')
body{color:#172033;font:7.4px DejaVu Sans}.right{text-align:right}.muted{color:#64748b;font-size:6.4px}table{border-collapse:collapse;width:100%}th,td{vertical-align:top}.head{border-bottom:3px solid {{ $render['setting']->brand_color }};padding-bottom:7px}.brand{font-size:14px;font-weight:bold;color:{{ $render['setting']->brand_color }}}.invoice-title{font-size:13px;font-weight:bold}.meta{margin-top:7px}.meta td{padding:5px;background:#f8fafc;border:1px solid #e2e8f0}.parties{margin-top:6px}.parties td{padding:6px;border:1px solid #cbd5e1}.items-minimal{margin-top:8px}.items-minimal th{padding:4px;background:#e2e8f0;color:#172033}.items-minimal td{padding:4px;border-bottom:1px solid #dbe4ed}.items-minimal thead{display:table-header-group}.items-minimal tr,.avoid-break{page-break-inside:avoid}.summary{margin-top:8px}.totals td{padding:4px;border-bottom:1px solid #dbe4ed}.grand td{background:{{ $render['setting']->brand_color }};color:#fff;font-weight:bold}.balance td{background:#eef6f3;font-weight:bold}.gst-summary{margin-top:8px}.gst-summary h3{font-size:8px;margin:0 0 3px}.gst-summary th,.gst-summary td{padding:3px;border:1px solid #dbe4ed}.payment-qr{display:table;margin-top:6px}.payment-qr img{width:60px;height:60px}.payment-qr img,.payment-qr div{display:table-cell;vertical-align:middle;padding-right:6px}.authorized-signature img{max-width:90px!important;max-height:34px!important}.variant-consultation .head{border-left:4px solid {{ $render['setting']->brand_color }};border-bottom:1px solid #cbd5e1;padding:7px}.variant-consultation .parties td{border:0;background:#f8fafc}.variant-creative .head{background:#352452;color:#fff;padding:9px;border-bottom:5px solid #facc15}.variant-creative .brand{color:#fff}.variant-creative .items-minimal th{background:#fef9c3}.variant-modern .head{background:#eff6ff;padding:8px}.variant-modern .items-minimal th{background:#2563eb;color:#fff}.variant-gst .head{border:2px solid #334155;padding:7px}.variant-gst .items-minimal th{background:#334155;color:#fff}.variant-boutique .head{background:#faf5ff;padding:9px;border-bottom-color:#7e22ce}.variant-boutique .brand{color:#7e22ce}.variant-boutique .grand td{background:#7e22ce}.variant-professional .head{border-top:6px solid #172033;border-bottom:1px solid #172033;padding-top:7px}.variant-professional .meta td{border:0;border-bottom:1px solid #cbd5e1}.variant-bold .head{background:#172033;color:#fff;padding:8px}.variant-bold .brand{color:#fff}.variant-bold .items-minimal th{background:#172033;color:#fff;font-size:8px}.variant-minimal .head{border-bottom:1px solid #94a3b8}.variant-minimal .meta td,.variant-minimal .parties td{background:#fff;border:0;border-bottom:1px solid #e2e8f0}.variant-minimal .items-minimal th{background:#fff;border-bottom:2px solid #172033}.variant-service .head{border-left:7px solid #0f766e;background:#f0fdfa;padding:8px}.variant-service .items-minimal th{background:#0f766e;color:#fff}.variant-service .grand td{background:#0f766e}
</style></head><body class="variant-{{ $variant }}">
<table class="head" role="presentation"><tr><td width="62%">@include('invoice-templates.partials.company-branding',['nameClass'=>'brand']){{ $invoice->company->address }}@if($render['is_gst'] && $invoice->supplier_gstin_snapshot)<br>GSTIN {{ $invoice->supplier_gstin_snapshot }}@endif</td><td class="right"><div class="invoice-title">{{ $variant === 'service' ? 'SERVICE '.($render['is_gst'] ? 'TAX INVOICE' : 'INVOICE') : ($render['is_gst'] ? 'TAX INVOICE' : 'INVOICE') }}</div><strong>{{ $invoice->invoice_number }}</strong><br>{{ str($render['setting']->copy_label)->replace('_',' ')->headline() }}</td></tr></table>
<table class="meta" role="presentation"><tr><td>Issued<br><strong>{{ $invoice->issue_date?->format('d M Y') }}</strong></td><td>Due<br><strong>{{ $invoice->due_date?->format('d M Y') ?: '—' }}</strong></td><td>Supply<br><strong>{{ $invoice->place_of_supply ?: '—' }}</strong></td></tr></table>
<table class="parties" role="presentation"><tr><td width="62%"><strong>Bill to</strong><br>{{ $invoice->billing_company ?: $invoice->billing_name }}<br>{{ $invoice->billing_address }}@if($render['is_gst'])<br>GSTIN {{ $invoice->customer_tax_number ?: '—' }}@endif</td><td><strong>Status</strong><br>{{ $invoice->status->label() }}<br><br><strong>Contact</strong><br>{{ $invoice->billing_phone ?: '—' }}</td></tr></table>
@include('invoice-templates.partials.items-minimal')
<table class="summary" role="presentation"><tr><td width="56%">@if($render['is_gst'] && $render['setting']->gst_presentation === 'detailed') @include('invoice-templates.partials.gst-summary') @elseif($render['is_gst']) <strong>GST included</strong><br>{{ number_format((float)$invoice->tax_total,2) }} @endif @include('invoice-templates.partials.payment-qr')</td><td>@include('invoice-templates.partials.totals')</td></tr></table>
@if(data_get($render,'setting.options.show_terms',true))<p class="avoid-break"><strong>Terms:</strong> {{ str($invoice->terms_conditions ?: 'Payment is due according to invoice terms.')->limit(220) }}</p>@endif
</body></html>
