@php($is58 = $render['template']['paper_format'] === 'thermal_58')
<!doctype html><html><head><style>@include('invoice-templates.partials.print-page')
body{color:#111;font:{{ $is58 ? '6.7px' : '7.8px' }} DejaVu Sans;margin:0}.right{text-align:right}.muted{color:#444;font-size:{{ $is58 ? '5.8px' : '6.8px' }}}table{border-collapse:collapse;width:100%}th,td{vertical-align:top}.receipt-head{text-align:center;border-bottom:1px dashed #111;padding-bottom:6px}.brand{font-size:{{ $is58 ? '10px' : '12px' }};font-weight:bold}.receipt-head img{max-width:{{ $is58 ? '80px' : '110px' }}!important;max-height:28px!important}.copy{margin-top:3px;font-size:6px}.meta{margin-top:6px}.meta td{padding:2px 0}.thermal-items{margin-top:7px}.thermal-items th{border-top:1px solid #111;border-bottom:1px solid #111;padding:3px 1px}.thermal-items td{padding:3px 1px;border-bottom:1px dotted #aaa}.thermal-items tr{page-break-inside:avoid}.thermal-totals{margin-top:6px;border-top:1px solid #111}.thermal-totals td{padding:2px 0}.grand td{font-size:{{ $is58 ? '8px' : '9px' }};font-weight:bold;border-top:1px solid #111}.balance td{font-weight:bold}.thermal-gst,.thermal-gst-summary{margin-top:7px;border-top:1px dotted #777;padding-top:4px}.thermal-gst div{display:flex;justify-content:space-between;margin-top:2px}.footer{margin-top:7px;border-top:1px dashed #111;padding-top:5px;text-align:center}.qr{margin:7px auto;text-align:center}.qr img{width:{{ $is58 ? '58px' : '70px' }};height:{{ $is58 ? '58px' : '70px' }}}</style></head><body>
<div class="receipt-head">@include('invoice-templates.partials.company-branding',['nameClass'=>'brand'])<div>{{ str($invoice->company->address)->limit($is58 ? 100 : 150) }}</div>@if($render['is_gst'] && $invoice->supplier_gstin_snapshot)<div>GSTIN: {{ $invoice->supplier_gstin_snapshot }}</div>@endif<div class="copy">{{ str($render['setting']->copy_label)->replace('_',' ')->headline() }}</div></div>
<table class="meta" role="presentation"><tr><td><strong>{{ $invoice->invoice_number }}</strong><br>{{ $invoice->issue_date?->format('d M Y H:i') }}</td><td class="right">{{ $invoice->status->label() }}<br>{{ $invoice->place_of_supply ?: '—' }}</td></tr>@if($invoice->billing_name)<tr><td colspan="2">Customer: {{ str($invoice->billing_company ?: $invoice->billing_name)->limit($is58 ? 34 : 48) }}@if($render['is_gst'] && $invoice->customer_tax_number)<br>Customer GSTIN: {{ $invoice->customer_tax_number }}@endif</td></tr>@endif</table>
@include('invoice-templates.partials.items-thermal')
@include('invoice-templates.partials.totals-thermal')
@include('invoice-templates.partials.gst-summary-thermal')
@if(! $is58)@include('invoice-templates.partials.authorized-signature')@endif
@if($render['payment_qr_data_uri'])<div class="qr"><img src="{{ $render['payment_qr_data_uri'] }}" alt="Payment QR"><br>Scan to pay {{ number_format((float)$invoice->balance_due,2) }}</div>@endif
<div class="footer">{{ str($invoice->terms_conditions ?: 'Thank you for your business.')->limit($is58 ? 110 : 180) }}<br>Payment: recorded against invoice balance</div>
</body></html>
