@extends('layouts.admin')
@section('title','AI & Forecasting')
@section('page-title','AI & Forecasting')
@section('content')
<div class="space-y-6">
    <section class="flex flex-col justify-between gap-4 rounded-lg border border-slate-200 bg-white p-5 shadow-sm md:flex-row md:items-end dark:border-slate-800 dark:bg-slate-900">
        <div><p class="text-xs font-semibold uppercase text-teal-700 dark:text-teal-300">Explainable, advisory only</p><h1 class="mt-1 text-xl font-semibold text-slate-950 dark:text-white">Retail insights from your operational data</h1><p class="mt-2 max-w-3xl text-sm text-slate-500 dark:text-slate-400">These deterministic forecasts do not create orders, change stock, alter prices, contact customers, or modify CRM records.</p></div>
        @can('ai.forecasts.run')<form method="POST" action="{{ route('ai.run') }}" class="flex gap-2">@csrf<select name="type" class="rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-950"><option value="all">Refresh all</option><option value="sales">Sales</option><option value="inventory">Inventory</option><option value="customers">Customers</option><option value="crm">CRM priorities</option></select><button class="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white dark:bg-teal-300 dark:text-slate-950">Recalculate</button></form>@endcan
    </section>
    <section class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        @foreach(['Latest runs' => $data['latest_runs']->count(), 'Stock risks' => $data['stock_risks']->whereIn('classification',['stockout_risk','overstock_risk'])->count(), 'CRM priorities' => $data['crm_priorities']->count(), 'Open insights' => $data['insights']->where('status','new')->count()] as $label => $value)<article class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p class="text-sm text-slate-500 dark:text-slate-400">{{ $label }}</p><p class="mt-2 text-2xl font-semibold text-slate-950 dark:text-white">{{ $value }}</p></article>@endforeach
    </section>
    <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <div class="flex flex-col justify-between gap-2 md:flex-row md:items-end"><div><h2 class="font-semibold text-slate-950 dark:text-white">Forecast runs</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">The latest six tenant forecast runs. Confidence describes the amount of available data, not a guarantee.</p></div><p class="text-xs text-slate-500 dark:text-slate-400">Last generated: {{ optional($data['latest_runs']->first()?->completed_at)->format('d M Y, H:i') ?? 'Not generated yet' }}</p></div>
        <div class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">@forelse($data['latest_runs'] as $run)<article class="rounded-lg border border-slate-200 p-4 dark:border-slate-800"><div class="flex items-center justify-between gap-3"><p class="font-medium text-slate-900 dark:text-white">{{ str($run->forecast_type)->headline() }}</p><span class="text-xs font-semibold uppercase text-slate-500">{{ str($run->status)->replace('_',' ') }}</span></div><dl class="mt-3 space-y-1 text-sm text-slate-500 dark:text-slate-400"><div class="flex justify-between gap-3"><dt>Method</dt><dd class="text-right">{{ $run->algorithm_version }}</dd></div><div class="flex justify-between gap-3"><dt>Data period</dt><dd class="text-right">{{ $run->training_start?->format('d M') }} - {{ $run->training_end?->format('d M Y') }}</dd></div><div class="flex justify-between gap-3"><dt>Data points</dt><dd>{{ number_format($run->data_points) }}</dd></div><div class="flex justify-between gap-3"><dt>Confidence</dt><dd>{{ $run->confidence_level ? str($run->confidence_level)->headline() : 'Not available' }}</dd></div></dl></article>@empty<p class="text-sm text-slate-500 dark:text-slate-400">No forecast run has been generated yet.</p>@endforelse</div>
    </section>
    <section class="grid gap-6 xl:grid-cols-2">
        <article class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold text-slate-950 dark:text-white">Sales forecast</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Completed POS sales only. Confidence reflects data quantity and consistency, not certainty.</p><div class="mt-4 space-y-3">@forelse($data['sales'] as $forecast)<div class="rounded-lg bg-slate-50 p-4 dark:bg-slate-950"><div class="flex justify-between gap-3"><span class="font-medium text-slate-900 dark:text-white">{{ $forecast->period_start?->diffInDays($forecast->period_end) + 1 }} days</span><span class="font-semibold">{{ number_format($forecast->predicted_value, 2) }}</span></div><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Range {{ number_format($forecast->lower_bound, 2) }} to {{ number_format($forecast->upper_bound, 2) }} · {{ data_get($forecast->explanation,'plain_language') }}</p></div>@empty<p class="mt-4 text-sm text-slate-500 dark:text-slate-400">Not enough completed sales history yet. Add at least {{ $settings['minimum_sales_history_days'] }} days before relying on a forecast.</p>@endforelse</div></article>
        <article class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold text-slate-950 dark:text-white">Customer segments</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Private RFM-style operational segments. No campaign is sent automatically.</p><div class="mt-4 grid grid-cols-2 gap-3">@forelse($data['customer_segments'] as $segment => $count)<div class="rounded-lg bg-slate-50 p-4 dark:bg-slate-950"><p class="text-sm text-slate-500">{{ str($segment)->replace('_',' ')->headline() }}</p><p class="mt-1 text-xl font-semibold">{{ $count }}</p></div>@empty<p class="text-sm text-slate-500">No segment snapshot exists yet.</p>@endforelse</div></article>
    </section>
    <section class="grid gap-6 xl:grid-cols-2">
        <article class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold text-slate-950 dark:text-white">Stock and reorder review</h2><div class="mt-4 space-y-3">@forelse($data['stock_risks'] as $risk)<div class="rounded-lg border border-slate-200 p-4 dark:border-slate-800"><div class="flex justify-between gap-3"><span class="font-medium">{{ $risk->product?->name ?? 'Inventory item' }}</span><span class="text-xs font-semibold uppercase text-slate-500">{{ str($risk->classification)->replace('_',' ') }}</span></div><p class="mt-1 text-sm text-slate-500">{{ data_get($risk->explanation,'plain_language') }}</p><p class="mt-2 text-xs text-slate-500">Suggested reorder: {{ data_get($risk->supporting_metrics,'suggested_reorder_quantity', 0) }}. Review before creating any purchase order.</p></div>@empty<p class="text-sm text-slate-500">No stock risks have been calculated yet.</p>@endforelse</div></article>
        <article class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold text-slate-950 dark:text-white">Follow-up priority</h2><div class="mt-4 space-y-3">@forelse($data['crm_priorities'] as $priority)<div class="rounded-lg border border-slate-200 p-4 dark:border-slate-800"><div class="flex justify-between gap-3"><a href="{{ $priority->lead ? route('crm.leads.show',$priority->lead) : '#' }}" class="font-medium">{{ $priority->lead?->title ?? 'Lead' }}</a><span class="font-semibold">{{ number_format($priority->score,0) }}/100</span></div><p class="mt-1 text-sm text-slate-500">{{ data_get($priority->explanation,'plain_language') }}</p></div>@empty<p class="text-sm text-slate-500">No active lead priority snapshot exists yet.</p>@endforelse</div></article>
    </section>
    <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold text-slate-950 dark:text-white">Recent insight history</h2><div class="mt-4 space-y-3">@forelse($data['insights'] as $insight)<div class="flex flex-col justify-between gap-3 rounded-lg border border-slate-200 p-4 md:flex-row md:items-center dark:border-slate-800"><div><p class="font-medium">{{ $insight->title }}</p><p class="mt-1 text-sm text-slate-500">{{ $insight->explanation }}</p></div>@can('ai.insights.review')<form method="POST" action="{{ route('ai.insights.review',$insight) }}" class="flex gap-2">@csrf<select name="status" class="rounded-lg border-slate-300 text-sm"><option value="reviewed">Review</option><option value="dismissed">Dismiss</option><option value="actioned">Mark actioned</option></select><button class="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold">Save</button></form>@endcan</div>@empty<p class="text-sm text-slate-500">No advisory insight exists yet. Recalculate when operational data is ready.</p>@endforelse</div></section>
</div>
@endsection
