@extends('layouts.admin')

@section('title', 'Subscription & Usage')
@section('page-title', 'Subscription & Usage')
@section('breadcrumbs')<span>/</span><span>Account</span><span>/</span><span>Subscription</span>@endsection

@section('content')
    @if(! $subscription)<section class="rounded-lg border border-amber-200 bg-amber-50 p-5 text-amber-950 shadow-sm dark:border-amber-900 dark:bg-amber-950 dark:text-amber-100"><h2 class="font-semibold">Subscription setup is pending</h2><p class="mt-2 text-sm">Please contact your account team to finish subscription setup.</p></section>@else
    <div class="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex items-start justify-between gap-4"><div><p class="text-sm text-slate-500">Current plan</p><h2 class="mt-1 text-xl font-semibold text-slate-950 dark:text-white">{{ $subscription->plan?->name ?? 'Your plan' }}</h2><p class="mt-1 text-sm text-slate-500">{{ $subscription->subscription_number }}</p></div><x-status-badge :status="$subscription->status" /></div><dl class="mt-6 grid gap-4 sm:grid-cols-3 text-sm"><div><dt class="text-slate-500">Renewal date</dt><dd class="mt-1 font-medium text-slate-900 dark:text-white">{{ $subscription->renewal_date?->format('d M Y') ?? '—' }}</dd></div><div><dt class="text-slate-500">Trial remaining</dt><dd class="mt-1 font-medium text-slate-900 dark:text-white">{{ $subscription->status === 'trialing' && $subscription->trial_ends_at ? max(0, today()->diffInDays($subscription->trial_ends_at, false)) . ' days' : '—' }}</dd></div><div><dt class="text-slate-500">Billing method</dt><dd class="mt-1 font-medium text-slate-900 dark:text-white">{{ str($subscription->billing_method)->headline() }}</dd></div></dl></section><section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold text-slate-950 dark:text-white">Need a change?</h2><p class="mt-1 text-sm text-slate-500">Requests are reviewed before your plan or billing changes.</p><form method="POST" action="{{ route('account.subscription.requests.store') }}" class="mt-4 space-y-3">@csrf<label class="block text-sm font-medium">Request<select name="type" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"><option value="upgrade">Upgrade</option><option value="downgrade">Schedule downgrade</option><option value="cancellation">Request cancellation</option></select></label><label class="block text-sm font-medium">Plan<select name="saas_plan_id" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"><option value="">Choose a plan</option>@foreach($plans as $plan)<option value="{{ $plan->id }}">{{ $plan->name }}</option>@endforeach</select></label><label class="block text-sm font-medium">Message<textarea name="message" rows="3" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></textarea></label><button class="rounded-md bg-slate-950 px-4 py-2 text-sm font-medium text-white dark:bg-teal-300 dark:text-slate-950">Submit request</button></form></section></div>
    <section class="mt-6 rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold text-slate-950 dark:text-white">Usage</h2><div class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">@foreach($usage as $name => $metric)<div class="rounded-md bg-slate-50 p-4 dark:bg-slate-800"><p class="text-sm text-slate-500">{{ str($name)->replace('_',' ')->headline() }}</p><p class="mt-1 text-lg font-semibold text-slate-950 dark:text-white">{{ number_format($metric['current']) }} <span class="text-sm font-normal text-slate-500">/ {{ $metric['limit'] === null ? 'Unlimited' : number_format($metric['limit']) }}</span></p></div>@endforeach</div></section>
    <section class="mt-6 rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold text-slate-950 dark:text-white">Subscription history</h2><div class="mt-4 divide-y divide-slate-100 dark:divide-slate-800">@forelse($subscription->events as $event)<div class="flex items-center justify-between gap-4 py-3 text-sm"><span>{{ str($event->event_key)->headline() }}</span><span class="text-slate-500">{{ $event->created_at?->format('d M Y, H:i') }}</span></div>@empty<p class="py-3 text-sm text-slate-500">No subscription activity yet.</p>@endforelse</div></section>
    @endif
@endsection
