@extends('layouts.admin')

@section('title', 'Create Account')
@section('page-title', 'Create Customer Account')
@section('breadcrumbs')<span>/</span><span>Platform</span><span>/</span><a href="{{ route('saas.onboarding.index') }}">Tenants</a><span>/</span><span>Create account</span>@endsection

@section('content')
    @include('command-center.saas.partials.nav')
    <form method="POST" action="{{ route('saas.tenants.store') }}" class="mx-auto max-w-5xl space-y-6">@csrf
        <input type="hidden" name="idempotency_key" value="{{ old('idempotency_key', $idempotencyKey) }}">
        <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
            <h2 class="font-semibold text-slate-950 dark:text-white">Owner details</h2><p class="mt-1 text-sm text-slate-500">The owner can finish their business details later. A mobile number is required for account verification.</p>
            <div class="mt-5 grid gap-4 md:grid-cols-2"><label class="text-sm font-medium">Owner name<input required name="owner_name" value="{{ old('owner_name') }}" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Mobile number<input required name="mobile" value="{{ old('mobile') }}" placeholder="+91 98765 43210" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Email address <span class="font-normal text-slate-500">(optional)</span><input type="email" name="email" value="{{ old('email') }}" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Password<input required type="password" name="password" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Confirm password<input required type="password" name="password_confirmation" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="mt-6 flex items-center gap-2 text-sm"><input type="checkbox" name="require_password_change" value="1" @checked(old('require_password_change'))> Require a password change at first sign-in</label></div>
        </section>
        <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold text-slate-950 dark:text-white">Store and package</h2><p class="mt-1 text-sm text-slate-500">A primary outlet and the selected package are created together, with no partial account if any step fails.</p><div class="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><label class="text-sm font-medium">Store name <span class="font-normal text-slate-500">(optional)</span><input name="company_name" value="{{ old('company_name') }}" placeholder="Your Store Name" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Industry<select required name="industry" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"><option value="">Select industry</option>@foreach($industries as $industry)<option value="{{ $industry->key }}" @selected(old('industry') === $industry->key)>{{ $industry->label }}</option>@endforeach</select></label><label class="text-sm font-medium">Package<select required name="saas_plan_id" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950">@foreach($plans as $plan)<option value="{{ $plan->id }}" @selected(old('saas_plan_id') == $plan->id)>{{ $plan->name }}</option>@endforeach</select></label><label class="text-sm font-medium">Primary outlet name<input name="branch_name" value="{{ old('branch_name','Main outlet') }}" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Activation date<input type="date" name="subscription_starts_at" value="{{ old('subscription_starts_at', now()->toDateString()) }}" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label></div></section>
        <div class="flex justify-end gap-3"><a href="{{ route('saas.onboarding.index') }}" class="rounded-md px-4 py-2 text-sm font-medium text-slate-600 dark:text-slate-300">Cancel</a><button class="rounded-md bg-slate-950 px-4 py-2 text-sm font-medium text-white dark:bg-teal-300 dark:text-slate-950">Create account</button></div>
    </form>
@endsection
