@extends('layouts.admin')

@section('title', 'Customer Onboarding')
@section('page-title', 'Customer Onboarding')

@section('content')
    <div class="space-y-6">
        @include('command-center.crm.partials.nav')
        <section class="flex flex-col justify-between gap-4 border-b border-slate-200 pb-6 dark:border-slate-800 sm:flex-row sm:items-end">
            <div><p class="text-sm font-semibold text-teal-700 dark:text-teal-300">Implementation workspace</p><h1 class="mt-2 text-2xl font-semibold text-slate-950 dark:text-white">Customer Onboarding</h1><p class="mt-2 max-w-2xl text-sm leading-6 text-slate-500 dark:text-slate-400">Keep every implementation, training, data request, and go-live commitment visible in one operational checklist.</p></div>
        </section>
        <section class="rounded-lg border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><form class="grid gap-3 md:grid-cols-2 xl:grid-cols-6"><input name="search" value="{{ request('search') }}" placeholder="Search customer, number, phone or email" class="xl:col-span-2"><select name="status"><option value="">All statuses</option>@foreach(\App\Enums\Crm\OnboardingStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status') === $status->value)>{{ $status->label() }}</option>@endforeach</select><select name="priority"><option value="">All priorities</option>@foreach(\App\Enums\Crm\OnboardingPriority::cases() as $priority)<option value="{{ $priority->value }}" @selected(request('priority') === $priority->value)>{{ $priority->label() }}</option>@endforeach</select><select name="owner_id"><option value="">All owners</option>@foreach($owners as $owner)<option value="{{ $owner->id }}" @selected((string) request('owner_id') === (string) $owner->id)>{{ $owner->name }}</option>@endforeach</select><select name="overdue"><option value="">All dates</option><option value="1" @selected(request('overdue'))>Target overdue</option></select><input type="date" name="target_from" value="{{ request('target_from') }}" aria-label="Target from"><input type="date" name="target_to" value="{{ request('target_to') }}" aria-label="Target to"><div class="flex gap-2 xl:col-span-2"><button class="flex-1 rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white dark:bg-teal-300 dark:text-slate-950">Apply filters</button><a href="{{ route('crm.onboarding.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 dark:border-slate-700 dark:text-slate-200">Reset</a></div></form></section>
        <section class="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="overflow-x-auto"><table class="min-w-[960px] w-full text-left text-sm"><thead class="bg-slate-50 text-xs font-semibold uppercase text-slate-500 dark:bg-slate-950"><tr><th class="px-5 py-3">Onboarding</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Progress</th><th class="px-5 py-3">Target go-live</th><th class="px-5 py-3">Owner</th><th class="px-5 py-3 text-right">Action</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($onboardings as $onboarding)<tr class="hover:bg-slate-50 dark:hover:bg-slate-800/50"><td class="px-5 py-4"><a href="{{ route('crm.onboarding.show', $onboarding) }}" class="font-semibold text-slate-950 hover:text-teal-700 dark:text-white dark:hover:text-teal-300">{{ $onboarding->onboarding_number }}</a><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">{{ $onboarding->business_name ?: $onboarding->customer?->company_name }}</p></td><td class="px-5 py-4"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700 dark:bg-slate-800 dark:text-slate-200">{{ $onboarding->status->label() }}</span></td><td class="px-5 py-4"><div class="flex items-center gap-3"><div class="h-2 w-28 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div class="h-full bg-teal-500" style="width: {{ $onboarding->progress_percent }}%"></div></div><span class="font-semibold text-slate-700 dark:text-slate-200">{{ $onboarding->progress_percent }}%</span></div></td><td class="px-5 py-4 {{ $onboarding->target_go_live_date?->isPast() && $onboarding->status->isActive() ? 'font-semibold text-rose-700 dark:text-rose-300' : 'text-slate-600 dark:text-slate-300' }}">{{ $onboarding->target_go_live_date?->format('d M Y') ?? 'Not set' }}</td><td class="px-5 py-4 text-slate-600 dark:text-slate-300">{{ $onboarding->implementationOwner?->name ?? $onboarding->assignee?->name ?? 'Unassigned' }}</td><td class="px-5 py-4 text-right"><a href="{{ route('crm.onboarding.show', $onboarding) }}" class="font-semibold text-teal-700 hover:text-teal-900 dark:text-teal-300">Open</a></td></tr>@empty<tr><td colspan="6" class="px-5 py-14 text-center text-sm text-slate-500 dark:text-slate-400">No customer onboarding records match the current filters.</td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-100 p-4 dark:border-slate-800">{{ $onboardings->links() }}</div></section>
    </div>
@endsection
