@extends('layouts.admin')

@section('title', 'Store Setup')
@section('page-title', 'Store Setup')
@section('breadcrumbs')<span>/</span><span>Getting Started</span><span>/</span><span>Store Setup</span>@endsection

@section('content')
@php($step = $displayStep)
@php($answers = $setup->answers ?? [])
<div class="mx-auto max-w-6xl space-y-6">
    <section class="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="bg-slate-950 px-5 py-6 text-white sm:px-7"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><span class="inline-flex rounded-full bg-teal-400 px-3 py-1 text-xs font-semibold text-slate-950">{{ auth()->user()->company?->saasSubscriptions()->whereHas('plan', fn($q) => $q->where('code', config('saas.free365_plan_code')))->exists() ? 'Free 365' : 'Store setup' }}</span><h1 class="mt-4 text-2xl font-semibold tracking-normal">Welcome to RetailPOS</h1><p class="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Let’s prepare {{ auth()->user()->company->name }} so you can start billing quickly. Your progress is saved every step.</p></div><div class="rounded-lg bg-white/10 px-4 py-3 text-sm"><p class="text-slate-300">Estimated time</p><p class="mt-1 font-semibold">About 5–10 minutes</p></div></div></div><div class="px-5 py-4 sm:px-7"><ol class="grid gap-2 text-xs font-semibold sm:grid-cols-3 lg:grid-cols-6" aria-label="Store setup progress">@foreach(['Sell','Products','GST','Scanner','Printer','Import'] as $number => $label)<li class="rounded-md px-3 py-2 {{ $step >= $number + 1 ? 'bg-teal-50 text-teal-800 dark:bg-teal-950 dark:text-teal-200' : 'bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-400' }}"><span class="mr-1">{{ $number + 1 }}.</span>{{ $label }}</li>@endforeach</ol></div></section>

    @if(session('status'))<div class="rounded-lg border border-teal-200 bg-teal-50 px-4 py-3 text-sm text-teal-900" role="status">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800" role="alert"><p class="font-semibold">Please review the highlighted answers.</p><ul class="mt-1 list-inside list-disc">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    <div class="grid gap-6 lg:grid-cols-[minmax(0,1fr)_280px]">
        <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm sm:p-7 dark:border-slate-800 dark:bg-slate-900">
            @if($step === 0)
                <h2 class="text-xl font-semibold text-slate-950 dark:text-white">Set up your store, your way</h2><p class="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">We’ll make explainable recommendations based on your industry. You can review every change before it is applied.</p><form class="mt-7 flex flex-wrap gap-3" method="POST" action="{{ route('onboarding.store-setup.start') }}">@csrf<button class="rounded-lg bg-slate-950 px-5 py-3 text-sm font-semibold text-white">Set Up My Store</button></form>
            @elseif($step === 1)
                <h2 class="text-xl font-semibold text-slate-950 dark:text-white">What do you sell?</h2><p class="mt-2 text-sm text-slate-500 dark:text-slate-400">We preselected your signup industry. Choose one or more business types to tailor starter categories.</p><form method="POST" action="{{ route('onboarding.store-setup.save') }}" class="mt-6 space-y-6">@csrf<input type="hidden" name="step" value="1"><div class="grid gap-3 sm:grid-cols-2">@foreach($subtypes as $key => $label)<label class="flex cursor-pointer gap-3 rounded-lg border border-slate-200 p-4 has-[:checked]:border-teal-600 has-[:checked]:bg-teal-50 dark:border-slate-800"><input type="checkbox" name="subtypes[]" value="{{ $key }}" @checked(in_array($key, old('subtypes', $answers['subtypes'] ?? []), true)) class="mt-1 rounded border-slate-300 text-teal-600"><span class="font-medium text-slate-950 dark:text-white">{{ $label }}</span></label>@endforeach<label class="flex cursor-pointer gap-3 rounded-lg border border-slate-200 p-4 has-[:checked]:border-teal-600 has-[:checked]:bg-teal-50 dark:border-slate-800"><input type="checkbox" name="subtypes[]" value="other" @checked(in_array('other', old('subtypes', $answers['subtypes'] ?? []), true)) class="mt-1 rounded border-slate-300 text-teal-600"><span class="font-medium text-slate-950 dark:text-white">Other</span></label></div><button class="rounded-lg bg-slate-950 px-5 py-3 text-sm font-semibold text-white">Continue</button></form>
            @elseif($step === 2)
                <h2 class="text-xl font-semibold text-slate-950 dark:text-white">Approximately how many products do you have?</h2><form method="POST" action="{{ route('onboarding.store-setup.save') }}" class="mt-6 space-y-3">@csrf<input type="hidden" name="step" value="2">@foreach(['under_50'=>'Fewer than 50','50_250'=>'50–250','251_1000'=>'251–1,000','1001_5000'=>'1,001–5,000','over_5000'=>'More than 5,000','unsure'=>'I’m not sure'] as $key=>$label)<label class="flex cursor-pointer items-center gap-3 rounded-lg border border-slate-200 p-4 has-[:checked]:border-teal-600 has-[:checked]:bg-teal-50 dark:border-slate-800"><input type="radio" required name="product_volume" value="{{ $key }}" @checked(old('product_volume',$answers['product_volume'] ?? '') === $key) class="text-teal-600"><span class="font-medium text-slate-950 dark:text-white">{{ $label }}</span></label>@endforeach<button class="mt-3 rounded-lg bg-slate-950 px-5 py-3 text-sm font-semibold text-white">Continue</button></form>
            @elseif($step === 3)
                <h2 class="text-xl font-semibold text-slate-950 dark:text-white">How should taxes work for your store?</h2><p class="mt-2 text-sm text-slate-500 dark:text-slate-400">GSTIN format is checked locally. RetailPOS does not verify government registration in this step.</p><form method="POST" action="{{ route('onboarding.store-setup.save') }}" class="mt-6 space-y-5">@csrf<input type="hidden" name="step" value="3"><label class="flex items-center gap-3 text-sm font-medium"><input type="hidden" name="registered" value="0"><input type="checkbox" name="registered" value="1" @checked(old('registered',$answers['tax']['registered'] ?? false)) class="rounded border-slate-300 text-teal-600">My business is registered for GST</label><div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium">GSTIN<input name="gstin" value="{{ old('gstin',$answers['tax']['gstin'] ?? '') }}" maxlength="15" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">GST state code<input name="state_code" value="{{ old('state_code',$answers['tax']['state_code'] ?? '') }}" maxlength="2" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">State name<input name="state_name" value="{{ old('state_name',$answers['tax']['state_name'] ?? '') }}" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Pricing<select name="pricing_mode" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950"><option value="inclusive">Tax-inclusive prices</option><option value="exclusive">Tax-exclusive prices</option></select></label></div><fieldset><legend class="text-sm font-medium">Common GST rates you use</legend><div class="mt-3 flex flex-wrap gap-3">@foreach(['0','5','12','18','28'] as $rate)<label class="rounded-lg border border-slate-200 px-3 py-2 text-sm dark:border-slate-800"><input type="checkbox" name="rates[]" value="{{ $rate }}" @checked(in_array($rate, old('rates',$answers['tax']['rates'] ?? []), true)) class="mr-2 rounded text-teal-600">{{ $rate }}%</label>@endforeach</div></fieldset><label class="flex items-center gap-3 text-sm"><input type="checkbox" name="interstate_sales" value="1" @checked(old('interstate_sales',$answers['tax']['interstate_sales'] ?? false)) class="rounded text-teal-600">I expect interstate sales</label><label class="flex items-center gap-3 text-sm"><input type="checkbox" name="hsn_tracking" value="1" @checked(old('hsn_tracking',$answers['tax']['hsn_tracking'] ?? false)) class="rounded text-teal-600">I need HSN or SAC tracking</label><button class="rounded-lg bg-slate-950 px-5 py-3 text-sm font-semibold text-white">Continue</button></form>
            @elseif($step === 4)
                <h2 class="text-xl font-semibold text-slate-950 dark:text-white">Will you use a barcode scanner?</h2><form method="POST" action="{{ route('onboarding.store-setup.save') }}" class="mt-6 space-y-5">@csrf<input type="hidden" name="step" value="4"><div class="space-y-3">@foreach(['already_have'=>'Yes, I already have one','plan_to_buy'=>'I plan to buy one','manual_search'=>'No, I will search products manually','unsure'=>'I’m not sure'] as $key=>$label)<label class="flex cursor-pointer items-center gap-3 rounded-lg border border-slate-200 p-4 has-[:checked]:border-teal-600 has-[:checked]:bg-teal-50 dark:border-slate-800"><input type="radio" required name="choice" value="{{ $key }}" @checked(old('choice',$answers['scanner']['choice'] ?? '') === $key) class="text-teal-600"><span class="font-medium">{{ $label }}</span></label>@endforeach</div><div class="grid gap-3 sm:grid-cols-2"><label class="flex gap-2 text-sm"><input type="checkbox" name="keyboard_input" value="1" class="rounded text-teal-600">Works like keyboard input</label><label class="flex gap-2 text-sm"><input type="checkbox" name="existing_barcodes" value="1" class="rounded text-teal-600">Products already have barcodes</label><label class="flex gap-2 text-sm"><input type="checkbox" name="generate_missing" value="1" class="rounded text-teal-600">Generate missing barcodes later</label><label class="text-sm">Preferred format<select name="format" class="ml-2 rounded border-slate-300 dark:bg-slate-950"><option value="code128">Code 128</option><option value="ean13">EAN-13</option><option value="unsure">I’m not sure</option></select></label></div>@if($flags['scanner_test_enabled'])<label class="block text-sm font-medium">Try a scanner now <span class="font-normal text-slate-500">(not saved)</span><input autocomplete="off" placeholder="Scan a sample barcode" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5 dark:border-slate-700 dark:bg-slate-950"></label>@endif<button class="rounded-lg bg-slate-950 px-5 py-3 text-sm font-semibold text-white">Continue</button></form>
            @elseif($step === 5)
                <h2 class="text-xl font-semibold text-slate-950 dark:text-white">How will you print invoices?</h2><p class="mt-2 text-sm text-slate-500">Printing depends on your browser, operating system, and installed printer. You can always change invoice designs later.</p><form method="POST" action="{{ route('onboarding.store-setup.save') }}" class="mt-6 space-y-3">@csrf<input type="hidden" name="step" value="5">@foreach(['thermal'=>'Thermal receipt printer','a4'=>'A4 printer','both'=>'Both thermal and A4','digital'=>'Digital invoice only','unsure'=>'I’m not sure'] as $key=>$label)<label class="flex cursor-pointer items-center gap-3 rounded-lg border border-slate-200 p-4 has-[:checked]:border-teal-600 has-[:checked]:bg-teal-50 dark:border-slate-800"><input type="radio" required name="type" value="{{ $key }}" @checked(old('type',$answers['printer']['type'] ?? '') === $key) class="text-teal-600"><span class="font-medium">{{ $label }}</span></label>@endforeach<label class="block text-sm font-medium">Thermal paper width<select name="thermal_width" class="ml-2 rounded border-slate-300 dark:bg-slate-950"><option value="80">80 mm</option><option value="58">58 mm</option></select></label><button class="rounded-lg bg-slate-950 px-5 py-3 text-sm font-semibold text-white">Continue</button></form>
            @elseif($step === 6)
                <h2 class="text-xl font-semibold text-slate-950 dark:text-white">Would you like to add products now?</h2><form method="POST" action="{{ route('onboarding.store-setup.save') }}" class="mt-6 space-y-3">@csrf<input type="hidden" name="step" value="6"><label class="flex cursor-pointer items-center gap-3 rounded-lg border border-slate-200 p-4"><input type="radio" name="choice" value="csv_template" checked class="text-teal-600"><span><span class="font-medium">Download a product template</span><span class="block text-sm text-slate-500">Use the safe CSV starter template.</span></span></label><label class="flex cursor-pointer items-center gap-3 rounded-lg border border-slate-200 p-4"><input type="radio" name="choice" value="manual" class="text-teal-600"><span class="font-medium">Add products manually</span></label><label class="flex cursor-pointer items-center gap-3 rounded-lg border border-slate-200 p-4"><input type="radio" name="choice" value="skip" class="text-teal-600"><span class="font-medium">Skip for now</span></label>@if($flags['product_import_enabled'])<a href="{{ route('onboarding.store-setup.template') }}" class="inline-flex rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 dark:border-slate-700 dark:text-slate-200">Download CSV template</a>@endif<button class="ml-2 rounded-lg bg-slate-950 px-5 py-3 text-sm font-semibold text-white">Review my setup plan</button></form>
            @else
                <h2 class="text-xl font-semibold text-slate-950 dark:text-white">Your Store Setup Plan</h2><p class="mt-2 text-sm text-slate-500">Review and choose the optional recommendations you want RetailPOS to apply. Existing tenant settings are never overwritten by this wizard.</p><form method="POST" action="{{ route('onboarding.store-setup.apply') }}" class="mt-6 space-y-6">@csrf<div class="rounded-lg border border-slate-200 p-4 dark:border-slate-800"><h3 class="font-semibold">Starter categories</h3><div class="mt-3 grid gap-2 sm:grid-cols-2">@foreach($setup->recommendations['categories'] ?? [] as $category)<label class="flex gap-2 text-sm"><input type="checkbox" name="categories[]" value="{{ $category['name'] }}" checked class="rounded text-teal-600"><span><strong>{{ $category['name'] }}</strong><span class="block text-slate-500">{{ $category['reason'] }}</span></span></label>@endforeach</div></div><div class="grid gap-4 sm:grid-cols-2"><label class="rounded-lg border border-slate-200 p-4 dark:border-slate-800"><input type="checkbox" name="apply_tax" value="1" checked class="mr-2 rounded text-teal-600"><strong>Tax settings</strong><span class="mt-1 block text-sm text-slate-500">{{ $setup->recommendations['tax']['reason'] ?? '' }}</span></label><label class="rounded-lg border border-slate-200 p-4 dark:border-slate-800"><input type="checkbox" name="apply_template" value="1" checked class="mr-2 rounded text-teal-600"><strong>{{ $setup->recommendations['invoice_template']['name'] ?? 'Invoice design' }}</strong><span class="mt-1 block text-sm text-slate-500">{{ $setup->recommendations['invoice_template']['reason'] ?? '' }}</span></label><label class="rounded-lg border border-slate-200 p-4 dark:border-slate-800"><input type="checkbox" name="apply_barcode" value="1" checked class="mr-2 rounded text-teal-600"><strong>Barcode defaults</strong><span class="mt-1 block text-sm text-slate-500">{{ $setup->recommendations['barcode']['reason'] ?? '' }}</span></label><div class="rounded-lg border border-slate-200 p-4 dark:border-slate-800"><strong>Product entry</strong><span class="mt-1 block text-sm text-slate-500">{{ $setup->recommendations['product_entry']['reason'] ?? '' }}</span></div></div><div class="rounded-lg border border-slate-200 p-4 dark:border-slate-800"><h3 class="font-semibold">Recommended modules</h3><div class="mt-3 grid gap-3 sm:grid-cols-2">@foreach($setup->recommendations['modules'] ?? [] as $module)<div class="text-sm"><strong>{{ $module['label'] }}</strong>@if($module['locked'])<span class="ml-2 rounded bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-600 dark:bg-slate-800">Available on upgrade</span>@endif<p class="mt-1 text-slate-500">{{ $module['reason'] }}</p></div>@endforeach</div></div><button class="rounded-lg bg-slate-950 px-5 py-3 text-sm font-semibold text-white">Prepare My Store</button></form>
            @endif
        </section>
        <aside class="space-y-4"><section class="rounded-lg border border-slate-200 bg-white p-5 text-sm shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold text-slate-950 dark:text-white">Your setup</h2><dl class="mt-4 space-y-3"><div><dt class="text-slate-500">Store</dt><dd class="font-medium">{{ auth()->user()->company->name }}</dd></div><div><dt class="text-slate-500">Industry</dt><dd class="font-medium">{{ str($setup->industry_key)->replace('_',' ')->headline() }}</dd></div><div><dt class="text-slate-500">Progress</dt><dd class="font-medium">{{ min($setup->current_step, 6) }} of 6 questions</dd></div></dl></section>@if($step > 1)<a href="{{ route('onboarding.store-setup.show', ['step' => $step - 1]) }}" class="block w-full rounded-lg border border-slate-300 px-4 py-2.5 text-center text-sm font-semibold text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:text-slate-200 dark:hover:bg-slate-800">Back</a>@endif<form method="POST" action="{{ route('onboarding.store-setup.skip') }}">@csrf<button class="w-full rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:text-slate-200 dark:hover:bg-slate-800">I’ll Do This Later</button></form></aside>
    </div>
</div>
@endsection
