@extends('layouts.admin')
@section('title', 'New Purchase Invoice')
@section('page-title', 'New Purchase Invoice')
@section('content')
@include('command-center.purchases.partials.nav')
<form method="POST" action="{{ route('purchases.invoices.store') }}" class="space-y-5">@csrf
<section class="grid gap-4 rounded-lg border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-2 dark:border-slate-800 dark:bg-slate-900"><label class="text-sm font-medium">Supplier<select name="supplier_id" required class="mt-1 block w-full rounded-md border-slate-300"><option value="">Choose supplier</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->name }}</option>@endforeach</select></label><label class="text-sm font-medium">Supplier invoice number<input name="supplier_invoice_number" required class="mt-1 block w-full rounded-md border-slate-300" value="{{ old('supplier_invoice_number') }}"></label><label class="text-sm font-medium">Supplier invoice date<input type="date" name="supplier_invoice_date" required class="mt-1 block w-full rounded-md border-slate-300" value="{{ old('supplier_invoice_date', now()->toDateString()) }}"></label><label class="text-sm font-medium">Due date<input type="date" name="due_date" class="mt-1 block w-full rounded-md border-slate-300"></label><input type="hidden" name="idempotency_key" value="{{ (string) str()->uuid() }}"></section>
<section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="text-base font-semibold">Accepted GRN lines</h2><p class="mt-1 text-sm text-slate-500">Enter only the quantity being invoiced. The server enforces each line’s remaining accepted quantity.</p><div class="mt-4 overflow-x-auto"><table class="min-w-full text-sm"><thead><tr class="text-left text-xs uppercase text-slate-500"><th class="py-2">Use</th><th>GRN / product</th><th>Accepted</th><th>Invoice qty</th><th>Unit price</th><th>Tax %</th></tr></thead><tbody>@php($index=0)@foreach($receipts as $receipt)@foreach($receipt->items as $line)<tr class="border-t"><td class="py-3"><input type="checkbox" onchange="this.closest('tr').querySelectorAll('input[type=number]').forEach(i=>i.disabled=!this.checked)"></td><td>{{ $receipt->grn_number }} · {{ $line->product?->name }}</td><td>{{ $line->accepted_quantity }}</td><td><input disabled type="number" step="0.001" name="items[{{ $index }}][quantity]" class="w-24 rounded border-slate-300" value="{{ $line->accepted_quantity }}"><input type="hidden" name="items[{{ $index }}][goods_receipt_item_id]" value="{{ $line->id }}"><input type="hidden" name="items[{{ $index }}][name_snapshot]" value="{{ $line->product?->name }}"></td><td><input disabled type="number" step="0.01" name="items[{{ $index }}][unit_price]" class="w-24 rounded border-slate-300" value="{{ $line->unit_cost }}"></td><td><input disabled type="number" step="0.001" name="items[{{ $index }}][tax_rate]" class="w-20 rounded border-slate-300" value="0"></td></tr>@php($index++)@endforeach@endforeach</tbody></table></div></section><button class="rounded-md bg-slate-950 px-4 py-2 text-sm font-medium text-white dark:bg-teal-300 dark:text-slate-950">Save draft</button></form>
@endsection
