@extends('layouts.admin')
@section('title', 'Purchase Invoices')
@section('page-title', 'Purchase Invoices')
@section('content')
    @include('command-center.purchases.partials.nav')
    <div class="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p class="text-sm text-slate-500">Approved supplier liability: ₹{{ number_format((float) $payable['outstanding'], 2) }} · Advances: ₹{{ number_format((float) $payable['advances'], 2) }}</p></div>@can('purchase-invoices.create')<a href="{{ route('purchases.invoices.create') }}" class="rounded-md bg-slate-950 px-4 py-2 text-sm font-medium text-white dark:bg-teal-300 dark:text-slate-950">New invoice from GRN</a>@endcan</div>
    <form class="mb-4 grid gap-3 rounded-lg border border-slate-200 bg-white p-4 md:grid-cols-3 dark:border-slate-800 dark:bg-slate-900"><select name="supplier_id" class="rounded-md border-slate-300 text-sm"><option value="">All suppliers</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected(request('supplier_id') == $supplier->id)>{{ $supplier->name }}</option>@endforeach</select><select name="status" class="rounded-md border-slate-300 text-sm"><option value="">All statuses</option>@foreach(['draft','pending_verification','approved','partially_paid','paid','overdue','disputed','cancelled'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ str($status)->headline() }}</option>@endforeach</select><button class="rounded-md border border-slate-300 px-3 py-2 text-sm">Filter</button></form>
    <section class="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500 dark:bg-slate-800"><tr><th class="px-5 py-3">Invoice</th><th class="px-5 py-3">Supplier</th><th class="px-5 py-3">Supplier invoice</th><th class="px-5 py-3">Status</th><th class="px-5 py-3 text-right">Outstanding</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($invoices as $invoice)<tr><td class="px-5 py-3 font-medium"><a href="{{ route('purchases.invoices.show', $invoice) }}">{{ $invoice->invoice_number }}</a></td><td class="px-5 py-3">{{ $invoice->supplier->name }}</td><td class="px-5 py-3">{{ $invoice->supplier_invoice_number }}</td><td class="px-5 py-3"><span class="rounded-full bg-slate-100 px-2 py-1 text-xs">{{ str($invoice->status)->headline() }}</span></td><td class="px-5 py-3 text-right">₹{{ number_format((float) $invoice->outstanding_total,2) }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-slate-500">No purchase invoices yet. Create one from an accepted goods receipt.</td></tr>@endforelse</tbody></table></div><div class="border-t p-4">{{ $invoices->links() }}</div></section>
@endsection
