@extends('layouts.admin')
@section('title', $invoice->invoice_number)
@section('page-title', $invoice->invoice_number)
@section('content')
@include('command-center.purchases.partials.nav')
<div class="mb-5 flex flex-wrap justify-between gap-3"><div><p class="text-sm text-slate-500">{{ $invoice->supplier->name }} · {{ $invoice->supplier_invoice_number }} · {{ str($invoice->status)->headline() }}</p></div><div class="flex gap-2">@can('purchase-invoices.verify')@if($invoice->status==='draft')<form method="POST" action="{{ route('purchases.invoices.verify',$invoice) }}">@csrf<button class="rounded-md border px-3 py-2 text-sm">Verify</button></form>@endif@endcan @can('purchase-invoices.approve')@if(in_array($invoice->status,['draft','pending_verification']))<form method="POST" action="{{ route('purchases.invoices.approve',$invoice) }}">@csrf<button class="rounded-md bg-slate-950 px-3 py-2 text-sm text-white">Approve</button></form>@endif@endcan</div></div>
<section class="rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Product</th><th class="px-5 py-3 text-right">Qty</th><th class="px-5 py-3 text-right">Taxable</th><th class="px-5 py-3 text-right">GST</th><th class="px-5 py-3 text-right">Total</th></tr></thead><tbody>@foreach($invoice->items as $item)<tr class="border-t"><td class="px-5 py-3">{{ $item->name_snapshot }}</td><td class="px-5 py-3 text-right">{{ $item->quantity }}</td><td class="px-5 py-3 text-right">₹{{ number_format((float)$item->taxable_value,2) }}</td><td class="px-5 py-3 text-right">₹{{ number_format((float)$item->cgst_amount+(float)$item->sgst_amount+(float)$item->igst_amount,2) }}</td><td class="px-5 py-3 text-right">₹{{ number_format((float)$item->line_total,2) }}</td></tr>@endforeach</tbody><tfoot class="border-t font-semibold"><tr><td colspan="4" class="px-5 py-3 text-right">Outstanding</td><td class="px-5 py-3 text-right">₹{{ number_format((float)$invoice->outstanding_total,2) }}</td></tr></tfoot></table></div></section>
@can('purchase-invoices.cancel')@if(!in_array($invoice->status,['cancelled','paid']) && (float)$invoice->paid_total===0)<form method="POST" action="{{ route('purchases.invoices.cancel',$invoice) }}" class="mt-5 flex gap-2">@csrf<input required name="reason" placeholder="Cancellation reason" class="rounded border-slate-300"><button class="rounded border border-rose-300 px-3 py-2 text-sm text-rose-700">Cancel invoice</button></form>@endif@endcan
@endsection
