<?php
namespace App\Http\Controllers\CommandCenter\Compliance;
use App\Http\Controllers\Controller; use App\Models\Compliance\GstDocumentSeries; use App\Models\Compliance\GstEwayReadiness; use App\Models\Compliance\GstExportLog; use App\Models\Compliance\GstReturnPeriod; use App\Models\Compliance\GstSetting; use App\Models\Crm\CrmInvoice; use App\Services\AuditLogger; use App\Services\Compliance\GstExportService; use Illuminate\Http\Request; use Illuminate\Http\Response; use Illuminate\View\View;
class GstComplianceController extends Controller {
public function dashboard(Request $r):View{$company=$r->user()->company_id;$invoices=CrmInvoice::query()->where('company_id',$company)->where('status','issued');$totals=(clone $invoices)->selectRaw('sum(taxable_total) taxable,sum(cgst_total) cgst,sum(sgst_total) sgst,sum(igst_total) igst,sum(cess_total) cess')->first();return view('command-center.compliance.gst.dashboard',['settings'=>GstSetting::firstOrCreate(['company_id'=>$company],['legal_name'=>$r->user()->company->name]),'totals'=>$totals,'periods'=>GstReturnPeriod::where('company_id',$company)->latest('period')->limit(5)->get(),'exports'=>GstExportLog::where('company_id',$company)->latest()->limit(5)->get(),'warnings'=>(clone $invoices)->whereNull('place_of_supply_state_code')->count()]);}
public function reports(Request $r,string $report='outward-supplies'):View{$allowed=['outward-supplies','b2b','b2c','hsn','tax-summary','notes','documents','e-invoice','e-way-bill'];abort_unless(in_array($report,$allowed,true),404);$rows=CrmInvoice::query()->where('company_id',$r->user()->company_id)->where('status','issued')->when($r->filled('from'),fn($q)=>$q->whereDate('issue_date','>=',$r->input('from')))->when($r->filled('to'),fn($q)=>$q->whereDate('issue_date','<=',$r->input('to')))->latest('issue_date')->paginate(50)->withQueryString();return view('command-center.compliance.gst.reports',compact('rows','report'));}
public function exports(Request $r):View{return view('command-center.compliance.gst.exports',['exports'=>GstExportLog::where('company_id',$r->user()->company_id)->latest()->paginate(25)]);}
public function downloadExport(Request $r,GstExportService $exports):Response{$d=$r->validate(['period'=>['nullable','regex:/^\d{4}-\d{2}$/'],'format'=>['required','in:csv,json'],'draft_export'=>['required','boolean']]);$data=$exports->outward($r->user(),$d['period']??null);if($data['warnings']&&!$d['draft_export'])return response(['message'=>'Resolve validation warnings or explicitly choose draft export.','warnings'=>$data['warnings']],422);$exports->log($r->user(),'gstr1_outward',$d['period']??null,$d['format'],(bool)$d['draft_export'],$data['rows']->count(),$data['warnings']);if($d['format']==='json')return response()->json(['review_before_filing'=>true,'schema'=>'retailpos.gstr1.outward.v1','warnings'=>$data['warnings'],'data'=>$data['rows']->values()]);$out=fopen('php://temp','r+');fputcsv($out,['Review before filing']);fputcsv($out,array_keys($data['rows']->first()??['invoice_number'=>null]));foreach($data['rows']as$row)fputcsv($out,$row);rewind($out);return response(stream_get_contents($out),200,['Content-Type'=>'text/csv','Content-Disposition'=>'attachment; filename="gstr1-outward.csv"']);}
public function guide():View{return view('command-center.compliance.gst.guide');}
public function periods(Request $r):View{return view('command-center.compliance.gst.periods',['periods'=>GstReturnPeriod::where('company_id',$r->user()->company_id)->latest('period')->get()]);}
public function transitionPeriod(Request $r,GstReturnPeriod $period,AuditLogger $audit){abort_unless($period->company_id===$r->user()->company_id,404);$d=$r->validate(['status'=>['required','in:under_review,accountant_approved,locked,open'],'reason'=>['nullable','required_if:status,open','string','max:1000']]);if($period->status==='locked'&&$d['status']!=='open')abort(422,'Locked periods must be reopened first.');$period->update(['status'=>$d['status'],'reviewed_by'=>in_array($d['status'],['under_review','accountant_approved'])?$r->user()->id:$period->reviewed_by,'reviewed_at'=>in_array($d['status'],['under_review','accountant_approved'])?now():$period->reviewed_at,'locked_by'=>$d['status']==='locked'?$r->user()->id:null,'locked_at'=>$d['status']==='locked'?now():null,'reopen_reason'=>$d['status']==='open'?$d['reason']:null]);$audit->record('compliance.gst.period_'.$d['status'],$period,'GST period status changed',['company_id'=>$period->company_id]);return back()->with('status','Period status updated.');}
public function series(Request $r):View{return view('command-center.compliance.gst.series',['series'=>GstDocumentSeries::where('company_id',$r->user()->company_id)->get()]);}
public function eway(Request $r):View{return view('command-center.compliance.gst.eway',['records'=>GstEwayReadiness::where('company_id',$r->user()->company_id)->latest()->paginate(25)]);}
}
