@extends('layouts.admin')
@section('title', 'Owner Command Center')
@section('page-title', 'Owner Command Center')
@section('content')
@php
    $money = fn ($value) => $value === null ? 'Unavailable' : 'INR '.number_format(((int) $value) / 100, 2);
    $metric = fn (array $kpi) => $kpi['value'] === null ? 'Unavailable' : ($kpi['format'] === 'percent' ? number_format((float) $kpi['value'], 2).'%' : $money($kpi['value']));
    $query = request()->except('page');
    $reportUrl = fn (string $report) => route('reports.show', [$report] + $query);
    $greetingHour = now($executive['range']['timezone'])->hour;
    $greeting = $greetingHour < 12 ? 'Good morning' : ($greetingHour < 17 ? 'Good afternoon' : 'Good evening');
    $accentClasses = [
        'teal' => 'border-t-teal-500 bg-teal-50/50 dark:bg-teal-950/20', 'emerald' => 'border-t-emerald-500 bg-emerald-50/50 dark:bg-emerald-950/20',
        'sky' => 'border-t-sky-500 bg-sky-50/50 dark:bg-sky-950/20', 'indigo' => 'border-t-indigo-500 bg-indigo-50/50 dark:bg-indigo-950/20',
        'amber' => 'border-t-amber-500 bg-amber-50/50 dark:bg-amber-950/20', 'rose' => 'border-t-rose-500 bg-rose-50/50 dark:bg-rose-950/20',
        'violet' => 'border-t-violet-500 bg-violet-50/50 dark:bg-violet-950/20', 'slate' => 'border-t-slate-500 bg-slate-50 dark:bg-slate-900',
    ];
@endphp

<div class="space-y-6" data-owner-command-center>
    <header class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-6">
        <div class="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between">
            <div class="min-w-0"><p class="text-sm font-semibold text-teal-700 dark:text-teal-300">{{ $greeting }}, {{ auth()->user()->name }}</p><h1 class="mt-1 text-2xl font-semibold text-slate-950 dark:text-white">{{ auth()->user()->company?->name ?? 'Business performance' }}</h1><p class="mt-2 text-sm text-slate-500 dark:text-slate-400">A verified view of sales, margin, obligations, tax, stock, and team execution.</p></div>
            <div class="flex flex-wrap gap-2">
                @can('crm.reports.export')<a href="{{ route('reports.executive.export', $query) }}" class="inline-flex min-h-11 items-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700 transition hover:border-slate-400 hover:bg-slate-50 focus:outline-none focus:ring-4 focus:ring-teal-500/15 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-200 dark:hover:bg-slate-800"><x-icon name="download" class="size-4" /> Export</a>@endcan
                <a href="{{ route('reports.index', $query) }}" class="inline-flex min-h-11 items-center gap-2 rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white transition hover:bg-slate-800 focus:outline-none focus:ring-4 focus:ring-teal-500/20 dark:bg-teal-300 dark:text-slate-950 dark:hover:bg-teal-200"><x-icon name="refresh" class="size-4" /> Refresh</a>
            </div>
        </div>

        <form action="{{ route('reports.index') }}" class="mt-6 grid gap-3 border-t border-slate-200 pt-5 sm:grid-cols-2 xl:grid-cols-[minmax(10rem,1fr)_minmax(10rem,1fr)_minmax(8.5rem,0.8fr)_minmax(8.5rem,0.8fr)_auto] dark:border-slate-800">
            <label class="grid gap-1 text-xs font-semibold text-slate-600 dark:text-slate-300" for="executive-outlet">Outlet<select id="executive-outlet" name="outlet_id" class="text-sm"><option value="">Current outlet</option>@if($canViewAllOutlets)<option value="all" @selected(request('outlet_id') === 'all')>All outlets</option>@endif @foreach($outlets as $outlet)<option value="{{ $outlet->id }}" @selected((string) request('outlet_id') === (string) $outlet->id)>{{ $outlet->name }}</option>@endforeach</select></label>
            <label class="grid gap-1 text-xs font-semibold text-slate-600 dark:text-slate-300" for="executive-warehouse">Warehouse<select id="executive-warehouse" name="warehouse_id" class="text-sm"><option value="">All warehouses</option>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}" @selected((string) request('warehouse_id') === (string) $warehouse->id)>{{ $warehouse->name }}</option>@endforeach</select></label>
            <label class="grid gap-1 text-xs font-semibold text-slate-600 dark:text-slate-300" for="executive-date-from">From<input id="executive-date-from" type="date" name="date_from" value="{{ request('date_from', $executive['range']['from']->toDateString()) }}" class="text-sm"></label>
            <label class="grid gap-1 text-xs font-semibold text-slate-600 dark:text-slate-300" for="executive-date-to">To<input id="executive-date-to" type="date" name="date_to" value="{{ request('date_to', $executive['range']['to']->toDateString()) }}" class="text-sm"></label>
            <div class="flex flex-col justify-end gap-2 sm:flex-row sm:items-end xl:flex-col xl:items-stretch"><input type="hidden" name="compare" value="0"><label class="inline-flex min-h-11 items-center gap-2 whitespace-nowrap rounded-lg border border-slate-200 px-3 text-sm font-medium text-slate-700 dark:border-slate-700 dark:text-slate-200"><input type="checkbox" name="compare" value="1" class="size-4" @checked($executive['compare'])> Compare previous</label><button class="min-h-11 rounded-lg bg-teal-600 px-4 text-sm font-semibold text-white transition hover:bg-teal-700 focus:outline-none focus:ring-4 focus:ring-teal-500/20 dark:bg-teal-300 dark:text-slate-950">Apply</button></div>
        </form>
        <p class="mt-3 text-xs text-slate-500 dark:text-slate-400">{{ $executive['scope']['label'] }} · {{ $executive['range']['from']->format('d M Y') }} to {{ $executive['range']['to']->format('d M Y') }} · {{ $executive['range']['timezone'] }}@if($executive['comparison_label']) · compared with {{ $executive['comparison_label'] }}@endif</p>
    </header>

    <section aria-label="Executive key performance indicators" class="grid auto-cols-[minmax(10.75rem,1fr)] grid-flow-col gap-3 overflow-x-auto pb-2 sm:grid-flow-row sm:grid-cols-2 sm:overflow-visible xl:grid-cols-4 2xl:grid-cols-8">
        @foreach($executive['kpis'] as $kpi)
            @php($url = $kpi['report'] ? route($kpi['route'], [$kpi['report']] + $query) : route($kpi['route'], $query))
            @php($change = $kpi['change'])
            <a href="{{ $url }}" class="min-h-40 rounded-lg border border-t-4 border-slate-200 p-4 shadow-sm transition hover:-translate-y-0.5 hover:border-slate-300 hover:shadow-md focus:outline-none focus:ring-4 focus:ring-teal-500/15 dark:border-slate-800 {{ $accentClasses[$kpi['accent']] }}"><div class="flex min-h-8 items-start justify-between gap-2"><p class="text-xs font-semibold uppercase text-slate-500 dark:text-slate-400">{{ $kpi['label'] }}</p>@if($kpi['sparkline'])<x-reports.sparkline :values="$kpi['sparkline']" :tone="$kpi['accent']" class="shrink-0" />@endif</div><p class="mt-4 break-words text-xl font-semibold text-slate-950 dark:text-white">{{ $metric($kpi) }}</p><p class="mt-3 text-xs font-medium {{ $change === null ? 'text-slate-400' : ((float) $change >= 0 ? 'text-emerald-700 dark:text-emerald-300' : 'text-rose-700 dark:text-rose-300') }}">{{ $change === null ? ($executive['compare'] ? 'No comparable baseline' : 'Comparison off') : (((float) $change >= 0 ? '↑ ' : '↓ ').number_format(abs((float) $change), 1).($kpi['change_unit'] === 'points' ? ' pts' : '%').' vs previous') }}</p></a>
        @endforeach
    </section>

    <section class="grid gap-6 xl:grid-cols-[minmax(0,1.55fr)_minmax(18rem,0.45fr)]">
        <article class="min-w-0 rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-6"><div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p class="text-xs font-semibold uppercase text-teal-700 dark:text-teal-300">Performance trajectory</p><h2 class="mt-1 text-lg font-semibold text-slate-950 dark:text-white">Revenue vs gross profit</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">{{ ucfirst($executive['charts']['profitability']['granularity']) }} movement from immutable sale-time profitability snapshots.</p></div>@can('reports.profitability.view')<a href="{{ $reportUrl('profitability') }}" class="text-sm font-semibold text-teal-700 hover:text-teal-800 dark:text-teal-300">Open profitability →</a>@endcan</div><x-reports.line-chart class="mt-5" :points="$executive['charts']['profitability']['points']" />@unless($executive['profitability_available'])<p class="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-100">Gross-profit data is permission controlled. Net sales remain visible from authorized operational reporting.</p>@endunless</article>
        <aside class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-6"><div class="flex items-center justify-between gap-3"><div><p class="text-xs font-semibold uppercase text-slate-500">Executive signals</p><h2 class="mt-1 text-lg font-semibold text-slate-950 dark:text-white">What needs attention</h2></div><x-icon name="activity" class="size-5 text-teal-600 dark:text-teal-300" /></div><div class="mt-5 space-y-3">@forelse($executive['insights'] as $insight)@php($insightUrl = $insight['report'] ? route($insight['route'], [$insight['report']] + $query) : route($insight['route'], $query))<a href="{{ $insightUrl }}" class="block rounded-lg border p-4 transition hover:shadow-sm {{ $insight['tone'] === 'warning' ? 'border-amber-200 bg-amber-50/70 dark:border-amber-900 dark:bg-amber-950/20' : ($insight['tone'] === 'positive' ? 'border-emerald-200 bg-emerald-50/70 dark:border-emerald-900 dark:bg-emerald-950/20' : 'border-slate-200 bg-slate-50 dark:border-slate-800 dark:bg-slate-950/50') }}"><p class="text-sm font-semibold text-slate-900 dark:text-white">{{ $insight['title'] }}</p><p class="mt-1 text-xs leading-5 text-slate-600 dark:text-slate-300">{{ $insight['message'] }}</p></a>@empty<div class="rounded-lg border border-dashed border-slate-300 p-5 text-center dark:border-slate-700"><p class="text-sm font-semibold text-slate-700 dark:text-slate-200">No material signal yet</p><p class="mt-1 text-xs text-slate-500">Insights appear only when the selected data supports a clear action.</p></div>@endforelse</div></aside>
    </section>

    <section class="grid gap-6 xl:grid-cols-[minmax(0,1.25fr)_minmax(20rem,0.75fr)]">
        <article class="min-w-0 rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-6"><div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p class="text-xs font-semibold uppercase text-sky-700 dark:text-sky-300">Operating flow</p><h2 class="mt-1 text-lg font-semibold text-slate-950 dark:text-white">Sales vs purchases</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Completed POS sales after returns compared with authorized net purchases.</p></div><a href="{{ $reportUrl('purchases') }}" class="text-sm font-semibold text-teal-700 dark:text-teal-300">Purchase detail →</a></div><x-reports.bar-chart class="mt-5" :points="$executive['charts']['operations']['points']" />@php($operationTotals = collect($executive['charts']['operations']['points']))<dl class="mt-5 grid gap-3 border-t border-slate-200 pt-4 sm:grid-cols-3 dark:border-slate-800"><div><dt class="text-xs text-slate-500">Net sales</dt><dd class="mt-1 font-semibold text-slate-950 dark:text-white">{{ $money($operationTotals->sum('sales')) }}</dd></div><div><dt class="text-xs text-slate-500">Net purchases</dt><dd class="mt-1 font-semibold text-slate-950 dark:text-white">{{ $money($operationTotals->sum('purchases')) }}</dd></div><div><dt class="text-xs text-slate-500">Variance</dt><dd class="mt-1 font-semibold {{ $operationTotals->sum('variance') >= 0 ? 'text-emerald-700 dark:text-emerald-300' : 'text-rose-700 dark:text-rose-300' }}">{{ $money($operationTotals->sum('variance')) }}</dd></div></dl></article>
        <article class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-6"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-semibold uppercase text-violet-700 dark:text-violet-300">Compliance snapshot</p><h2 class="mt-1 text-lg font-semibold text-slate-950 dark:text-white">GST position</h2></div><a href="{{ $reportUrl('gst') }}" class="text-sm font-semibold text-teal-700 dark:text-teal-300">Review →</a></div><dl class="mt-6 space-y-4"><div class="flex items-center justify-between gap-4 border-b border-slate-100 pb-4 dark:border-slate-800"><dt class="text-sm text-slate-500">Output GST</dt><dd class="font-semibold text-slate-950 dark:text-white">{{ $money($executive['gst']['output']) }}</dd></div><div class="flex items-center justify-between gap-4 border-b border-slate-100 pb-4 dark:border-slate-800"><dt class="text-sm text-slate-500">Input GST</dt><dd class="font-semibold text-slate-950 dark:text-white">{{ $money($executive['gst']['input']) }}</dd></div><div class="flex items-center justify-between gap-4"><dt><span class="block text-sm font-semibold text-slate-800 dark:text-slate-100">{{ $executive['gst']['net'] >= 0 ? 'Net payable' : 'Input credit position' }}</span><span class="mt-1 block text-xs text-slate-500">Preparation view, not a filed return.</span></dt><dd class="text-lg font-semibold {{ $executive['gst']['net'] >= 0 ? 'text-amber-700 dark:text-amber-300' : 'text-emerald-700 dark:text-emerald-300' }}">{{ $money(abs($executive['gst']['net'])) }}</dd></div></dl>@if($executive['gst']['incomplete_count'])<p class="mt-5 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-100">{{ $executive['gst']['incomplete_count'] }} invoice(s) need place-of-supply review.</p>@endif</article>
    </section>

    <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-6">
        <div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p class="text-xs font-semibold uppercase text-amber-700 dark:text-amber-300">Working capital</p><h2 class="mt-1 text-lg font-semibold text-slate-950 dark:text-white">Financial position</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Open customer and supplier balances within the selected authorized period.</p></div><div class="flex gap-4 text-sm"><a href="{{ $reportUrl('outstanding') }}" class="font-semibold text-teal-700 dark:text-teal-300">Receivables →</a><a href="{{ route('purchases.reports.index') }}" class="font-semibold text-teal-700 dark:text-teal-300">Payables →</a></div></div>
        <dl class="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
            @foreach([
                ['Receivables', $executive['financial']['receivables'], 'bg-sky-500'],
                ['Overdue receivables', $executive['financial']['overdue_receivables'], 'bg-amber-500'],
                ['Payables', $executive['financial']['payables'], 'bg-violet-500'],
                ['Overdue payables', $executive['financial']['overdue_payables'], 'bg-rose-500'],
            ] as [$label, $value, $tone])
                <div class="rounded-lg border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-950/50"><div class="mb-3 h-1.5 w-10 rounded-full {{ $tone }}"></div><dt class="text-xs font-semibold uppercase text-slate-500 dark:text-slate-400">{{ $label }}</dt><dd class="mt-2 text-lg font-semibold text-slate-950 dark:text-white">{{ $money($value) }}</dd></div>
            @endforeach
        </dl>
    </section>

    <section class="grid gap-6 xl:grid-cols-2">
        @foreach(['top' => ['Top products', 'Highest net sales in the selected period.'], 'slow' => ['Slow-moving products', 'Lowest positive movement among sold products.']] as $productGroup => [$title, $description])
            @php($productMaximum = max(1, (int) collect($executive['products'][$productGroup])->max('net_sales')))
            <article class="min-w-0 rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">
                <div class="flex items-start justify-between gap-3 border-b border-slate-200 p-5 dark:border-slate-800 sm:p-6"><div><p class="text-xs font-semibold uppercase text-indigo-700 dark:text-indigo-300">Product intelligence</p><h2 class="mt-1 text-lg font-semibold text-slate-950 dark:text-white">{{ $title }}</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">{{ $description }}</p></div>@can('reports.profitability.view')<a href="{{ $reportUrl('profitability') }}" class="shrink-0 text-sm font-semibold text-teal-700 dark:text-teal-300">Details →</a>@endcan</div>
                <div class="hidden sm:block">
                    <table class="w-full table-fixed text-left text-xs xl:text-sm"><thead class="bg-slate-50 text-[0.65rem] uppercase text-slate-500 dark:bg-slate-950/60 dark:text-slate-400"><tr><th class="w-[34%] px-4 py-3 font-semibold">Product</th><th class="w-[12%] px-2 py-3 text-right font-semibold">Qty</th><th class="w-[20%] px-2 py-3 text-right font-semibold">Net sales</th><th class="w-[20%] px-2 py-3 text-right font-semibold">Profit</th><th class="w-[14%] px-4 py-3 text-right font-semibold">Margin</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($executive['products'][$productGroup] as $row)<tr class="hover:bg-slate-50/70 dark:hover:bg-slate-800/40"><td class="px-4 py-3"><span class="block truncate font-semibold text-slate-900 dark:text-white" title="{{ $row['dimension'] }}">{{ $row['dimension'] }}</span><span class="mt-0.5 block truncate text-[0.65rem] text-slate-500">{{ $row['sku'] ?: 'No SKU' }}</span><span class="mt-2 block h-1.5 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><span class="block h-full rounded-full bg-indigo-500" style="width: {{ max(3, min(100, ((int) $row['net_sales'] / $productMaximum) * 100)) }}%"></span></span></td><td class="px-2 py-3 text-right text-slate-600 dark:text-slate-300">{{ number_format((float) $row['net_quantity'], 3) }}</td><td class="px-2 py-3 text-right font-medium text-slate-900 dark:text-white">{{ $money($row['net_sales']) }}</td><td class="px-2 py-3 text-right text-slate-600 dark:text-slate-300">{{ $money($row['gross_profit']) }}</td><td class="px-4 py-3 text-right font-medium text-emerald-700 dark:text-emerald-300">{{ number_format((float) $row['margin_percent'], 1) }}%</td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-sm text-slate-500">No authorized product profitability data is available for this period.</td></tr>@endforelse</tbody></table>
                </div>
                <div class="divide-y divide-slate-100 sm:hidden dark:divide-slate-800">
                    @forelse($executive['products'][$productGroup] as $row)
                        <div class="p-4"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><p class="truncate text-sm font-semibold text-slate-900 dark:text-white">{{ $row['dimension'] }}</p><p class="mt-0.5 text-xs text-slate-500">{{ $row['sku'] ?: 'No SKU' }} · Qty {{ number_format((float) $row['net_quantity'], 3) }}</p></div><p class="shrink-0 text-sm font-semibold text-slate-950 dark:text-white">{{ $money($row['net_sales']) }}</p></div><div class="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div class="h-full rounded-full bg-indigo-500" style="width: {{ max(3, min(100, ((int) $row['net_sales'] / $productMaximum) * 100)) }}%"></div></div><div class="mt-3 flex justify-between gap-3 text-xs text-slate-500"><span>Gross profit {{ $money($row['gross_profit']) }}</span><span class="font-semibold text-emerald-700 dark:text-emerald-300">{{ number_format((float) $row['margin_percent'], 1) }}% margin</span></div></div>
                    @empty
                        <p class="p-6 text-center text-sm text-slate-500">No authorized product profitability data is available for this period.</p>
                    @endforelse
                </div>
            </article>
        @endforeach
    </section>

    <section class="rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex flex-col gap-3 border-b border-slate-200 p-5 dark:border-slate-800 sm:flex-row sm:items-start sm:justify-between sm:p-6"><div><p class="text-xs font-semibold uppercase text-teal-700 dark:text-teal-300">Location performance</p><h2 class="mt-1 text-lg font-semibold text-slate-950 dark:text-white">Outlet comparison</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Only outlets within your authorized reporting scope are included.</p></div><a href="{{ $reportUrl('outlets') }}" class="text-sm font-semibold text-teal-700 dark:text-teal-300">Open outlet report →</a></div><div class="overflow-x-auto"><table class="w-full min-w-[42rem] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-950/60 dark:text-slate-400"><tr><th class="px-5 py-3 font-semibold">Outlet</th><th class="px-4 py-3 text-right font-semibold">Net sales</th><th class="px-4 py-3 text-right font-semibold">Gross profit</th><th class="px-4 py-3 text-right font-semibold">Margin</th><th class="px-5 py-3 text-right font-semibold">Purchases</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($executive['outlets'] as $index => $row)<tr class="hover:bg-slate-50/70 dark:hover:bg-slate-800/40"><td class="px-5 py-4"><span class="font-semibold text-slate-900 dark:text-white">{{ $row['outlet'] }}</span>@if(count($executive['outlets']) > 1)<span class="ml-2 rounded-full px-2 py-0.5 text-[0.65rem] font-semibold {{ $index === 0 ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300' : ($index === count($executive['outlets']) - 1 ? 'bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300' : 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300') }}">{{ $index === 0 ? 'Leading' : ($index === count($executive['outlets']) - 1 ? 'Needs attention' : '#'.($index + 1)) }}</span>@endif</td><td class="px-4 py-4 text-right font-medium text-slate-900 dark:text-white">{{ $money($row['net_sales']) }}</td><td class="px-4 py-4 text-right text-slate-600 dark:text-slate-300">{{ $money($row['gross_profit']) }}</td><td class="px-4 py-4 text-right text-slate-600 dark:text-slate-300">{{ $row['margin_percent'] === null ? 'Unavailable' : number_format((float) $row['margin_percent'], 2).'%' }}</td><td class="px-5 py-4 text-right text-slate-600 dark:text-slate-300">{{ $money($row['purchases']) }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-slate-500">No authorized outlet activity is available.</td></tr>@endforelse</tbody></table></div></section>

    <section class="grid gap-6 xl:grid-cols-3">
        @php($salespersonMaximum = max(1, (int) collect($executive['salespeople'])->max('net_sales')))
        <article class="rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="border-b border-slate-200 p-5 dark:border-slate-800"><h2 class="font-semibold text-slate-950 dark:text-white">Salesperson performance</h2><p class="mt-1 text-sm text-slate-500">Authorized sale attribution only.</p></div><div class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($executive['salespeople'] as $row)<div class="px-5 py-4"><div class="flex items-center justify-between gap-4"><div class="min-w-0"><p class="truncate text-sm font-semibold text-slate-900 dark:text-white">{{ $row['dimension'] }}</p><p class="mt-1 text-xs text-slate-500">{{ number_format($row['invoice_count']) }} sale document(s)</p></div><div class="shrink-0 text-right"><p class="text-sm font-semibold text-slate-900 dark:text-white">{{ $money($row['net_sales']) }}</p><p class="mt-1 text-xs text-slate-500">{{ $row['margin_percent'] === null ? 'Margin unavailable' : number_format((float) $row['margin_percent'], 1).'% margin' }}</p></div></div><div class="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div class="h-full rounded-full bg-teal-500" style="width: {{ max(3, min(100, ((int) $row['net_sales'] / $salespersonMaximum) * 100)) }}%"></div></div></div>@empty<p class="p-6 text-center text-sm text-slate-500">No attributed sales in this period.</p>@endforelse</div></article>
        @foreach(['customers' => ['Outstanding customers', 'Receivables', 'outstanding'], 'suppliers' => ['Outstanding suppliers', 'Payables', null]] as $group => [$title, $subtitle, $report])
            <article class="rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex items-start justify-between gap-3 border-b border-slate-200 p-5 dark:border-slate-800"><div><h2 class="font-semibold text-slate-950 dark:text-white">{{ $title }}</h2><p class="mt-1 text-sm text-slate-500">{{ $subtitle }} ranked by open balance.</p></div>@if($report)<a href="{{ $reportUrl($report) }}" class="text-sm font-semibold text-teal-700 dark:text-teal-300">View →</a>@else<a href="{{ route('purchases.reports.index') }}" class="text-sm font-semibold text-teal-700 dark:text-teal-300">View →</a>@endif</div><div class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($executive['financial'][$group] as $row)<div class="flex items-center justify-between gap-4 px-5 py-4"><div class="min-w-0"><p class="truncate text-sm font-semibold text-slate-900 dark:text-white">{{ $row['name'] }}</p><p class="mt-1 text-xs text-slate-500">{{ $row['document_count'] }} open document(s)</p></div><p class="shrink-0 text-sm font-semibold text-slate-900 dark:text-white">{{ $money($row['outstanding']) }}</p></div>@empty<p class="p-6 text-center text-sm text-slate-500">No outstanding balance in this period.</p>@endforelse</div></article>
        @endforeach
    </section>

    <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-6"><div><p class="text-xs font-semibold uppercase text-slate-500">Drill into the detail</p><h2 class="mt-1 text-lg font-semibold text-slate-950 dark:text-white">Authorized reports</h2></div><div class="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6">@foreach(['sales' => 'Sales', 'purchases' => 'Purchases', 'inventory' => 'Inventory', 'movements' => 'Stock Movements', 'gst' => 'GST & Tax', 'payments' => 'Payments', 'outstanding' => 'Outstanding', 'returns' => 'Purchase Returns', 'outlets' => 'Outlet Performance', 'cashiers' => 'Cashier Performance'] as $report => $label)<a href="{{ $reportUrl($report) }}" class="flex min-h-12 items-center justify-between gap-3 rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-700 transition hover:border-teal-400 hover:text-teal-700 dark:border-slate-700 dark:text-slate-200 dark:hover:border-teal-500 dark:hover:text-teal-300"><span>{{ $label }}</span><span aria-hidden="true">→</span></a>@endforeach @can('reports.profitability.view')<a href="{{ $reportUrl('profitability') }}" class="flex min-h-12 items-center justify-between gap-3 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm font-semibold text-emerald-800 transition hover:border-emerald-400 dark:border-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-200"><span>Profitability</span><span aria-hidden="true">→</span></a>@endcan</div></section>
</div>
@endsection
