@extends('layouts.admin')

@section('title', 'Company Profile')
@section('page-title', 'Company Profile')
@section('breadcrumbs')<span>/</span><span>Settings</span><span>/</span><span>Company Profile</span>@endsection

@section('content')
    <form method="POST" action="{{ route('settings.company-profile.update') }}" class="mx-auto max-w-4xl space-y-6">@csrf @method('PUT')
        @if($company->hasPlaceholderName())<div class="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950 dark:text-amber-100">Add your store name before issuing your first formal GST invoice.</div>@endif
        <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold text-slate-950 dark:text-white">Business identity</h2><p class="mt-1 text-sm text-slate-500">This updates your store display details without changing your tenant identity.</p><div class="mt-5 grid gap-4 md:grid-cols-2"><label class="text-sm font-medium">Store name<input required name="name" value="{{ old('name',$company->name) }}" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Industry<select required name="industry" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950">@foreach($industries as $industry)<option value="{{ $industry->key }}" @selected(old('industry',$company->industry) === $industry->key)>{{ $industry->label }}</option>@endforeach</select></label><label class="text-sm font-medium">Legal business name<input name="legal_name" value="{{ old('legal_name',$company->legal_name) }}" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">GSTIN<input name="tax_id" value="{{ old('tax_id',$company->tax_id) }}" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Contact mobile<input name="phone" value="{{ old('phone',$company->phone) }}" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Contact email<input type="email" name="email" value="{{ old('email',$company->email) }}" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label></div><label class="mt-4 block text-sm font-medium">Business address<textarea name="address" rows="4" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950">{{ old('address',$company->address) }}</textarea></label></section>
        <div class="flex justify-end"><button class="rounded-md bg-slate-950 px-4 py-2 text-sm font-medium text-white dark:bg-teal-300 dark:text-slate-950">Save company profile</button></div>
    </form>
@endsection
