@extends('layouts.admin')

@section('title', 'Company Profile')
@section('page-title', 'Company Profile')
@section('breadcrumbs')<span>/</span><span>Settings</span><span>/</span><span>Company Profile</span>@endsection

@section('content')
    <form method="POST" action="{{ route('settings.company-profile.update') }}" enctype="multipart/form-data" class="mx-auto max-w-4xl space-y-6">@csrf @method('PUT')
        @can('store.setup.manage')<div class="flex items-center justify-between gap-4 rounded-lg border border-teal-200 bg-teal-50 p-4 text-sm text-teal-900 dark:border-teal-900 dark:bg-teal-950 dark:text-teal-100"><span>Need to revisit your starter configuration?</span><a href="{{ route('onboarding.store-setup.show') }}" class="font-semibold underline">Complete Store Setup</a></div>@endcan
        @can('outlets.manage')<div class="flex items-center justify-between gap-4 rounded-lg border border-slate-200 bg-white p-4 text-sm text-slate-700 shadow-sm dark:border-slate-800 dark:bg-slate-900 dark:text-slate-200"><span>Opening another location? Keep shared products and customers while managing outlet operations separately.</span><a href="{{ route('onboarding.outlets.show') }}" class="font-semibold text-teal-700 underline dark:text-teal-300">Set up outlets</a></div>@endcan
        @if($company->hasPlaceholderName())<div class="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950 dark:text-amber-100">Add your store name before issuing your first formal GST invoice.</div>@endif
        <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold text-slate-950 dark:text-white">Business identity</h2><p class="mt-1 text-sm text-slate-500">This updates your store display details without changing your tenant identity.</p><div class="mt-5 grid gap-4 md:grid-cols-2"><label class="text-sm font-medium">Store name<input required name="name" value="{{ old('name',$company->name) }}" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Industry<select required name="industry" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950">@foreach($industries as $industry)<option value="{{ $industry->key }}" @selected(old('industry',$company->industry) === $industry->key)>{{ $industry->label }}</option>@endforeach</select></label><label class="text-sm font-medium">Legal business name<input name="legal_name" value="{{ old('legal_name',$company->legal_name) }}" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">GSTIN<input name="tax_id" value="{{ old('tax_id',$company->tax_id) }}" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Contact mobile<input name="phone" value="{{ old('phone',$company->phone) }}" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Contact email<input type="email" name="email" value="{{ old('email',$company->email) }}" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label></div><label class="mt-4 block text-sm font-medium">Business address<textarea name="address" rows="4" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950">{{ old('address',$company->address) }}</textarea></label></section>
        <section id="branding" class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
            <div class="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><h2 class="font-semibold text-slate-950 dark:text-white">Company branding</h2><p class="mt-1 max-w-2xl text-sm leading-6 text-slate-500">Your primary logo is used by default on invoices and receipts. An invoice logo can override it without creating duplicate files for every design.</p></div><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600 dark:bg-slate-800 dark:text-slate-300">Private company files</span></div>
            <p class="mt-4 text-xs leading-5 text-slate-500">PNG, JPG, or WEBP only. Maximum 2 MB. Images are stored privately for this company and embedded safely when a document is rendered.</p>
            <div class="mt-5 grid gap-5 md:grid-cols-2">
                @foreach ([
                    ['key' => 'company', 'title' => 'Primary business logo', 'copy' => 'The default mark for every outlet, invoice, and POS receipt.', 'preview' => $branding['company_logo']],
                    ['key' => 'invoice', 'title' => 'Invoice and receipt override', 'copy' => 'Optional. Use only when documents need a different legal or retail mark.', 'preview' => $branding['invoice_logo']],
                ] as $logo)
                    <article class="rounded-lg border border-slate-200 p-4 dark:border-slate-800">
                        <div class="flex items-start justify-between gap-4"><div><h3 class="font-semibold text-slate-900 dark:text-white">{{ $logo['title'] }}</h3><p class="mt-1 text-sm leading-5 text-slate-500">{{ $logo['copy'] }}</p></div><div class="grid h-16 w-28 shrink-0 place-items-center overflow-hidden rounded-lg border border-slate-200 bg-slate-50 p-2 dark:border-slate-700 dark:bg-slate-950">@if($logo['preview'])<img src="{{ $logo['preview'] }}" alt="{{ $logo['title'] }} preview" class="max-h-full max-w-full object-contain">@else<span class="text-center text-xs font-medium text-slate-400">No logo</span>@endif</div></div>
                        <label class="mt-4 block text-sm font-medium text-slate-700 dark:text-slate-200">{{ $logo['preview'] ? 'Replace logo' : 'Upload logo' }}<input type="file" name="{{ $logo['key'] }}_logo" accept="image/png,image/jpeg,image/webp" class="mt-2 block w-full text-sm text-slate-500 file:mr-3 file:rounded-md file:border-0 file:bg-slate-100 file:px-3 file:py-2 file:text-sm file:font-semibold file:text-slate-700 hover:file:bg-slate-200 dark:file:bg-slate-800 dark:file:text-slate-200">@error($logo['key'].'_logo')<span class="mt-1 block text-sm font-normal text-rose-600">{{ $message }}</span>@enderror</label>
                        @if($logo['preview'])<label class="mt-3 flex items-center gap-2 text-sm text-rose-700 dark:text-rose-300"><input type="hidden" name="remove_{{ $logo['key'] }}_logo" value="0"><input type="checkbox" name="remove_{{ $logo['key'] }}_logo" value="1" class="rounded border-slate-300 text-rose-600 focus:ring-rose-500"> Remove this logo when saving</label>@endif
                    </article>
                @endforeach
            </div>
            <div class="mt-5 rounded-lg bg-slate-50 p-4 text-sm text-slate-600 dark:bg-slate-950 dark:text-slate-300"><strong class="text-slate-900 dark:text-white">Document precedence:</strong> invoice or receipt override, then the company primary logo, then the company name with no image. Branch-specific logo overrides are not configured in this release.</div>
        </section>
        <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
            <h2 class="font-semibold text-slate-950 dark:text-white">Authorized signature</h2><p class="mt-1 text-sm text-slate-500">This private image is embedded only when a new invoice or quotation is created with its signature option enabled.</p>
            <div class="mt-5 grid gap-5 md:grid-cols-[160px_minmax(0,1fr)]"><div class="grid min-h-28 place-items-center rounded-lg border border-dashed border-slate-300 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-950">@if($signature['data_uri'])<img src="{{ $signature['data_uri'] }}" alt="Authorized signature preview" class="max-h-20 max-w-full object-contain">@else<span class="text-center text-xs text-slate-400">No signature uploaded</span>@endif</div><div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium">Authorized signatory<input name="authorized_signatory_name" value="{{ old('authorized_signatory_name',$company->authorized_signatory_name) }}" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="text-sm font-medium">Designation<input name="authorized_signatory_designation" value="{{ old('authorized_signatory_designation',$company->authorized_signatory_designation) }}" class="mt-1 w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label><label class="sm:col-span-2 text-sm font-medium">Upload signature<input type="file" name="authorized_signature" accept="image/png,image/jpeg,image/webp" class="mt-1 block w-full text-sm text-slate-500">@error('authorized_signature')<span class="mt-1 block text-rose-600">{{ $message }}</span>@enderror<span class="mt-1 block text-xs font-normal text-slate-500">PNG, JPG, or WEBP, up to 1 MB. SVG and public URLs are not accepted.</span></label>@if($company->authorized_signature_path)<label class="sm:col-span-2 flex items-center gap-2 text-sm text-rose-700"><input type="hidden" name="remove_authorized_signature" value="0"><input type="checkbox" name="remove_authorized_signature" value="1"> Remove current signature</label>@endif</div></div>
        </section>
        <div class="flex justify-end"><button class="rounded-md bg-slate-950 px-4 py-2 text-sm font-medium text-white dark:bg-teal-300 dark:text-slate-950">Save company profile</button></div>
    </form>
@endsection
