@extends('layouts.admin')

@section('title', 'Create Support Ticket')
@section('page-title', 'Create Support Ticket')

@section('content')
    <div class="space-y-6">
        @include('command-center.crm.partials.nav')
        <section class="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p class="text-sm font-semibold text-sky-700 dark:text-sky-300">Customer care workspace</p><h1 class="mt-1 text-2xl font-semibold text-slate-950 dark:text-white">Create Support Ticket</h1><p class="mt-2 text-sm text-slate-500 dark:text-slate-400">Capture the customer issue once. SLA deadlines are applied automatically from the selected priority.</p></div><a href="{{ route('crm.support.tickets.index') }}" class="text-sm font-semibold text-slate-600 hover:text-slate-950 dark:text-slate-300 dark:hover:text-white">Back to tickets</a></section>

        <form method="POST" action="{{ route('crm.support.tickets.store') }}" class="space-y-6">@csrf
            <section class="form-section"><h2 class="form-section-title">Customer and context</h2><p class="form-section-help">Link the request to a customer where possible. This keeps support history visible on the customer and onboarding records.</p><div class="mt-5 grid gap-4 md:grid-cols-2"><label class="block text-sm font-semibold text-slate-700 dark:text-slate-200">Customer<select name="customer_id" class="mt-2 w-full"><option value="">No customer linked</option>@foreach ($customers as $customer)<option value="{{ $customer->id }}" @selected((string) old('customer_id', $ticket['customer_id'] ?? null) === (string) $customer->id)>{{ $customer->company_name ?: $customer->display_name }}</option>@endforeach</select></label><label class="block text-sm font-semibold text-slate-700 dark:text-slate-200">Source<select name="source" class="mt-2 w-full">@foreach (\App\Enums\Crm\SupportTicketSource::cases() as $source)<option value="{{ $source->value }}" @selected(old('source', 'internal') === $source->value)>{{ $source->label() }}</option>@endforeach</select></label><input type="hidden" name="lead_id" value="{{ old('lead_id', $ticket['lead_id'] ?? null) }}"><input type="hidden" name="onboarding_id" value="{{ old('onboarding_id', $ticket['onboarding_id'] ?? null) }}"><input type="hidden" name="proforma_invoice_id" value="{{ old('proforma_invoice_id', $ticket['proforma_invoice_id'] ?? null) }}"></div>@if ($onboarding ?? $proforma)<div class="mt-4 rounded-lg border border-sky-200 bg-sky-50 p-4 text-sm text-sky-900 dark:border-sky-900 dark:bg-sky-950/30 dark:text-sky-100">This ticket is linked to {{ $onboarding ? 'onboarding '.$onboarding->onboarding_number : 'proforma '.$proforma->proforma_number }}.</div>@endif</section>
            <section class="form-section"><h2 class="form-section-title">Request details</h2><p class="form-section-help">Write a concise subject and enough detail for the person handling the request.</p><div class="mt-5 grid gap-4"><label class="block text-sm font-semibold text-slate-700 dark:text-slate-200">Subject<input name="subject" required maxlength="255" value="{{ old('subject') }}" class="mt-2 w-full" placeholder="What does the customer need help with?"></label><label class="block text-sm font-semibold text-slate-700 dark:text-slate-200">Description<textarea name="description" required maxlength="10000" rows="7" class="mt-2 w-full" placeholder="Describe the issue, impact, and any useful context.">{{ old('description') }}</textarea></label><div class="grid gap-4 md:grid-cols-3"><label class="block text-sm font-semibold text-slate-700 dark:text-slate-200">Category<select name="category" class="mt-2 w-full">@foreach (\App\Enums\Crm\SupportTicketCategory::cases() as $category)<option value="{{ $category->value }}" @selected(old('category', 'general') === $category->value)>{{ $category->label() }}</option>@endforeach</select></label><label class="block text-sm font-semibold text-slate-700 dark:text-slate-200">Priority<select name="priority" class="mt-2 w-full">@foreach (\App\Enums\Crm\SupportTicketPriority::cases() as $priority)<option value="{{ $priority->value }}" @selected(old('priority', 'normal') === $priority->value)>{{ $priority->label() }}</option>@endforeach</select></label><label class="block text-sm font-semibold text-slate-700 dark:text-slate-200">Assigned to<select name="assigned_to" class="mt-2 w-full"><option value="">Assign later</option>@foreach ($owners as $owner)<option value="{{ $owner->id }}" @selected((string) old('assigned_to') === (string) $owner->id)>{{ $owner->name }}</option>@endforeach</select></label></div></div></section>
            <section class="form-section"><h2 class="form-section-title">Reporter contact</h2><p class="form-section-help">These details are prefilled from the selected customer when available. Add at least one detail if there is no customer link.</p><div class="mt-5 grid gap-4 md:grid-cols-3"><label class="block text-sm font-semibold text-slate-700 dark:text-slate-200">Name<input name="reported_by_name" value="{{ old('reported_by_name', $ticket['reported_by_name'] ?? null) }}" class="mt-2 w-full"></label><label class="block text-sm font-semibold text-slate-700 dark:text-slate-200">Email<input type="email" name="reported_by_email" value="{{ old('reported_by_email', $ticket['reported_by_email'] ?? null) }}" class="mt-2 w-full"></label><label class="block text-sm font-semibold text-slate-700 dark:text-slate-200">Phone<input name="reported_by_phone" value="{{ old('reported_by_phone', $ticket['reported_by_phone'] ?? null) }}" class="mt-2 w-full"></label></div></section>
            <section class="form-section"><h2 class="form-section-title">Internal planning</h2><p class="form-section-help">Optional internal guidance. The customer cannot see this note in the future portal.</p><div class="mt-5 grid gap-4 md:grid-cols-2"><label class="block text-sm font-semibold text-slate-700 dark:text-slate-200">Custom due date<input type="datetime-local" name="due_at" value="{{ old('due_at') }}" class="mt-2 w-full"></label><label class="block text-sm font-semibold text-slate-700 dark:text-slate-200">Internal remarks<textarea name="internal_remarks" rows="3" class="mt-2 w-full" placeholder="Private handoff or investigation notes.">{{ old('internal_remarks') }}</textarea></label></div></section>
            @if ($errors->any())<section class="rounded-lg border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800 dark:border-rose-900 dark:bg-rose-950/30 dark:text-rose-200"><p class="font-semibold">Please review the highlighted fields.</p><ul class="mt-2 list-disc pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></section>@endif
            <div class="sticky-form-actions"><a href="{{ route('crm.support.tickets.index') }}" class="rounded-lg px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800">Cancel</a><button class="rounded-lg bg-slate-950 px-5 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-slate-800 active:translate-y-px dark:bg-teal-300 dark:text-slate-950">Create Ticket</button></div>
        </form>
    </div>
@endsection
