@extends('layouts.admin')

@section('title', $ticket->ticket_number)
@section('page-title', 'Support Ticket')

@section('breadcrumbs')
    <span>/</span><span>CRM</span><span>/</span><a href="{{ route('crm.support.tickets.index') }}" class="hover:text-slate-950 dark:hover:text-white">Support Tickets</a><span>/</span><span>{{ $ticket->ticket_number }}</span>
@endsection

@section('content')
    @php
        $priorityClasses = ['urgent' => 'bg-rose-100 text-rose-800 dark:bg-rose-950/70 dark:text-rose-200', 'high' => 'bg-amber-100 text-amber-800 dark:bg-amber-950/70 dark:text-amber-200', 'normal' => 'bg-sky-100 text-sky-800 dark:bg-sky-950/70 dark:text-sky-200', 'low' => 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-200'];
        $statusClasses = ['new' => 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-200', 'open' => 'bg-sky-100 text-sky-800 dark:bg-sky-950/70 dark:text-sky-200', 'in_progress' => 'bg-indigo-100 text-indigo-800 dark:bg-indigo-950/70 dark:text-indigo-200', 'waiting_for_customer' => 'bg-amber-100 text-amber-800 dark:bg-amber-950/70 dark:text-amber-200', 'waiting_for_internal_team' => 'bg-violet-100 text-violet-800 dark:bg-violet-950/70 dark:text-violet-200', 'resolved' => 'bg-teal-100 text-teal-800 dark:bg-teal-950/70 dark:text-teal-200', 'closed' => 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950/70 dark:text-emerald-200', 'reopened' => 'bg-orange-100 text-orange-800 dark:bg-orange-950/70 dark:text-orange-200'];
        $transitions = ['new' => ['open'], 'open' => ['in_progress'], 'in_progress' => ['waiting_for_customer', 'waiting_for_internal_team', 'resolved'], 'waiting_for_customer' => ['in_progress', 'resolved'], 'waiting_for_internal_team' => ['in_progress', 'resolved'], 'resolved' => ['closed', 'reopened'], 'closed' => ['reopened'], 'reopened' => ['in_progress']];
        $availableTransitions = $transitions[$ticket->status->value] ?? [];
    @endphp
    <div class="space-y-6">
        @include('command-center.crm.partials.nav')
        <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
            <div class="flex flex-col justify-between gap-5 lg:flex-row lg:items-start"><div class="min-w-0"><p class="text-sm font-semibold text-sky-700 dark:text-sky-300">{{ $ticket->ticket_number }}</p><h1 class="mt-2 text-2xl font-semibold text-slate-950 dark:text-white">{{ $ticket->subject }}</h1><p class="mt-2 text-sm text-slate-500 dark:text-slate-400">Created {{ $ticket->created_at->format('d M Y, h:i A') }} · {{ $ticket->category->label() }} via {{ $ticket->source->label() }}</p></div><div class="flex flex-wrap gap-2"><span class="support-status-badge inline-flex rounded-full px-3 py-1.5 text-sm font-semibold {{ $statusClasses[$ticket->status->value] }}">{{ $ticket->status->label() }}</span><span class="inline-flex rounded-full px-3 py-1.5 text-sm font-semibold {{ $priorityClasses[$ticket->priority->value] }}">{{ $ticket->priority->label() }}</span><a href="{{ route('crm.support.tickets.index') }}" class="inline-flex min-h-10 items-center rounded-lg border border-slate-300 px-3 text-sm font-semibold text-slate-700 transition hover:bg-slate-50 dark:border-slate-700 dark:text-slate-200 dark:hover:bg-slate-800">All tickets</a></div></div>
        </section>

        <section class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_22rem]">
            <div class="space-y-6">
                <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="text-base font-semibold text-slate-950 dark:text-white">Request</h2><p class="mt-4 whitespace-pre-line text-sm leading-7 text-slate-700 dark:text-slate-200">{{ $ticket->description }}</p>@if($ticket->internal_remarks)<div class="mt-5 rounded-lg border border-violet-200 bg-violet-50 p-4 dark:border-violet-900 dark:bg-violet-950/30"><p class="text-xs font-semibold uppercase tracking-wide text-violet-700 dark:text-violet-300">Private internal remarks</p><p class="mt-2 whitespace-pre-line text-sm text-violet-950 dark:text-violet-100">{{ $ticket->internal_remarks }}</p></div>@endif</section>

                <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex items-center justify-between gap-4"><div><h2 class="text-base font-semibold text-slate-950 dark:text-white">Conversation</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Internal notes remain private. Customer-safe replies are ready for future customer delivery channels.</p></div><span class="text-xs font-semibold text-slate-500">{{ $ticket->messages->count() }} entries</span></div>
                    @can('crm.support.reply')<form method="POST" action="{{ route('crm.support.tickets.messages.store', $ticket) }}" class="mt-5 rounded-lg border border-slate-200 bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-950/40">@csrf<label class="block text-sm font-semibold text-slate-700 dark:text-slate-200">Add a note or reply<textarea name="message" required rows="4" class="mt-2 w-full" placeholder="Write a clear update for the team or customer."></textarea></label><div class="mt-3 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><label class="flex items-center gap-2 text-sm font-medium text-slate-700 dark:text-slate-200"><select name="visibility"><option value="internal">Private internal note</option><option value="customer_safe">Customer-safe reply</option></select></label><button class="rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-slate-800 active:translate-y-px dark:bg-teal-300 dark:text-slate-950">Add message</button></div></form>@endcan
                    <div class="mt-5 space-y-4">@forelse ($ticket->messages as $message)<article class="support-timeline-entry rounded-lg border p-4 {{ $message->visibility->value === 'internal' ? 'border-violet-200 bg-violet-50/70 dark:border-violet-900 dark:bg-violet-950/20' : 'border-sky-200 bg-sky-50/70 dark:border-sky-900 dark:bg-sky-950/20' }}"><div class="flex flex-col justify-between gap-2 sm:flex-row sm:items-center"><span class="inline-flex w-fit items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold {{ $message->visibility->value === 'internal' ? 'bg-violet-100 text-violet-800 dark:bg-violet-900/60 dark:text-violet-100' : 'bg-sky-100 text-sky-800 dark:bg-sky-900/60 dark:text-sky-100' }}">{{ $message->visibility->value === 'internal' ? 'Private internal note' : 'Customer-safe reply' }}</span><p class="text-xs text-slate-500 dark:text-slate-400">{{ $message->creator?->name ?? 'System' }} · {{ $message->created_at->format('d M Y, h:i A') }}</p></div><p class="mt-3 whitespace-pre-line text-sm leading-6 text-slate-800 dark:text-slate-100">{{ $message->message }}</p></article>@empty<p class="rounded-lg border border-dashed border-slate-300 px-4 py-10 text-center text-sm text-slate-500 dark:border-slate-700">No messages yet. Add an internal note to begin the support timeline.</p>@endforelse</div>
                </section>

                <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex items-center justify-between gap-4"><div><h2 class="text-base font-semibold text-slate-950 dark:text-white">Attachments</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">External links only in this foundation. File storage can be connected later.</p></div></div>@can('crm.support.update')<form method="POST" action="{{ route('crm.support.tickets.attachments.store', $ticket) }}" class="mt-4 grid gap-3 sm:grid-cols-[1fr_1.5fr_auto]">@csrf<input name="title" required placeholder="Link title"><input type="url" name="external_url" required placeholder="https://…"><button class="rounded-lg border border-slate-300 px-4 text-sm font-semibold text-slate-700 transition hover:bg-slate-50 dark:border-slate-700 dark:text-slate-200 dark:hover:bg-slate-800">Add link</button></form>@endcan<div class="mt-4 space-y-2">@forelse($ticket->attachments as $attachment)<a href="{{ $attachment->external_url }}" target="_blank" rel="noopener noreferrer" class="support-ticket-row flex items-center justify-between rounded-lg border border-slate-200 p-3 text-sm transition dark:border-slate-800"><span class="font-medium text-slate-900 dark:text-white">{{ $attachment->title }}</span><span class="text-sky-700 dark:text-sky-300">Open link</span></a>@empty<p class="text-sm text-slate-500">No external links are attached to this ticket.</p>@endforelse</div></section>

                <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="text-base font-semibold text-slate-950 dark:text-white">Status history</h2><div class="mt-5 space-y-4">@forelse($ticket->statusHistories as $history)<div class="support-status-history relative pl-6"><span class="absolute left-0 top-1.5 size-3 rounded-full bg-sky-500 ring-4 ring-sky-100 dark:ring-sky-950"></span><p class="text-sm font-medium text-slate-900 dark:text-white">{{ $history->old_status ? \App\Enums\Crm\SupportTicketStatus::from($history->old_status)->label().' to ' : '' }}{{ \App\Enums\Crm\SupportTicketStatus::from($history->new_status)->label() }}</p>@if($history->note)<p class="mt-1 text-sm text-slate-600 dark:text-slate-300">{{ $history->note }}</p>@endif<p class="mt-1 text-xs text-slate-500">{{ $history->changer?->name ?? 'System' }} · {{ $history->created_at->format('d M Y, h:i A') }}</p></div>@empty<p class="text-sm text-slate-500">No status history recorded.</p>@endforelse</div></section>
            </div>

            <aside class="space-y-6">
                <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="text-base font-semibold text-slate-950 dark:text-white">Customer</h2><div class="mt-4 space-y-3"><p class="font-semibold text-slate-900 dark:text-white">{{ $ticket->customer?->company_name ?? $ticket->reported_by_name ?? 'Unlinked request' }}</p><p class="text-sm text-slate-600 dark:text-slate-300">{{ $ticket->reported_by_name }}</p><p class="text-sm text-slate-500">{{ $ticket->reported_by_email ?: 'No email recorded' }}</p><p class="text-sm text-slate-500">{{ $ticket->reported_by_phone ?: 'No phone recorded' }}</p>@if($ticket->customer)<a href="{{ route('crm.customers.show', $ticket->customer) }}" class="inline-flex text-sm font-semibold text-sky-700 hover:text-sky-900 dark:text-sky-300">Open customer profile</a>@endif</div></section>
                <section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="text-base font-semibold text-slate-950 dark:text-white">SLA and ownership</h2><div class="mt-4 space-y-4"><div><div class="flex justify-between gap-3 text-sm"><span class="text-slate-500">First response</span><span class="font-semibold {{ $sla['first_response_overdue'] ? 'text-rose-700 dark:text-rose-300' : 'text-slate-900 dark:text-white' }}">{{ $ticket->first_response_due_at?->format('d M, h:i A') ?? 'Not set' }}</span></div><div class="support-sla-track mt-2"><div class="support-sla-bar {{ $sla['first_response_overdue'] ? 'is-overdue' : '' }}" style="width: {{ $sla['first_response_overdue'] ? 100 : ($sla['at_risk'] ? 78 : 38) }}%"></div></div></div><div><div class="flex justify-between gap-3 text-sm"><span class="text-slate-500">Resolution due</span><span class="font-semibold {{ $sla['overdue'] ? 'text-rose-700 dark:text-rose-300' : 'text-slate-900 dark:text-white' }}">{{ $ticket->due_at?->format('d M, h:i A') ?? 'Not set' }}</span></div><div class="support-sla-track mt-2"><div class="support-sla-bar {{ $sla['overdue'] ? 'is-overdue' : ($sla['at_risk'] ? 'is-risk' : '') }}" style="width: {{ $sla['overdue'] ? 100 : ($sla['at_risk'] ? 78 : 38) }}%"></div></div></div><div class="border-t border-slate-100 pt-4 dark:border-slate-800"><p class="text-xs font-semibold uppercase tracking-wide text-slate-500">Assigned to</p><p class="mt-1 font-semibold text-slate-900 dark:text-white">{{ $ticket->assignee?->name ?? 'Unassigned' }}</p></div></div></section>
                @can('crm.support.update')<section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="text-base font-semibold text-slate-950 dark:text-white">Manage ticket</h2><form method="POST" action="{{ route('crm.support.tickets.update', $ticket) }}" class="mt-4 space-y-4">@csrf @method('PUT')<label class="block text-sm font-semibold text-slate-700 dark:text-slate-200">Status<select name="status" class="mt-2 w-full"><option value="{{ $ticket->status->value }}">Keep {{ $ticket->status->label() }}</option>@foreach($availableTransitions as $transition)<option value="{{ $transition }}">{{ \App\Enums\Crm\SupportTicketStatus::from($transition)->label() }}</option>@endforeach</select></label><label class="block text-sm font-semibold text-slate-700 dark:text-slate-200">Assigned to<select name="assigned_to" class="mt-2 w-full"><option value="">Unassigned</option>@foreach($owners as $owner)<option value="{{ $owner->id }}" @selected($ticket->assigned_to === $owner->id)>{{ $owner->name }}</option>@endforeach</select></label><label class="block text-sm font-semibold text-slate-700 dark:text-slate-200">Priority<select name="priority" class="mt-2 w-full">@foreach(\App\Enums\Crm\SupportTicketPriority::cases() as $priority)<option value="{{ $priority->value }}" @selected($ticket->priority === $priority)>{{ $priority->label() }}</option>@endforeach</select></label><label class="block text-sm font-semibold text-slate-700 dark:text-slate-200">Status note<textarea name="status_note" rows="2" class="mt-2 w-full" placeholder="Optional internal status context."></textarea></label>@if(in_array('resolved', $availableTransitions, true) || $ticket->status->value === 'resolved')<label class="block text-sm font-semibold text-slate-700 dark:text-slate-200">Resolution summary<textarea name="resolution_summary" rows="3" class="mt-2 w-full" placeholder="Required before resolving.">{{ $ticket->resolution_summary }}</textarea></label>@endif<button class="w-full rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-slate-800 active:translate-y-px dark:bg-teal-300 dark:text-slate-950">Save changes</button></form></section>@endcan
                @if($ticket->resolution_summary)<section class="rounded-lg border border-teal-200 bg-teal-50 p-5 dark:border-teal-900 dark:bg-teal-950/30"><h2 class="text-base font-semibold text-teal-950 dark:text-teal-100">Resolution</h2><p class="mt-2 whitespace-pre-line text-sm leading-6 text-teal-900 dark:text-teal-100">{{ $ticket->resolution_summary }}</p><p class="mt-3 text-xs text-teal-700 dark:text-teal-300">Resolved {{ $ticket->resolved_at?->format('d M Y, h:i A') }}</p></section>@endif
            </aside>
        </section>
    </div>
@endsection
