@extends('layouts.admin')
@section('title', 'My attendance')
@section('page-title', 'My attendance')
@section('content')
<div class="mx-auto max-w-6xl space-y-6">
    <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-semibold text-teal-700">{{ $timezone }}</p><h1 class="mt-1 text-2xl font-semibold text-slate-950">Today at a glance</h1><p class="mt-2 text-sm text-slate-500">Attendance is recorded only when you take an action.</p></div><a href="{{ route('attendance.history') }}" class="text-sm font-semibold text-teal-700">Attendance history</a></div>
    <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p class="text-sm text-slate-500">{{ $record?->outlet?->name ?: ($employee->primaryBranch?->name ?: 'Outlet not set') }}</p><h2 class="mt-1 text-xl font-semibold text-slate-950">{{ $record?->attendance_state === 'completed' ? 'Day complete' : ($record?->checked_in_at ? 'You are checked in' : 'Ready when you are') }}</h2><p class="mt-1 text-sm text-slate-500">{{ $record?->shiftAssignment?->shift?->name ?: 'No shift assigned for today' }}</p></div>
        @if(! $record?->checked_in_at)<form method="POST" action="{{ route('attendance.check-in') }}">@csrf<button class="w-full rounded-lg bg-slate-950 px-5 py-3 text-sm font-semibold text-white sm:w-auto">Check in</button></form>
        @elseif(! $record?->checked_out_at)<div class="flex flex-wrap gap-2">@if($record->breaks->firstWhere('ended_at', null))<form method="POST" action="{{ route('attendance.breaks.end', $record->breaks->firstWhere('ended_at', null)) }}">@csrf<button class="rounded-lg border border-amber-300 bg-amber-50 px-4 py-2 text-sm font-semibold text-amber-800">End break</button></form>@else<form method="POST" action="{{ route('attendance.breaks.start', $record) }}" class="flex gap-2">@csrf<select name="break_type" class="rounded-lg border-slate-300 text-sm"><option value="short_break">Short break</option><option value="meal">Meal</option><option value="official_duty">Official duty</option></select><button class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700">Start break</button></form>@endif<form method="POST" action="{{ route('attendance.check-out', $record) }}">@csrf<button class="rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white">Check out</button></form></div>@endif</div>
        @if($record?->checked_in_at)<div class="mt-5 grid gap-3 sm:grid-cols-4"><div class="rounded-lg bg-teal-50 p-3"><p class="text-xs text-teal-700">Checked in</p><p class="mt-1 font-semibold">{{ $record->checked_in_at->timezone($timezone)->format('g:i A') }}</p></div><div class="rounded-lg bg-slate-50 p-3"><p class="text-xs text-slate-500">Worked</p><p class="mt-1 font-semibold">{{ intdiv($record->worked_minutes, 60) }}h {{ $record->worked_minutes % 60 }}m</p></div><div class="rounded-lg bg-slate-50 p-3"><p class="text-xs text-slate-500">Breaks</p><p class="mt-1 font-semibold">{{ $record->total_break_minutes }}m</p></div><div class="rounded-lg bg-slate-50 p-3"><p class="text-xs text-slate-500">Status</p><p class="mt-1 font-semibold">{{ str($record->attendance_status)->headline() }}</p></div></div>@endif
    </section>
    <div class="grid gap-6 lg:grid-cols-2"><section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-slate-950">Upcoming shifts</h2><div class="mt-4 space-y-3">@forelse($upcoming as $assignment)<div class="flex items-center justify-between rounded-lg bg-slate-50 p-3 text-sm"><span><strong>{{ $assignment->work_date->format('D, j M') }}</strong><span class="ml-2 text-slate-500">{{ $assignment->shift?->name }}</span></span><span class="text-slate-500">{{ $assignment->outlet?->name }}</span></div>@empty<p class="text-sm text-slate-500">No upcoming shifts assigned.</p>@endforelse</div></section><section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex justify-between"><h2 class="font-semibold text-slate-950">Leave balances</h2><a href="{{ route('attendance.leave.self') }}" class="text-sm font-semibold text-teal-700">Request leave</a></div><div class="mt-4 space-y-3">@forelse($balances as $balance)<div class="flex justify-between rounded-lg bg-slate-50 p-3 text-sm"><span>{{ $balance->leaveType?->name }}</span><strong>{{ $balance->remaining }} days</strong></div>@empty<p class="text-sm text-slate-500">Leave balances appear when policies are assigned.</p>@endforelse</div></section></div>
    <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-slate-950">Recent attendance</h2><div class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@forelse($recent as $item)<div class="rounded-lg bg-slate-50 p-3 text-sm"><strong>{{ $item->attendance_date->format('j M') }}</strong><p class="mt-1 text-slate-500">{{ str($item->attendance_status)->headline() }} · {{ $item->worked_minutes }} min</p></div>@empty<p class="text-sm text-slate-500">Your recent attendance will appear here.</p>@endforelse</div></section>
</div>
@endsection
