@extends('layouts.admin')

@section('title', 'Subscription Plans')
@section('page-title', 'Subscription Plans')
@section('breadcrumbs')<span>/</span><span>Platform</span><span>/</span><span>Plans</span>@endsection

@section('content')
    @include('command-center.saas.partials.nav')
    <div class="mb-5 flex items-center justify-between gap-4"><p class="text-sm text-slate-500 dark:text-slate-400">Plan changes are versioned. Current subscriptions keep their original price and access snapshots.</p><a href="{{ route('saas.plans.create') }}" class="shrink-0 rounded-md bg-slate-950 px-4 py-2 text-sm font-medium text-white dark:bg-teal-300 dark:text-slate-950">New plan</a></div>
    <div class="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm dark:divide-slate-800"><thead class="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500 dark:bg-slate-800"><tr><th class="px-5 py-3">Plan</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Billing</th><th class="px-5 py-3">Base price</th><th class="px-5 py-3">Versions</th><th class="px-5 py-3"></th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($plans as $plan)<tr class="hover:bg-slate-50 dark:hover:bg-slate-800"><td class="px-5 py-4"><a class="font-medium text-slate-900 dark:text-white" href="{{ route('saas.plans.show', $plan) }}">{{ $plan->name }}</a><p class="mt-1 text-xs text-slate-500">{{ $plan->code }}</p></td><td class="px-5 py-4"><x-status-badge :status="$plan->status" /></td><td class="px-5 py-4">{{ str($plan->billing_interval)->headline() }}</td><td class="px-5 py-4">{{ $plan->currency }} {{ number_format((float) $plan->base_price, 2) }}</td><td class="px-5 py-4">{{ $plan->versions_count }}</td><td class="px-5 py-4 text-right"><a href="{{ route('saas.plans.edit', $plan) }}" class="font-medium text-sky-700 hover:text-sky-900 dark:text-sky-300">Edit</a></td></tr>@empty<tr><td colspan="6" class="px-5 py-10 text-center text-slate-500">No plans have been created yet.</td></tr>@endforelse</tbody></table></div></div><div class="mt-4">{{ $plans->links() }}</div>
@endsection
