@extends('layouts.admin')

@section('title', $plan->name)
@section('page-title', $plan->name)
@section('breadcrumbs')<span>/</span><span>Platform</span><span>/</span><a href="{{ route('saas.plans.index') }}">Plans</a><span>/</span><span>{{ $plan->name }}</span>@endsection

@section('content')
    @include('command-center.saas.partials.nav')
    <div class="flex flex-wrap items-start justify-between gap-4"><div><div class="flex items-center gap-2"><h2 class="text-xl font-semibold text-slate-950 dark:text-white">{{ $plan->name }}</h2><x-status-badge :status="$plan->status" /></div><p class="mt-1 text-sm text-slate-500">{{ $plan->code }} · {{ $plan->currency }} {{ number_format((float) $plan->base_price, 2) }} / {{ str($plan->billing_interval)->headline() }}</p></div><div class="flex gap-2"><form method="POST" action="{{ route('saas.plans.duplicate', $plan) }}">@csrf<button class="rounded-md border border-slate-300 px-3 py-2 text-sm font-medium dark:border-slate-700">Duplicate</button></form><a href="{{ route('saas.plans.edit', $plan) }}" class="rounded-md bg-slate-950 px-3 py-2 text-sm font-medium text-white dark:bg-teal-300 dark:text-slate-950">Edit plan</a></div></div>
    <div class="mt-6 grid gap-6 lg:grid-cols-2"><section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold text-slate-950 dark:text-white">Features</h2><div class="mt-4 flex flex-wrap gap-2">@forelse($plan->features->where('is_enabled',true) as $feature)<span class="rounded-full bg-teal-50 px-3 py-1 text-sm text-teal-800 dark:bg-teal-950 dark:text-teal-200">{{ str($feature->feature_key)->replace('_',' ')->headline() }}</span>@empty<p class="text-sm text-slate-500">No features included.</p>@endforelse</div></section><section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-semibold text-slate-950 dark:text-white">Limits</h2><dl class="mt-4 grid grid-cols-2 gap-x-5 gap-y-3 text-sm">@forelse($plan->limits as $limit)<div><dt class="text-slate-500">{{ str($limit->limit_key)->replace('_',' ')->headline() }}</dt><dd class="mt-1 font-medium text-slate-900 dark:text-white">{{ $limit->limit_value === null ? 'Unlimited' : number_format($limit->limit_value) }}</dd></div>@empty<p class="text-slate-500">No limits configured.</p>@endforelse</dl></section></div>
    <section class="mt-6 rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="border-b border-slate-200 px-5 py-4 dark:border-slate-800"><h2 class="font-semibold text-slate-950 dark:text-white">Plan history</h2><p class="mt-1 text-sm text-slate-500">Versions preserve what was offered at each edit. Subscription records retain their own snapshot.</p></div><div class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($plan->versions as $version)<div class="flex items-center justify-between px-5 py-4 text-sm"><span>Version {{ $version->version }}</span><span class="text-slate-500">{{ $version->created_at?->format('d M Y, H:i') }}</span></div>@empty<p class="px-5 py-8 text-sm text-slate-500">No saved versions yet.</p>@endforelse</div></section>
    @if($plan->status !== 'archived')<form method="POST" action="{{ route('saas.plans.archive', $plan) }}" class="mt-6" onsubmit="return confirm('Archive this plan? Existing subscriptions will not change.')">@csrf<button class="text-sm font-medium text-rose-700 dark:text-rose-300">Archive plan</button></form>@endif
@endsection
